{
  "hash": "497a62c790504b1c1fb5fc26cb5bea75",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 5: Poisson Regression\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Yeaju Diana Kim\"\ndate: \"2026-03-18\"\ndate-modified: today\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\n    toc-location: left\nexecute: \n  message: false\n  warning: false\nengine: knitr\n---\n\n## Instructions\n\n-   If you are fitting a model, display the model output in a neatly formatted table. (The `tidy()` and `kable()` functions can help!)\n-   If you are creating a plot, use clear labels for all axes, titles, etc.\n-   Commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages.\n-   When you're done, we should be able to knit the final version of the QMD in your GitHub as an HTML.\n\n::: callout-tip\n## Workflow tip\n\nWork through the lab by running chunks **one at a time** in RStudio (Cmd/Ctrl + Enter), not by rendering the whole document. Render only at the end, once all your code is working.\n\nThis is how most R users actually work — you'd write a line, run it, check the output, and iterate. Rendering is for producing the final document. When you render, Quarto starts a fresh R session and runs every chunk top-to-bottom, so if anything is incomplete, everything downstream breaks. When you work interactively using chunks, your environment builds up as you go, so you always have your objects available to inspect and troubleshoot.\n\nThe **\"Run All Chunks Above\"** button (downward arrow with a bar, next to the green play button in each chunk) is another useful tool. It re-runs everything from the top of the document up to your current chunk, so all your objects are up to date before you start working on the next question.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(MASS)\nlibrary(naniar)\nlibrary(skimr)\nlibrary(emmeans)\nlibrary(ggeffects)\nlibrary(easystats)\nlibrary(performance)\nlibrary(knitr)\nlibrary(modelsummary)\nlibrary(pscl)\n\noptions(scipen = 999)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 1: Data Preparation & Cleaning\n\nThis lab accompanies a pre-registration document. Download it here: [Pre-Registration (PDF)](https://github.com/suyoghc/PSY504_Spring_2026/raw/main/posts/Poisson/Lab_Poisson_Pre-Registration.pdf). Refer to Hypothesis (a) for the variables and analysis plan you'll be implementing.\n\nThe data come from the 2010 General Social Survey (GSS). As described in the pre-registration, we are testing whether the number of hours per week a person spends on the Internet (`wwwhr`) is predicted by their vocabulary (`wordsum`), age (`age`), sex (`sex`), religiosity (`reliten`), political orientation (`polviews`), and how often they work from home (`wrkhome`).\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndata <- read_delim(\"https://raw.githubusercontent.com/jgeller112/psy504-advanced-stats/main/slides/Poisson/data/2010.csv\")\nhead(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 801\n   mar1  mar2  mar3  mar4  mar5  mar6  mar7  mar8  mar9 mar11 mar12 abany\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1     5     0     0     0     0     0     0     0     0     0     0     0\n2     5     0     0     0     0     0     0     0     0     0     0     0\n3     4     0     0     0     0     0     0     0     0     0     0     2\n4     2     0     0     0     0     0     0     0     0     0     0     0\n5     1     1     0     0     0     0     0     0     0     0     0     9\n6     5     0     0     0     0     0     0     0     0     0     0     0\n# ℹ 789 more variables: abdefect <dbl>, abhlth <dbl>, abnomore <dbl>,\n#   abpoor <dbl>, abrape <dbl>, absingle <dbl>, acqntsex <dbl>, adults <dbl>,\n#   advfront <dbl>, affrmact <dbl>, age <dbl>, aged <dbl>, agekdbrn <dbl>,\n#   astrolgy <dbl>, astrosci <dbl>, attend <dbl>, away1 <dbl>, away11 <dbl>,\n#   away2 <dbl>, away3 <dbl>, away4 <dbl>, away5 <dbl>, away6 <dbl>,\n#   away7 <dbl>, babies <dbl>, backpain <dbl>, balneg <dbl>, balpos <dbl>,\n#   betrlang <dbl>, bible <dbl>, bigbang <dbl>, bizbstgw <dbl>, …\n```\n\n\n:::\n:::\n\n\nThe following code uses the `naniar` package to clean the data by replacing survey-coded missing values with `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ndata_pos <- data %>%\n  dplyr::select(wwwhr, wordsum, age, sex, reliten, polviews, wrkhome) %>%\n  replace_with_na(.,\n    replace = list(\n      wwwhr = c(-1, 998, 999),\n      wordsum = c(-1, 99),\n      reliten = c(0, 8, 9),\n      polviews = c(0, 8, 9),\n      wrkhome = c(0, 8, 9),\n      age = c(0, 98, 99)\n    ))\n```\n:::\n\n\n### Exercise 1.1 {.unnumbered}\n\nExplain what the `replace_with_na` code is doing. Why are values like -1, 998, and 999 being replaced? What would happen to your model if you left these values in the data?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: GSS coding conventions\"}\nIn many large-scale surveys, numeric codes like -1, 98/99, 998/999 don't represent real values. They're placeholders for \"inapplicable,\" \"don't know,\" or \"no answer.\" Check the GSS codebook if you want to see what each code means for each variable.\n:::\n\nThe values like -1, 998, and 999 are meaningful responses, so we're replacing them with NA. If you don't do this, the extreme numeric values will influence your statistics and predictions.\n\n### Exercise 1.2 {.unnumbered}\n\nRecode `sex` and `reliten` as factors with meaningful labels. Should `reliten` be treated as ordered or nominal? Justify your choice.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Recoding\"}\n`sex` is coded 1 = Male, 2 = Female in the GSS. For `reliten`, check the unique values after cleaning. You'll need to decide whether to treat it as an ordered factor or collapse categories. Use `mutate()` with `factor()` or `case_when()`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos <- data_pos %>%\n  mutate(\n    sex = factor(sex,\n                 levels = c(1, -1), # -1 not 2\n                 labels = c(\"Male\", \"Female\")))\n\ndata_pos <- data_pos %>%\n  mutate(\n    reliten_3f = case_when(\n      reliten == 1 ~ \"Strong\",\n      reliten == 2 ~ \"Moderate\",\n      reliten == 3 ~ \"Moderate\",\n      reliten == 4 ~ \"No religion\"\n    ),\n    reliten_3f = factor(reliten_3f,\n                        levels = c(\"Strong\", \"Moderate\", \"No religion\"),\n                        ordered = TRUE)\n  )\n\nunique(data_pos$reliten)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  1  4  3  2 NA\n```\n\n\n:::\n\n```{.r .cell-code}\nunique(data_pos$reliten_3f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Strong      No religion Moderate    <NA>       \nLevels: Strong < Moderate < No religion\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(data_pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  wwwhr wordsum   age sex    reliten polviews wrkhome reliten_3f \n  <dbl>   <dbl> <dbl> <fct>    <dbl>    <dbl>   <dbl> <ord>      \n1     3       6    31 Male         1        3       3 Strong     \n2    20       9    23 Female       4        2       4 No religion\n3    NA      NA    71 Female       1       NA      NA Strong     \n4    NA       3    82 Female       1        2      NA Strong     \n5    NA      NA    78 Female       1        3      NA Strong     \n6    NA      NA    40 Male         4        3      NA No religion\n```\n\n\n:::\n:::\n\n\n'reliten' seems like an ordinal variable, but the order and distance betweeen factors are unclear. I collapsed the two middle categories (i.e., not very strong, somewhat strong) to treat it as an ordinal variable.\n\n## Missingness\n\n### Exercise 1.3 {.unnumbered}\n\nInspect the cleaned data for missing values. How many complete cases do you have across all analysis variables? -\\> 603 cases.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nskimr::skim(data_pos)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |data_pos |\n|Number of rows           |2044     |\n|Number of columns        |8        |\n|_______________________  |         |\n|Column type frequency:   |         |\n|factor                   |2        |\n|numeric                  |6        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                   |\n|:-------------|---------:|-------------:|:-------|--------:|:----------------------------|\n|sex           |         0|          1.00|FALSE   |        2|Fem: 1153, Mal: 891          |\n|reliten_3f    |        99|          0.95|TRUE    |        3|Mod: 875, Str: 707, No : 363 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0| p25| p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|---:|---:|---:|----:|:-----|\n|wwwhr         |       996|          0.51|  9.79| 13.41|  0|   2|   5|  14|  168|▇▁▁▁▁ |\n|wordsum       |       657|          0.68|  6.03|  2.07|  0|   5|   6|   7|   10|▁▃▇▅▂ |\n|age           |         3|          1.00| 47.97| 17.68| 18|  33|  47|  61|   89|▇▇▇▅▃ |\n|reliten       |        99|          0.95|  2.08|  1.08|  1|   1|   2|   3|    4|▇▇▁▂▃ |\n|polviews      |        71|          0.97|  4.08|  1.46|  1|   3|   4|   5|    7|▃▂▇▃▅ |\n|wrkhome       |       882|          0.57|  2.26|  1.72|  1|   1|   1|   4|    6|▇▁▁▂▁ |\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nsum(complete.cases(data_pos))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 603\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ndata_pos <- data_pos[complete.cases(data_pos), ]\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 2: Fitting a Poisson Model\n\n## Mini-tutorial: Fitting and reading a Poisson model\n\nBefore you fit your model on the GSS data, here is a worked example on a toy dataset so you can see the full workflow.\n\n**Toy data:**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntoy <- tibble(\n  visits = c(0, 1, 3, 2, 0, 5, 1, 4, 7, 2),\n  age = c(22, 25, 35, 30, 20, 55, 28, 45, 60, 33)\n)\n```\n:::\n\n\n**Fit the model:**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ntoy_model <- glm(visits ~ age, data = toy, family = poisson(link = \"log\"))\n```\n:::\n\n\n**Read the output on the log scale.** These coefficients are on the log-count scale. The intercept is the log of the expected count when age = 0. The slope is the change in log-count for a one-year increase in age.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel_parameters(toy_model) %>% print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xtcianvofz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xtcianvofz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xtcianvofz thead, #xtcianvofz tbody, #xtcianvofz tfoot, #xtcianvofz tr, #xtcianvofz td, #xtcianvofz th {\n  border-style: none;\n}\n\n#xtcianvofz p {\n  margin: 0;\n  padding: 0;\n}\n\n#xtcianvofz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xtcianvofz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xtcianvofz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xtcianvofz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xtcianvofz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xtcianvofz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xtcianvofz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xtcianvofz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xtcianvofz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xtcianvofz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xtcianvofz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xtcianvofz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xtcianvofz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xtcianvofz .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xtcianvofz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtcianvofz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xtcianvofz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xtcianvofz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xtcianvofz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtcianvofz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xtcianvofz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtcianvofz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xtcianvofz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtcianvofz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xtcianvofz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xtcianvofz .gt_left {\n  text-align: left;\n}\n\n#xtcianvofz .gt_center {\n  text-align: center;\n}\n\n#xtcianvofz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xtcianvofz .gt_font_normal {\n  font-weight: normal;\n}\n\n#xtcianvofz .gt_font_bold {\n  font-weight: bold;\n}\n\n#xtcianvofz .gt_font_italic {\n  font-style: italic;\n}\n\n#xtcianvofz .gt_super {\n  font-size: 65%;\n}\n\n#xtcianvofz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xtcianvofz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xtcianvofz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xtcianvofz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xtcianvofz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xtcianvofz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xtcianvofz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xtcianvofz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xtcianvofz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-1.43</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.71</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-2.95, -0.14)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-2.01</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.044 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.01</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.03, 0.09)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">3.91</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Exponentiate to get IRRs.** Now the intercept is the expected count when age = 0, and the slope is the incidence rate ratio — the multiplicative change in the expected count per one-year increase in age.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nmodel_parameters(toy_model, exponentiate = TRUE) %>% print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"epulydwvkx\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#epulydwvkx table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#epulydwvkx thead, #epulydwvkx tbody, #epulydwvkx tfoot, #epulydwvkx tr, #epulydwvkx td, #epulydwvkx th {\n  border-style: none;\n}\n\n#epulydwvkx p {\n  margin: 0;\n  padding: 0;\n}\n\n#epulydwvkx .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#epulydwvkx .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#epulydwvkx .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#epulydwvkx .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#epulydwvkx .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#epulydwvkx .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#epulydwvkx .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#epulydwvkx .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#epulydwvkx .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#epulydwvkx .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#epulydwvkx .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#epulydwvkx .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#epulydwvkx .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#epulydwvkx .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#epulydwvkx .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epulydwvkx .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#epulydwvkx .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#epulydwvkx .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#epulydwvkx .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epulydwvkx .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#epulydwvkx .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epulydwvkx .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#epulydwvkx .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epulydwvkx .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#epulydwvkx .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#epulydwvkx .gt_left {\n  text-align: left;\n}\n\n#epulydwvkx .gt_center {\n  text-align: center;\n}\n\n#epulydwvkx .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#epulydwvkx .gt_font_normal {\n  font-weight: normal;\n}\n\n#epulydwvkx .gt_font_bold {\n  font-weight: bold;\n}\n\n#epulydwvkx .gt_font_italic {\n  font-style: italic;\n}\n\n#epulydwvkx .gt_super {\n  font-size: 65%;\n}\n\n#epulydwvkx .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#epulydwvkx .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#epulydwvkx .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#epulydwvkx .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#epulydwvkx .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#epulydwvkx .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#epulydwvkx .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#epulydwvkx .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#epulydwvkx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.17</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.05, 0.87)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-2.01</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.044 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">1.06</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.03, 1.09)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">3.91</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n**Get a predicted count.** This is the model's predicted number of visits for a 40-year-old, back on the count scale.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\npredict(toy_model, newdata = tibble(age = 40), type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n2.394034 \n```\n\n\n:::\n:::\n\n\nNow apply this workflow to the GSS data.\n\n### Exercise 2.1 {.unnumbered}\n\nFit a Poisson regression model predicting `wwwhr` from the predictors listed in the pre-registration. Display the results in a formatted table.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: glm() syntax\"}\nThe key argument is `family = poisson(link = \"log\")`. Use `model_parameters() %>% print_html()` or `tidy() %>% kable()` for a clean table.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwwwhr_model <- glm(wwwhr ~ wordsum + age + sex + reliten_3f + polviews + wrkhome, \n                   data = data_pos, \n                   family = poisson(link = \"log\"))\nmodel_parameters(wwwhr_model) %>% print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ighaeaettv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ighaeaettv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ighaeaettv thead, #ighaeaettv tbody, #ighaeaettv tfoot, #ighaeaettv tr, #ighaeaettv td, #ighaeaettv th {\n  border-style: none;\n}\n\n#ighaeaettv p {\n  margin: 0;\n  padding: 0;\n}\n\n#ighaeaettv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ighaeaettv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ighaeaettv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ighaeaettv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ighaeaettv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ighaeaettv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ighaeaettv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ighaeaettv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ighaeaettv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ighaeaettv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ighaeaettv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ighaeaettv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ighaeaettv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ighaeaettv .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ighaeaettv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ighaeaettv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ighaeaettv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ighaeaettv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ighaeaettv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ighaeaettv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ighaeaettv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ighaeaettv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ighaeaettv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ighaeaettv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ighaeaettv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ighaeaettv .gt_left {\n  text-align: left;\n}\n\n#ighaeaettv .gt_center {\n  text-align: center;\n}\n\n#ighaeaettv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ighaeaettv .gt_font_normal {\n  font-weight: normal;\n}\n\n#ighaeaettv .gt_font_bold {\n  font-weight: bold;\n}\n\n#ighaeaettv .gt_font_italic {\n  font-style: italic;\n}\n\n#ighaeaettv .gt_super {\n  font-size: 65%;\n}\n\n#ighaeaettv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ighaeaettv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ighaeaettv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ighaeaettv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ighaeaettv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ighaeaettv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ighaeaettv .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ighaeaettv .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ighaeaettv div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">2.34</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(2.20, 2.48)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">32.18</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wordsum</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">7.80e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.09, 0.12)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">13.08</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">1.08e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.02, -0.01)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-15.37</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">sex (Female)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.25</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.30, -0.20)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-9.36</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (linear)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.47</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.41, 0.52)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">16.80</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (quadratic)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.06, 0.03)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-0.80</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.423 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.03</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">9.76e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.05, -0.01)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-3.30</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.08</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">7.66e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.06, 0.09)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">10.29</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\nmodel_parameters(wwwhr_model, exponentiate = TRUE) %>% print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ludbitoofb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ludbitoofb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ludbitoofb thead, #ludbitoofb tbody, #ludbitoofb tfoot, #ludbitoofb tr, #ludbitoofb td, #ludbitoofb th {\n  border-style: none;\n}\n\n#ludbitoofb p {\n  margin: 0;\n  padding: 0;\n}\n\n#ludbitoofb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ludbitoofb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ludbitoofb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ludbitoofb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ludbitoofb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ludbitoofb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ludbitoofb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ludbitoofb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ludbitoofb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ludbitoofb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ludbitoofb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ludbitoofb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ludbitoofb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ludbitoofb .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ludbitoofb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ludbitoofb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ludbitoofb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ludbitoofb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ludbitoofb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ludbitoofb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ludbitoofb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ludbitoofb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ludbitoofb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ludbitoofb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ludbitoofb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ludbitoofb .gt_left {\n  text-align: left;\n}\n\n#ludbitoofb .gt_center {\n  text-align: center;\n}\n\n#ludbitoofb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ludbitoofb .gt_font_normal {\n  font-weight: normal;\n}\n\n#ludbitoofb .gt_font_bold {\n  font-weight: bold;\n}\n\n#ludbitoofb .gt_font_italic {\n  font-style: italic;\n}\n\n#ludbitoofb .gt_super {\n  font-size: 65%;\n}\n\n#ludbitoofb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ludbitoofb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ludbitoofb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ludbitoofb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ludbitoofb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ludbitoofb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ludbitoofb .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ludbitoofb .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ludbitoofb div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">10.38</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.75</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(9.00, 11.96)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">32.18</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wordsum</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">1.11</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">8.64e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.09, 1.12)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">13.08</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">1.07e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.98, 0.99)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-15.37</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">sex (Female)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.78</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.74, 0.82)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-9.36</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (linear)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">1.59</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.51, 1.68)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">16.80</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (quadratic)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.98</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.02</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.94, 1.03)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-0.80</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.423 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.97</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">9.45e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.95, 0.99)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-3.30</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">1.08</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">8.29e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.07, 1.10)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">10.29</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Exercise 2.2 {.unnumbered}\n\nPick one observation from your data. Using the coefficients from your fitted model, manually compute the predicted count for that observation. Show your work, then confirm it matches the output of `predict(model, type = \"response\")` for that row.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: From log-counts to counts\"}\nThe model estimates log(λ). So the predicted log-count for observation *i* is β₀ + β₁x₁ + β₂x₂ + ... Exponentiate to get the predicted count: λ = exp(β₀ + β₁x₁ + ...). Use `coef(model)` to extract the coefficients.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# row <- data_pos[300, ]\n# data_pos[300, 'sex']\n# data_pos[300, 'reliten_3f']\n# model.matrix(wwwhr_model)[300, 'reliten_3f.L']\n# \n# coef(wwwhr_model)\n# beta0 <- 2.33971674\n# beta_wordsum <- 0.10202749\n# beta_age <- -0.01667169\n# beta_sexF <- -0.24748598\n# beta_reliten3fL <- 0.46681384\n# beta_reliten3fQ <- -0.01783327\n# beta_polviews <- -0.03220420\n# beta_wrkhome <- 0.07881938\n# \n# logcount <- beta0 + beta_wordsum*row$wordsum + beta_age*row$age +\n#   beta_sexF*0 + beta_reliten3fL*model.matrix(wwwhr_model)[300, 'reliten_3f.L'] + \n#   beta_reliten3fQ*model.matrix(wwwhr_model)[300, 'reliten_3f.Q'] + \n#   beta_polviews*row$polviews + beta_wrkhome*row$wrkhome\n\nlogcount <- sum(coef(wwwhr_model) * model.matrix(wwwhr_model)[300, ])\nexp(logcount)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.174197\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(wwwhr_model, type = \"response\")[300]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     300 \n8.174197 \n```\n\n\n:::\n:::\n\n\nIt didn't match when I literally hand calculated the log count.. but the simpler way worked.\n\n------------------------------------------------------------------------\n\n# Part 3: Model Diagnostics\n\n### Exercise 3.1 {.unnumbered}\n\nUse the `performance` package to check your model. For each diagnostic panel, state what it's testing and whether your model passes or fails.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Which function?\"}\n`performance::check_model()` produces a panel of diagnostic plots. You can select specific checks with the `check` argument — e.g., `check = c(\"pp_check\", \"outliers\", \"overdispersion\")`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_model(wwwhr_model)\n```\n\n::: {.cell-output-display}\n![](Lab_Poisson_Regression_Q_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n1.  Posterior predictive check - checks whether the model produces the actual distribution of the observed data. The green dots are widely spread outside of the blue distribution. It fails..\n2.  Misspecified dispersion and zero inflation - checks whether the mean is similar enough with the variance. The observed variance is much larger than expected. It fails..\n3.  Homogeneity of variance - checks whether residual variance is constant across fitted values. There's a overall upward trend. It fails..\n4.  Influential observations - checks if any of the observations in the data was too influential and biased the model. Few dots are outside the lines so Pass?\n5.  Collinearity - checks whether the predictors were highly correlated. VIF values are under 2. Pass!\n6.  Distribution of quantile residuals - checks whether residuals follow the expected distribution. It deviates a lot from the reference line. It fails..\n\n### Exercise 3.2 {.unnumbered}\n\nIdentify outliers. How many observations are flagged, and what makes them outlying: high residuals, high leverage, or both?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Outlier detection\"}\n`performance::check_outliers()` returns a logical vector you can use to filter your data. Try `which()` or `sum()` to count the flagged cases.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers <- performance::check_outliers(wwwhr_model)\nwhich(outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  72 156 363\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(outliers)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\noutliers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 outliers detected: cases 72, 156, 363.\n- Based on the following method and threshold: cook (0.9).\n- For variable: (Whole model).\n```\n\n\n:::\n:::\n\n\nThree outliers are detected. High Cook's distances indicate both high residuals and high leverage.\n\n### Exercise 3.3 {.unnumbered}\n\nRefit the model without the outliers. Compare the two coefficient tables: which estimates changed substantively, and does the overall story change?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Filtering\"}\nStore the outlier check as an object, then use it to index your data: `data_clean <- data_pos[!outlier_flag, ]`. Refit the same `glm()` call on the filtered data and compare with `model_parameters()`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutliers_flag <- as.logical(outliers)\ndata_clean <- data_pos[!outliers_flag, ]\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwwwhr_clean <- glm(wwwhr ~ wordsum + age + sex + reliten_3f + polviews + wrkhome, \n                   data = data_clean, \n                   family = poisson(link = \"log\"))\n\nmodel_parameters(wwwhr_clean) %>% print_html()\n```\n:::\n\n\nPolviews coefficient is not significant anymore. Also the effect of sex and wrkhome decreased a lot. Now it seems that several predictors were weaker than expected before, and political views are not related with internet usage.\n\n------------------------------------------------------------------------\n\n# Part 4: Overdispersion & Alternative Models\n\n### Exercise 4.1 {.unnumbered}\n\nCheck for overdispersion and report the dispersion ratio. What specific property of the Poisson distribution is violated when the ratio is much greater than 1?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Checking overdispersion\"}\n`performance::check_overdispersion()` returns a dispersion ratio and a p-value. A ratio near 1 means the Poisson assumption holds.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwwwhr_clean <- glm(wwwhr ~ wordsum + age + sex + reliten_3f + polviews + wrkhome, \n                   data = data_clean, \n                   family = poisson(link = \"log\"))\n\nperformance::check_overdispersion(wwwhr_clean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio =   12.119\n  Pearson's Chi-Squared = 7174.518\n                p-value =  < 0.001\n```\n\n\n:::\n:::\n\n\nOh no, dispersion ratio is 12.119. It violates the assumption that the variance of the outcome equals the mean.\n\n### Exercise 4.2 {.unnumbered}\n\nGiven the overdispersion you found, name a model family that can handle it and explain in 1–2 sentences why it works. Then fit that model to the data and display the results.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: An extra parameter\"}\nThe Poisson model has no separate parameter for variance. What if you had a model that added one? Check the `MASS` package.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwwwhr_nb <- glm.nb(wwwhr ~ wordsum + age + sex + reliten_3f + polviews + wrkhome, data = data_clean)\nmodel_parameters(wwwhr_nb) %>% print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"piszxfatsk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#piszxfatsk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#piszxfatsk thead, #piszxfatsk tbody, #piszxfatsk tfoot, #piszxfatsk tr, #piszxfatsk td, #piszxfatsk th {\n  border-style: none;\n}\n\n#piszxfatsk p {\n  margin: 0;\n  padding: 0;\n}\n\n#piszxfatsk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#piszxfatsk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#piszxfatsk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#piszxfatsk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#piszxfatsk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#piszxfatsk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#piszxfatsk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#piszxfatsk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#piszxfatsk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#piszxfatsk .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#piszxfatsk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#piszxfatsk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#piszxfatsk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#piszxfatsk .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#piszxfatsk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#piszxfatsk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#piszxfatsk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#piszxfatsk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#piszxfatsk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#piszxfatsk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#piszxfatsk .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#piszxfatsk .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#piszxfatsk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#piszxfatsk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#piszxfatsk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#piszxfatsk .gt_left {\n  text-align: left;\n}\n\n#piszxfatsk .gt_center {\n  text-align: center;\n}\n\n#piszxfatsk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#piszxfatsk .gt_font_normal {\n  font-weight: normal;\n}\n\n#piszxfatsk .gt_font_bold {\n  font-weight: bold;\n}\n\n#piszxfatsk .gt_font_italic {\n  font-style: italic;\n}\n\n#piszxfatsk .gt_super {\n  font-size: 65%;\n}\n\n#piszxfatsk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#piszxfatsk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#piszxfatsk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#piszxfatsk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#piszxfatsk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#piszxfatsk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#piszxfatsk .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#piszxfatsk .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#piszxfatsk div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">2.22</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.74, 2.70)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">9.28</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wordsum</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.05, 0.15)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">3.86</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.01</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">3.47e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.02, -7.18e-03)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-4.09</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">sex (Female)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.14</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.09</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.31, 0.04)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-1.54</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.123 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (linear)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.42</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.09</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.25, 0.60)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">4.74</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten 3f (quadratic)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.16, 0.12)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-0.24</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.809 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.08, 0.05)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-0.47</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.640 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.02, 0.08)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">1.06</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.290 </td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe need a negative binomial model. It adds an additional parameter that allows the variance to exceed the mean.\n\n------------------------------------------------------------------------\n\n# Part 5: Model Comparison\n\n### Exercise 5.1 {.unnumbered}\n\nCompare your Poisson and negative binomial models using a likelihood ratio test and a comparison table. Interpret the test result and the AIC/BIC values. What do they tell you about relative model fit?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Two ways to compare\"}\n`performance::test_likelihoodratio()` gives you a formal test. For a publication-style table, use `modelsummary(list(\"Poisson\" = m1, \"Neg. Binomial\" = m2), exponentiate = TRUE, stars = TRUE)`. AIC/BIC are reported automatically.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::test_likelihoodratio(wwwhr_clean, wwwhr_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName        |  Model | df | df_diff |    Chi2 |      p\n------------------------------------------------------\nwwwhr_clean |    glm |  8 |         |         |       \nwwwhr_nb    | negbin |  9 |       1 | 3850.62 | < .001\n```\n\n\n:::\n\n```{.r .cell-code}\nmodelsummary(list(\"Poisson\" = wwwhr_clean, \"Neg. Binomial\" = wwwhr_nb), exponentiate = TRUE, stars = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_y3c79ezfr9xsubvg593a = TinyTable.createTableFunctions(\"tinytable_y3c79ezfr9xsubvg593a\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '22', j: 2 }, { i: '22', j: 3 } ], css_id: 'tinytable_css_dgjddxz9kfqctischbxy',}, \n          { positions: [ { i: '16', j: 2 }, { i: '16', j: 3 } ], css_id: 'tinytable_css_rg4rxjhy8z5qua21bz1w',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '17', j: 3 }, { i: '18', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '21', j: 3 } ], css_id: 'tinytable_css_1g1vhtyya9wk1luk6kmx',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_4b12bp9bokwkz2wwxz24',}, \n          { positions: [ { i: '22', j: 1 } ], css_id: 'tinytable_css_3q6u26r23sbpsldic5sy',}, \n          { positions: [ { i: '16', j: 1 } ], css_id: 'tinytable_css_5b54aoux8f75cu46xlib',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 } ], css_id: 'tinytable_css_wc0zxv0909pqgxcu2r6t',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_x4vg0kjumf5e23xxd7bp',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_y3c79ezfr9xsubvg593a.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_dgjddxz9kfqctischbxy, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_dgjddxz9kfqctischbxy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_rg4rxjhy8z5qua21bz1w, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_rg4rxjhy8z5qua21bz1w {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_1g1vhtyya9wk1luk6kmx, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_1g1vhtyya9wk1luk6kmx { text-align: center }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_4b12bp9bokwkz2wwxz24, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_4b12bp9bokwkz2wwxz24 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_3q6u26r23sbpsldic5sy, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_3q6u26r23sbpsldic5sy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_5b54aoux8f75cu46xlib, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_5b54aoux8f75cu46xlib {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_wc0zxv0909pqgxcu2r6t, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_wc0zxv0909pqgxcu2r6t { text-align: left }\n    #tinytable_y3c79ezfr9xsubvg593a td.tinytable_css_x4vg0kjumf5e23xxd7bp, #tinytable_y3c79ezfr9xsubvg593a th.tinytable_css_x4vg0kjumf5e23xxd7bp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_y3c79ezfr9xsubvg593a\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Poisson</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Neg. Binomial</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='3'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">8.750***</td>\n                  <td data-row=\"1\" data-col=\"3\">9.171***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.659)</td>\n                  <td data-row=\"2\" data-col=\"3\">(2.191)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">wordsum</td>\n                  <td data-row=\"3\" data-col=\"2\">1.099***</td>\n                  <td data-row=\"3\" data-col=\"3\">1.104***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.009)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.028)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">age</td>\n                  <td data-row=\"5\" data-col=\"2\">0.987***</td>\n                  <td data-row=\"5\" data-col=\"3\">0.986***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.001)</td>\n                  <td data-row=\"6\" data-col=\"3\">(0.003)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">sexFemale</td>\n                  <td data-row=\"7\" data-col=\"2\">0.831***</td>\n                  <td data-row=\"7\" data-col=\"3\">0.873</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.023)</td>\n                  <td data-row=\"8\" data-col=\"3\">(0.077)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">reliten_3f.L</td>\n                  <td data-row=\"9\" data-col=\"2\">1.540***</td>\n                  <td data-row=\"9\" data-col=\"3\">1.528***</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.044)</td>\n                  <td data-row=\"10\" data-col=\"3\">(0.137)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">reliten_3f.Q</td>\n                  <td data-row=\"11\" data-col=\"2\">0.967</td>\n                  <td data-row=\"11\" data-col=\"3\">0.983</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.022)</td>\n                  <td data-row=\"12\" data-col=\"3\">(0.070)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">polviews</td>\n                  <td data-row=\"13\" data-col=\"2\">0.997</td>\n                  <td data-row=\"13\" data-col=\"3\">0.985</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.010)</td>\n                  <td data-row=\"14\" data-col=\"3\">(0.032)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">wrkhome</td>\n                  <td data-row=\"15\" data-col=\"2\">1.032***</td>\n                  <td data-row=\"15\" data-col=\"3\">1.029</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.008)</td>\n                  <td data-row=\"16\" data-col=\"3\">(0.028)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"17\" data-col=\"2\">600</td>\n                  <td data-row=\"17\" data-col=\"3\">600</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\">AIC</td>\n                  <td data-row=\"18\" data-col=\"2\">7734.0</td>\n                  <td data-row=\"18\" data-col=\"3\">3885.4</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">BIC</td>\n                  <td data-row=\"19\" data-col=\"2\">7769.2</td>\n                  <td data-row=\"19\" data-col=\"3\">3924.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"20\" data-col=\"2\">-3858.996</td>\n                  <td data-row=\"20\" data-col=\"3\">-1933.686</td>\n                </tr>\n                <tr>\n                  <td data-row=\"21\" data-col=\"1\">F</td>\n                  <td data-row=\"21\" data-col=\"2\">104.227</td>\n                  <td data-row=\"21\" data-col=\"3\">10.559</td>\n                </tr>\n                <tr>\n                  <td data-row=\"22\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"22\" data-col=\"2\">10.85</td>\n                  <td data-row=\"22\" data-col=\"3\">10.87</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nThe likelihood ratio test result shows that negative binomial model worked significantly better than the original poisson model. AIC and BIC values are also substantially lower for the negative binomial model, which indicates a better fit.\n\n------------------------------------------------------------------------\n\n# Part 6: Zero Inflation\n\n### Exercise 6.1 {.unnumbered}\n\nTest for zero inflation in your chosen model and interpret the result. In your answer, define zero inflation and distinguish between the two types of zeros, giving a concrete example of each using the `wwwhr` variable.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Why zero?\"}\n`performance::check_zeroinflation()` compares observed vs. predicted zero counts. Think about why someone might report 0 hours of internet use — there could be more than one reason.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_zeroinflation(wwwhr_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for zero-inflation\n\n   Observed zeros: 40\n  Predicted zeros: 65\n            Ratio: 1.61\n```\n\n\n:::\n:::\n\n\nZero inflation happens when the data has too many zero values, more than what the model predicts. This can bias the model's prediction.\n\nZero values can have broadly two reasons. 1) Some people genuinely don't use the internet at all, or less than 1 hour. 2) In other cases, zero values don't have meaningful interpretations about the respondents' behavior. For example, some people might not have access to the internet as they're in extremely rural areas. Zero values can be misleading in this case.\n\n## Mini-tutorial: Fitting a zero-inflated model\n\nThe `zeroinfl()` function from the `pscl` package fits a two-part model. The left side of `|` is the count model (Poisson or negative binomial). The right side models the probability of a structural zero using logistic regression.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Extending the doctor visits example from Part 2\n# Some people avoid doctors entirely (structural zeros)\n# Others see doctors but had 0 visits that month (sampling zeros)\n# Adding a binary predictor: whether the person has insurance\n\ntoy_zi_data <- tibble(\n  visits   = c(0, 0, 0, 0, 1, 3, 0, 2, 0, 7, 0, 0, 4, 1, 0),\n  age      = c(22, 25, 35, 19, 40, 55, 28, 45, 23, 60, 20, 30, 50, 33, 27),\n  insured  = c(0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0)\n)\n\n# Count model: visits ~ age (how many visits, given you go at all)\n# Zero model:  ~ insured (does having insurance affect whether you go at all?)\ntoy_zi_model <- zeroinfl(visits ~ age | insured, dist = \"negbin\", data = toy_zi_data)\n\nsummary(toy_zi_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nzeroinfl(formula = visits ~ age | insured, data = toy_zi_data, dist = \"negbin\")\n\nPearson residuals:\n       Min         1Q     Median         3Q        Max \n-0.8469321 -0.0003343 -0.0002728  0.0493294  0.7525305 \n\nCount model coefficients (negbin with log link):\n             Estimate Std. Error z value Pr(>|z|)   \n(Intercept)  -3.46939    1.57370  -2.205  0.02748 * \nage           0.08963    0.02954   3.035  0.00241 **\nLog(theta)   14.44723  407.91453   0.035  0.97175   \n\nZero-inflation model coefficients (binomial with logit link):\n            Estimate Std. Error z value Pr(>|z|)\n(Intercept)    14.79    1155.04   0.013    0.990\ninsured       -28.14    1209.03  -0.023    0.981\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n\nTheta = 1880844.8294 \nNumber of iterations in BFGS optimization: 37 \nLog-likelihood: -9.666 on 5 Df\n```\n\n\n:::\n:::\n\n\nThe output has two sections. \"Count model coefficients\" are interpreted like a regular negative binomial (log-counts, exponentiate for IRRs). \"Zero-inflation model coefficients\" are interpreted like logistic regression (log odds of being a structural zero). In this example, uninsured people may be more likely to avoid doctors entirely, which is a different process from how often insured people visit.\n\n### Exercise 6.2 {.unnumbered}\n\nBased on your zero-inflation test, should you fit a zero-inflated model? If yes, fit one and compare it to your negative binomial. If no, explain why the negative binomial is sufficient.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Zero-inflated syntax\"}\nThe mini-tutorial above shows the syntax pattern. The left side of `|` is your count model formula, the right side models structural zeros. Use `dist = \"negbin\"` if your count model is negative binomial.\n:::\n\n\n::: {.cell}\n\n:::\n\n\nNo! My model actually predicts more zeros than observed. Zero inflation isn't happening.\n\n------------------------------------------------------------------------\n\n# Part 7: Visualization\n\n### Exercise 7.1 {.unnumbered}\n\nVisualize your final model's predictions on both the log-lambda and mean-count scales. For each plot, explain in 1–2 sentences what the scale shows and when you would report one vs. the other.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Two scales\"}\n`ggemmeans()` or `ggpredict()` from the `ggeffects` package. Counts are back-transformed by default. Show both in the panel-tabset.\n:::\n\n::: panel-tabset\n## Log Lambda\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlogplot <- ggpredict(wwwhr_nb, terms = c(\"wordsum\", \"age\", \"reliten_3f\"), back_transform = FALSE)\nlogplot <- ggpredict(wwwhr_nb, terms = c(\"wordsum\"), back_transform = FALSE)\n\nplot(logplot, log_y = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab_Poisson_Regression_Q_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThis plot shows predictions on linear predictor scale, and the relationship between predictors and the DV is additive. It's good for understanding how coefficients operate.\n\n## Mean Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncountplot <- ggpredict(wwwhr_nb, terms = c(\"wordsum\", \"age\", \"reliten_3f\"))\ncountplot <- ggpredict(wwwhr_nb, terms = c(\"wordsum\"))\nplot(countplot)\n```\n\n::: {.cell-output-display}\n![](Lab_Poisson_Regression_Q_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nThis plot shows predictions on the original outcome scale by exponentiating the linear predictor. It's more easily interpretable and good for reporting substantive results.\n:::\n\n------------------------------------------------------------------------\n\n# Part 8: Report Your Conclusions\n\n### Exercise 8.1 {.unnumbered}\n\nWrite a results paragraph following the reporting checklist from the lecture slides. Include a justification for why you used your final model over the Poisson.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Reporting checklist\"}\nFrom the lecture: state the hypothesis and model (with link function), report log-count coefficients and IRRs with 95% CIs, include a model fit measure (McFadden R²), mention overdispersion and zero-inflation test results, and note if you switched models and why.\n:::\n\nWe tested whether cognitive ability, demographics, and religious intensity predict internet use using count regression with a log link. Our initial Poisson model showed substantial overdispersion (dispersion ratio = 12.12, *p* \\< .001), so we fitted a negative binomial model. Compared to the Poisson model, model fit strongly favored the negative binomial specification (χ²(1) = 3850.62, *p* \\< .001; AIC = 3885.4). In the final model, higher vocabulary scores were associated with greater internet use (beta = 0.10, 95% CI \\[0.05, 0.15\\], *p* \\< .001), while age was negatively associated (beta = −0.01, 95% CI \\[-0.02, -0.0007\\], *p* \\< .001). Religiosity showed a strong positive linear effect (beta = 0.42, 95% CI \\[0.25, 0.60\\], *p* \\< .001). Political views and working from home were not significant.A zero-inflation test showed that the model overpredicted zeros (ratio = 1.61, p \\< .001). Overall, the negative binomial model provided the best fit and most reliable inference.\n",
    "supporting": [
      "Lab_Poisson_Regression_Q_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}