{
  "hash": "deafb1e277c2f1e5c1d114cfdb6563a9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayes Tutorial\"\nsubtitle: \"PSY 504: Advanced Statistics Final Project\"\nauthor: \"Yeaju Diana Kim\"\ndate: \"2026-05-06\"\ndate-modified: today\nformat:\n  html:\n    code-fold: false\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\n    toc-location: left\nexecute:\n  message: false\n  warning: false\nengine: knitr\n---\n\n# Intro\n\nIn this tutorial, I walk through a basic Bayesian linear regression model using the **brms** package in R. This tutorial assumes that readers are already familiar with ordinary least squares regression using `lm()` and have some basic familiarity with Bayesian modeling concepts, such as priors, likelihoods, and posterior distributions. The goal is to show how to fit, check, and interpret a Bayesian linear regression model in R using **brms**.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)  # data wrangling and plotting\nlibrary(ggside)     # extends ggplot with marginal histograms\nlibrary(brms)       # our main package for Bayesian regression modeling!\nlibrary(tidybayes)  # visualizing posterior uncertainty\n```\n:::\n\n\n# Data and Variables\n\nIn this tutorial, we will use **brms** to investigate whether neural alignment during conversation predicts perceived similarity after the conversation. The dataset includes dyads who were either friends or strangers.\n\nNeural alignment is measured using reconstruction (R\\^2) values, stored in the variable `r2_vox`. The outcome variable is the dyadic average of perceived similarity, stored as `mean_similarity_comp`.\n\n## Load data\n\nFirst, we load and wrangle the data. We standardize `r2_vox` using a z-score transformation so that the regression coefficient can be interpreted as the expected change in perceived similarity for a 1-sd increase in neural alignment. We then create `df`, the main dataframe for this tutorial, which contains the standardized predictor `r2_vox_z` and the outcome variable `mean_similarity_comp`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSRM_df <- read.csv(\"dyadsrm_metrics_glasser_generate.csv\") %>% \n  dplyr::select(dyad, group, r2_vox)\n\nbehav_df <- read.csv(\"behav_measures.csv\") %>%\n  dplyr::select(dyad, group, mean_similarity_comp)\n\ndf <- SRM_df %>%\n  inner_join(behav_df, by = c(\"dyad\", \"group\")) %>%\n  mutate(r2_vox_z = as.numeric(scale(r2_vox)))\n\nglimpse(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 48\nColumns: 5\n$ dyad                 <int> 104, 105, 107, 108, 109, 113, 114, 116, 117, 121,…\n$ group                <chr> \"stranger\", \"stranger\", \"stranger\", \"stranger\", \"…\n$ r2_vox               <dbl> 0.09122112, 0.08711615, 0.10054018, 0.10646721, 0…\n$ mean_similarity_comp <dbl> 3.833333, 5.000000, 4.666667, 4.833333, 5.166667,…\n$ r2_vox_z             <dbl> -1.7554784, -2.1265395, -0.9130995, -0.3773362, 1…\n```\n\n\n:::\n:::\n\n\nThere are 48 dyads in total, each belongs to either the 'stranger' or 'friend' group. For now, we will ignore group membership and fit a simple Bayesian linear regression model using only neural alignment as a predictor of perceived similarity. Later, we will return to the `group` variable and examine whether accounting for group status changes the results.\n\n## Exploratory Data Analysis (EDA)\n\nBefore fitting the Bayesian model, we first inspect the relationship between neural alignment and perceived similarity. The marginal histograms show the distribution of each variable separately. Perceived similarity scores range from approximately 3 to 7, while standardized neural alignment values range from about -2 to 2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  ggplot(aes(x = r2_vox_z, y = mean_similarity_comp)) +\n  geom_point() +\n  stat_smooth(method = \"lm\", formula = 'y ~ x', se = FALSE) +\n  geom_xsidehistogram(bins = 15) +\n  geom_ysidehistogram(bins = 15) +\n  scale_xsidey_continuous(breaks = NULL) +\n  scale_ysidex_continuous(breaks = NULL) +\n  theme(ggside.panel.scale = 0.25)\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nThe plot suggests a positive (but noisy) association between neural alignment and perceived similarity! Dyads with higher `r2_vox_z` tend to report higher similarity. We will quantify this association more formally using Bayesian linear regression below.\n\nNext, we compute basic descriptive statistics and check whether either variable contains missing values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf %>% \n  pivot_longer(cols = c(r2_vox_z, mean_similarity_comp)) %>% \n  group_by(name) %>% \n  summarise(mean = mean(value),\n            sd = sd(value),\n            n_missing = sum(is.na(value))) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  name                      mean    sd n_missing\n  <chr>                    <dbl> <dbl>     <int>\n1 mean_similarity_comp  5.01e+ 0  1.06         0\n2 r2_vox_z             -4.59e-18  1            0\n```\n\n\n:::\n:::\n\n\nThere are no missing values for either `r2_vox_z` or `mean_similarity_comp`. The mean perceived similarity score is approximately 5.01, with a standard deviation of about 1.06. The standardized neural alignment variable has a mean close to 0 and a standard deviation close to 1.\n\n## Warm up: Ordinary Least Squares (OLS) regression\n\nBefore diving into Bayesian modeling, let’s warm up with the familiar `lm()` function. This gives us a useful baseline and reminds us of the key variables. We are predicting perceived similarity, `mean_similarity_comp`, from standardized neural alignment, `r2_vox_z`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ols <- lm(data = df, mean_similarity_comp ~ r2_vox_z)\nsummary(fit_ols)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_similarity_comp ~ r2_vox_z, data = df)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.0953 -0.6419  0.1557  0.8597  1.5061 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   5.0069     0.1426  35.102   <2e-16 ***\nr2_vox_z      0.4102     0.1441   2.845   0.0066 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9882 on 46 degrees of freedom\nMultiple R-squared:  0.1497,\tAdjusted R-squared:  0.1312 \nF-statistic: 8.096 on 1 and 46 DF,  p-value: 0.006603\n```\n\n\n:::\n:::\n\n\nThe OLS model gives us our first hint that something is going on. `r2_vox_z` has a positive slope, and the association is statistically significant under the usual frequentist framework. Nice!\n\nWe can also visualize the fitted OLS regression line and its 95% confidence interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnd <- tibble(r2_vox_z = seq(from = min(df$r2_vox_z),\n                            to = max(df$r2_vox_z),\n                            length.out = 50))\n\npredict(fit_ols,\n        interval = \"confidence\",\n        newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = r2_vox_z)) +\n  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 1/3) +\n  geom_line(aes(y = fit)) +\n  geom_point(data = df,\n             aes(y = mean_similarity_comp))\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n# Bayesian Linear Regression\n\nNow we finally move on to Bayesian modeling. As noted earlier, we will use the **brms** package. The main function, `brm()`, works somewhat like `lm()` in that we still use familiar formula syntax: `mean_similarity_comp ~ r2_vox_z`. The difference is that Bayesian modeling also requires us to think about the likelihood, priors, MCMC settings, and posterior uncertainty. That may sound like a lot, but don't worry too much. For now, we'll start only with priors.\n\n## Default Priors\n\nIf you are not sure what priors to use, **brms** provides default priors. We can inspect them using `brms::get_prior()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(data = df, \n          mean_similarity_comp ~ r2_vox_z,\n          family = gaussian()\n          )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                prior     class     coef group resp dpar nlpar lb ub\n               (flat)         b                                     \n               (flat)         b r2_vox_z                            \n student_t(3, 5, 2.5) Intercept                                     \n student_t(3, 0, 2.5)     sigma                                 0   \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nThe output tells us which parameters need priors in this model. For this simple Bayesian linear regression, the main parameters are:\n\n-   the intercept\n-   the slope for `r2_vox_z`\n-   `sigma`, the residual standard deviation\n\nThe default prior for the slope of `r2_vox_z` is listed as `flat`. This means that `brms` is not putting much prior information on the slope by default. The intercept gets a Student-t prior centered around 5, which makes sense because the outcome variable `mean_similarity_comp` is centered near 5. The residual standard deviation, `sigma`, also gets a Student-t prior with a lower bound of 0, because standard deviations cannot be negative.\n\nThese defaults are usable, but for this tutorial we will specify our own weakly informative priors so that the assumptions of the model are more explicit.\n\n## Set Priors\n\nAs I just said, we can also set our own priors. For this model, I use weakly informative priors because I do not want to assume a strong relationship between neural alignment and perceived similarity before seeing the data.\n\nI set the intercept prior to be centered around 5. I use a skeptical prior centered at 0 for the slope. Finally, I use a lognormal prior for `sigma`, the residual standard deviation, because `sigma` must be positive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_priors <- c(\n  prior(normal(5, 1.5), class = \"Intercept\"),\n  prior(normal(0, 0.5), class = \"b\"),\n  prior(lognormal(0, 0.5), class = \"sigma\")\n)\n```\n:::\n\n\nBefore fitting the model to the actual outcome data, we first run a prior-only model. Setting `sample_prior = \"only\"` tells `brms` to simulate data from the priors without updating them with the observed outcome. This is useful for checking whether our priors imply plausible values of perceived similarity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_brm_prior <- brm(\n  data = df,\n  mean_similarity_comp ~ r2_vox_z,\n  family = gaussian(),\n  prior = my_priors,\n  iter = 2000, \n  chains = 4, \n  seed = 20,\n  sample_prior = \"only\"\n)\n```\n:::\n\n\nAfter fitting the prior-only model, we can check which priors were used:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprior_summary(fit_brm_prior)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             prior     class     coef group resp dpar nlpar lb ub       source\n    normal(0, 0.5)         b                                              user\n    normal(0, 0.5)         b r2_vox_z                             (vectorized)\n    normal(5, 1.5) Intercept                                              user\n lognormal(0, 0.5)     sigma                                 0            user\n```\n\n\n:::\n:::\n\n\nThe `prior_summary()` output confirms that the model is using the priors we specified.\n\n## Prior predictive check\n\nBefore fitting the model to the observed data, we run a prior predictive check. This shows what kinds of outcome values the model can generate using only the priors, before learning from the data.\n\nThis is not meant to perfectly match the observed data. Instead, we are checking whether the priors generate values that are at least plausible for `mean_similarity_comp`. Here we use `brms::pp_check()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_brm_prior, ndraws=50)\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nWell it doesn't look very good and the predictives are generally too broad, but it's at least not absurdly weird. Most simulated datasets generate similarity scores in or near the observed range, although some prior predictions extend beyond the 1–7 scale.\n\n## Fit Bayes model with priors\n\nNow that the priors are set, we can fit the main Bayesian regression model. This model uses the observed data to update the priors and produce posterior distributions for the intercept, slope, and residual standard deviation.\n\nHere, we set `sample_prior = TRUE`, which saves prior draws along with the posterior draws. This can be useful if we later want to compare prior and posterior distributions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_brm_1 <- brm(\n  data = df,\n  mean_similarity_comp ~ r2_vox_z,\n  family = gaussian(),\n  prior = my_priors,\n  iter = 2000, \n  chains = 4, \n  seed = 20,\n  sample_prior = TRUE\n)\n```\n:::\n\n\n## Markov Chain Monte Carlo (MCMC) diagnostics\n\nBefore interpreting the model results, we should check whether the MCMC sampler behaved well. The `brms::plot()` function gives us two useful diagnostics for each parameter: a posterior distribution plot on the left and a trace plot on the right.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(fit_brm_1, widths = 2:3)\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nFor the trace plots on the right side, we want the chains to look like fuzzy caterpillars. In other words, the chains should mix together without obvious trends or drifting over time. Here, the chains look well mixed for the intercept, slope, and `sigma`, which suggests that the sampler did not have obvious convergence problems.\n\n## Model results\n\nNow results! We can use `summary()` to inspect the posterior estimates for the model parameters. By default, `brms::summary()` reports 95% credible intervals, but we can request other intervals, such as 80%, 90%, or 99%, using the `prob` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_brm_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: mean_similarity_comp ~ r2_vox_z \n   Data: df (Number of observations: 48) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     5.01      0.14     4.72     5.29 1.00     3466     2961\nr2_vox_z      0.38      0.14     0.10     0.66 1.00     4158     3028\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     1.00      0.10     0.82     1.23 1.00     3737     3012\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n\n```{.r .cell-code}\n# Other examples:\n# summary(fit_brm_1, prob = .80)\n# summary(fit_brm_1, prob = .90)\n```\n:::\n\n\n-   The intercept is about 5.00. This means that when `r2_vox` is at its average value, the expected similarity score is approximately 5.00.\n\n-   The slope for `r2_vox_z` is about 0.38. This means that for every 1 standard deviation increase in `r2_vox`, mean perceived similarity is expected to increase by about 0.38 points.\n\n-   The 95% credible interval for the slope is \\[0.09, 0.65\\]. This interval does not include 0, suggesting a positive association between neural alignment and perceived similarity in this model.\n\n-   All Rhat values are 1.00, and the effective sample sizes are large. This suggests no obvious convergence problems.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- as_draws_df(fit_brm_1)\n\nmean(draws$b_r2_vox_z > 0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.995\n```\n\n\n:::\n:::\n\n\nThis gives the posterior probability that the slope is greater than zero. In this case, the result is 0.997, meaning that about 99.7% of the posterior draws for the slope are positive. This is a useful Bayesian summary of the direction of the association. Let me return to `as_draws_df()` in a few code chunks.\n\n## Posterior predictive check\n\nNext, we run a posterior predictive check. This is similar to the prior predictive check, but now the model has been fit to the observed data.\n\nThe basic question is:\n\n> If this model were true, would simulated data from the model look similar to the data we actually observed?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_brm_1, ndraws=50)\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe dark line shows the observed distribution of `mean_similarity_comp`, and the light blue lines show simulated datasets from the fitted model. The model does a reasonable job capturing the overall center and spread of the observed similarity scores, although the observed distribution is a bit flatter than many of the simulated distributions.\n\n## Compare with OLS\n\nWe can also compute a focused summary of the Bayesian regression coefficients using `brms::fixef()`. By default, `fixef()` reports posterior means. If we set `robust = TRUE`, it reports posterior medians instead.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfixef(fit_brm_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Estimate Est.Error       Q2.5     Q97.5\nIntercept 5.0054720 0.1447401 4.72147257 5.2894680\nr2_vox_z  0.3764805 0.1417793 0.09548644 0.6579378\n```\n\n\n:::\n\n```{.r .cell-code}\n# If we want to use median:\n# fixef(fit_brm_1, robust = TRUE)\n```\n:::\n\n\nThese estimates look familiar, right? The Bayesian model gives an intercept and slope that are very similar to the OLS estimates. This is expected here because we are fitting a simple Gaussian linear regression with weakly informative priors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbind(coef(fit_ols),  \n      sqrt(diag(vcov(fit_ols))),\n      confint(fit_ols)) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                    2.5 %    97.5 %\n(Intercept) 5.0069444 0.1426401 4.7198249 5.2940640\nr2_vox_z    0.4101539 0.1441495 0.1199959 0.7003118\n```\n\n\n:::\n:::\n\n\nThe OLS and Bayesian estimates are close, but the interpretation is different. In the OLS model, the interval is a frequentist confidence interval. In the Bayesian model, the interval is a posterior credible interval.\n\n# Visualization\n\n## Coefficients\n\nLet's get the main regression line plot with `conditional_effects()`. This plots the relationship between `r2_vox_z` and `mean_similarity_comp`, along with uncertainty around the fitted line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(fit_brm_1) %>% \n  plot(points = TRUE)\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nThe blue line shows the model’s estimated relationship between neural alignment and perceived similarity, and the gray ribbon shows the uncertainty around that fitted line. The points are the observed data.\n\n## Parameter distributions\n\nOne of the nice things about Bayesian modeling is that we can work directly with the full posterior distributions of the model parameters, not just point estimates. We can extract the posterior draws from a fitted model using `brms::as_draws_df()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- as_draws_df(fit_brm_1)\nglimpse(draws)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 4,000\nColumns: 12\n$ b_Intercept     <dbl> 4.954366, 5.028863, 5.014997, 4.966033, 5.084960, 4.89…\n$ b_r2_vox_z      <dbl> 0.2482303, 0.5310256, 0.3516985, 0.4252662, 0.3887591,…\n$ sigma           <dbl> 1.0226341, 0.9900557, 0.9929083, 0.9935381, 0.9709848,…\n$ Intercept       <dbl> 4.954366, 5.028863, 5.014997, 4.966033, 5.084960, 4.89…\n$ prior_Intercept <dbl> 6.211616, 6.534947, 2.697560, 6.062472, 7.417916, 4.24…\n$ prior_b         <dbl> -0.51645745, 0.57045691, -0.19605796, 0.36136789, 0.22…\n$ prior_sigma     <dbl> 0.7238576, 1.5800676, 0.7102229, 1.0496273, 1.1559378,…\n$ lprior          <dbl> -1.923069, -2.330354, -2.016404, -2.131547, -2.052147,…\n$ lp__            <dbl> -69.21556, -69.24740, -68.65819, -68.73736, -68.76834,…\n$ .chain          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …\n$ .iteration      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…\n$ .draw           <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…\n```\n\n\n:::\n:::\n\n\nNotice that this object contains thousands of posterior draws, along with some metadata such as chain number, iteration number, and draw number. The columns beginning with `b_` are the regression coefficients from the model.\n\nTo get a feel for the full posterior distributions of the regression coefficients, we can plot them directly:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_draws_df(fit_brm_1) %>% \n  as_tibble() %>% \n  pivot_longer(starts_with(\"b_\")) %>% \n  ggplot(aes(x = value)) + \n  geom_histogram(bins = 40) +\n  facet_wrap(~ name, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](FinalProject_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nThese histograms show the posterior distributions of the intercept and slope. Most of the slope distribution lies above 0, which matches our earlier conclusion that the association between neural alignment and perceived similarity is likely positive.\n\nWe can also summarize these posterior distributions with simple descriptive statistics, such as the posterior mean, posterior standard deviation, and 95% credible interval.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_draws_df(fit_brm_1) %>% \n  as_tibble() %>%\n  pivot_longer(starts_with(\"b_\")) %>% \n  group_by(name) %>% \n  summarise(mean = mean(value),\n            sd = sd(value),\n            lower = quantile(value, probs = 0.025),\n            upper = quantile(value, probs = 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  name         mean    sd  lower upper\n  <chr>       <dbl> <dbl>  <dbl> <dbl>\n1 b_Intercept 5.01  0.145 4.72   5.29 \n2 b_r2_vox_z  0.376 0.142 0.0955 0.658\n```\n\n\n:::\n:::\n\n\nThis gives results very similar to `summary(fit_brm_1)`, but here we are computing them directly from the posterior draws. For the intercept, the posterior mean is about 5.00, with a 95% credible interval from about 4.72 to 5.29. For the slope, the posterior mean is about 0.38, with a 95% credible interval from about 0.09 to 0.65.\n\n# Model comparison\n\n## Adding an Interaction to the model\n\nSo far, we have fit a simple model predicting perceived similarity from neural alignment. This model treats all dyads as coming from one pooled group. However, our data include both friend dyads and stranger dyads. This matters because friends may generally report higher similarity than strangers, regardless of their neural alignment.\n\nTo account for this, we fit an interaction model with `group` as an additional predictor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_brm_2 <- brm(\n  data = df,\n  mean_similarity_comp ~ r2_vox_z * group,\n  family = gaussian(),\n  prior = my_priors,\n  iter = 2000, \n  chains = 4, \n  seed = 20,\n  sample_prior = TRUE\n)\n```\n:::\n\n\nThe interaction term asks whether the slope of `r2_vox_z` differs between friend and stranger dyads.\n\n## Model results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_brm_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: mean_similarity_comp ~ r2_vox_z * group \n   Data: df (Number of observations: 48) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n                       Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS\nIntercept                  5.69      0.13     5.42     5.94 1.00     3360\nr2_vox_z                   0.22      0.13    -0.04     0.48 1.00     2564\ngroupstranger             -1.51      0.19    -1.86    -1.13 1.00     3472\nr2_vox_z:groupstranger    -0.22      0.18    -0.56     0.13 1.00     2846\n                       Tail_ESS\nIntercept                  2703\nr2_vox_z                   2529\ngroupstranger              2830\nr2_vox_z:groupstranger     2727\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     0.60      0.07     0.48     0.75 1.00     3689     2871\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nAfter adding the interaction between neural alignment and dyad group, the model suggested a clear group difference but weak evidence for different slopes by group.\n\n-   Friend dyads showed an estimated positive slope for `r2_vox_z` of 0.22, but the 95% credible interval ranged from -0.03 to 0.47.\n-   Stranger dyads were estimated to report similarity scores 1.51 points lower than friend dyads when neural alignment was average.\n-   The interaction term was -0.22, with a 95% credible interval from -0.55 to 0.12, suggesting that the data do not provide strong evidence that the effect differs between friend and stranger dyads.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws2 <- as_draws_df(fit_brm_2)\n\ndraws2 %>% \n  mutate(\n    slope_friend = b_r2_vox_z,\n    slope_stranger = b_r2_vox_z + `b_r2_vox_z:groupstranger`\n  ) %>% \n  summarise(\n    friend_mean = mean(slope_friend),\n    friend_lower = quantile(slope_friend, 0.025),\n    friend_upper = quantile(slope_friend, 0.975),\n    stranger_mean = mean(slope_stranger),\n    stranger_lower = quantile(slope_stranger, 0.025),\n    stranger_upper = quantile(slope_stranger, 0.975)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  friend_mean friend_lower friend_upper stranger_mean stranger_lower\n        <dbl>        <dbl>        <dbl>         <dbl>          <dbl>\n1       0.221      -0.0402        0.483       0.00454         -0.247\n# ℹ 1 more variable: stranger_upper <dbl>\n```\n\n\n:::\n:::\n\n\nThe interaction model suggests that the neural alignment slope may be more positive for friend dyads than for stranger dyads. Because both intervals include 0, the model no longer provides strong evidence that neural alignment clearly predicts perceived similarity within either group.\n\n## Leave-One-Out Cross Validation (LOO-CV)\n\nFinally, we compare the original model and the interaction model using leave-one-out cross validation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_brm_1 <- add_criterion(fit_brm_1, \"loo\")\nfit_brm_2 <- add_criterion(fit_brm_2, \"loo\")\n\nloo_compare(fit_brm_1, fit_brm_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          elpd_diff se_diff\nfit_brm_2   0.0       0.0  \nfit_brm_1 -24.7       3.5  \n```\n\n\n:::\n:::\n\n\nThe LOO-CV results favor the interaction model. Including dyad group substantially improves prediction of perceived similarity. This improvement seems to come mainly from the friend vs. stranger difference.\n\n## Session information\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.3.3 (2024-02-29 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=Korean_Korea.utf8  LC_CTYPE=Korean_Korea.utf8   \n[3] LC_MONETARY=Korean_Korea.utf8 LC_NUMERIC=C                 \n[5] LC_TIME=Korean_Korea.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] tidybayes_3.0.7 brms_2.22.0     Rcpp_1.0.14     ggside_0.4.1   \n [5] lubridate_1.9.4 forcats_1.0.0   stringr_1.6.0   dplyr_1.1.4    \n [9] purrr_1.0.2     readr_2.1.5     tidyr_1.3.1     tibble_3.2.1   \n[13] ggplot2_4.0.0   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1     svUnit_1.0.8         farver_2.1.1        \n [4] loo_2.9.0            S7_0.2.0             fastmap_1.2.0       \n [7] TH.data_1.1-4        tensorA_0.36.2.1     digest_0.6.35       \n[10] estimability_1.5.1   timechange_0.3.0     lifecycle_1.0.5     \n[13] StanHeaders_2.32.10  processx_3.8.6       survival_3.5-8      \n[16] magrittr_2.0.3       posterior_1.6.1      compiler_4.3.3      \n[19] rlang_1.1.5          tools_4.3.3          utf8_1.2.4          \n[22] yaml_2.3.10          knitr_1.50           labeling_0.4.3      \n[25] bridgesampling_1.2-1 htmlwidgets_1.6.4    curl_6.2.2          \n[28] pkgbuild_1.4.8       plyr_1.8.9           RColorBrewer_1.1-3  \n[31] multcomp_1.4-28      abind_1.4-8          withr_3.0.2         \n[34] grid_4.3.3           stats4_4.3.3         colorspace_2.1-0    \n[37] xtable_1.8-4         inline_0.3.21        emmeans_2.0.0       \n[40] scales_1.4.0         MASS_7.3-60.0.1      cli_3.6.4           \n[43] mvtnorm_1.3-3        rmarkdown_2.30       generics_0.1.4      \n[46] RcppParallel_5.1.10  rstudioapi_0.17.1    reshape2_1.4.4      \n[49] tzdb_0.4.0           rstan_2.32.7         splines_4.3.3       \n[52] bayesplot_1.15.0     parallel_4.3.3       matrixStats_1.5.0   \n[55] vctrs_0.6.5          V8_8.0.1             Matrix_1.6-5        \n[58] sandwich_3.1-1       jsonlite_2.0.0       callr_3.7.6         \n[61] hms_1.1.3            arrayhelpers_1.1-0   ggdist_3.3.3        \n[64] glue_1.8.0           ps_1.9.0             codetools_0.2-19    \n[67] distributional_0.6.0 stringi_1.8.7        gtable_0.3.6        \n[70] QuickJSR_1.7.0       pillar_1.11.1        htmltools_0.5.8.1   \n[73] Brobdingnag_1.2-9    R6_2.6.1             evaluate_1.0.5      \n[76] lattice_0.22-5       backports_1.4.1      rstantools_2.6.0    \n[79] coda_0.19-4.1        gridExtra_2.3        nlme_3.1-164        \n[82] checkmate_2.3.2      mgcv_1.9-1           xfun_0.52           \n[85] zoo_1.8-13           pkgconfig_2.0.3     \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "FinalProject_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}