{
  "hash": "ace359e5e099a81024b45e25eafcbd5c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Logistic Regression\"\nsubtitle: \"Princeton University\"\nauthor: \"Diana Kim\"\noutput: \n  tufte::tufte_html:\n    css: \n    tufte_variant: \"envisioned\"\n    highlight: github-dark\n    fig_height: 10\n    fig_width: 16\n    toc: true\n    toc_depth: 1\nexecute: \n  message: false\n  warning: false\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\nengine: knitr\n---\n\n-   Assignment requirements:\n\n    -   If you are using Github (recommended), make sure to commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages, and share the link to your assignment with me. If not, you can also send me the **rmd** & **rendered file** via Canvas.\n\n    -   In this assignment, you will not need to code from scratch. Rather, you'll need to fill in code where needed. This assignment walks through a logistic regression implementation from EDA to model comparison — useful as a reference for your own future analyses.\n\n    -   I want the assignments to begin reflecting a bit more of how you'd be doing things on your own, where you have some prior knowledge and you figure other things out (by referring to documentation, etc.). In addition to the rendered file, I also want you to submit **notes** of anything new that you learn while finishing the assignment, and any pain-points — we'll discuss more.\n\n-   Note:\n\n    -   If you are fitting a model, display the model output in a neatly formatted table. (The `gt`, `tidy`, and `kable` functions can help!). `modelsummary` also works well: <https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html>\n\n    -   Make sure that your plots are clearly labeled — all axes, titles, etc.\n\n    -   When computing confidence intervals for odds ratios, always exponentiate the CI endpoints from the log-odds scale. Do **not** add/subtract SE on the OR scale directly.\n\n## Data: General Social Survey\n\nThe General Social Survey (GSS) has been used to measure trends in attitudes and behaviors in American society since 1972. In addition to collecting demographic information, the survey includes questions used to gauge attitudes about government spending priorities, confidence in institutions, lifestyle, and many other topics. A full description of the survey may be found here.\n\nThe data for this lab are from the 2016 General Social Survey. The original data set contains 2867 observations and 935 variables. We will use and abbreviated data set that includes the following variables:\n\nnatmass: Respondent’s answer to the following prompt:\n\n“We are faced with many problems in this country, none of which can be solved easily or inexpensively. I’m going to name some of these problems, and for each one I’d like you to tell me whether you think we’re spending too much money on it, too little money, or about the right amount…are we spending too much, too little, or about the right amount on mass transportation?”\n\nage: Age in years.\n\nsex: Sex recorded as male or female\n\nsei10: Socioeconomic index from 0 to 100\n\nregion: Region where interview took place\n\npolviews: Respondent’s answer to the following prompt:\n\n“We hear a lot of talk these days about liberals and conservatives. I’m going to show you a seven-point scale on which the political views that people might hold are arranged from extremely liberal - point 1 - to extremely conservative - point 7. Where would you place yourself on this scale?”\n\nThe data are in gss2016.csv in the data folder.\n\n## EDA\n\n> Let’s begin by making a binary variable for respondents’ views on spending on mass transportation. Create a new variable that is equal to “1” if a respondent said spending on mass transportation is about right and “0” otherwise. Then plot the proportion of the response variable, using informative labels for each category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(readr)\n#install.packages('modelsummary')\n#library(modelsummary)\nlibrary(tidyr)\nlibrary(knitr)\n#install.packages('easystats')\nlibrary(easystats)\nlibrary(broom)\nlibrary(emmeans)\n#install.packages(\"marginaleffects\")\nlibrary(marginaleffects)\nlibrary(performance)\n#install.packages('arm')\nlibrary(arm)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\ndata <- read.csv(\"gss2016.csv\")\nhead(data,30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       natmass age    sex sei10          region             polviews\n1   Too little  47   Male  87.9     New england             Moderate\n2   Too little  61   Male  38.3     New england              Liberal\n3     Too much  43 Female  21.8     New england             Moderate\n4   Too little  55 Female  39.7     New england     Slightly liberal\n5  About right  53 Female  44.6     New england     Slightly liberal\n6   Too little  50   Male  80.7     New england     Slightly liberal\n7     Too much  23 Female  20.1 Middle atlantic Slghtly conservative\n8     Too much  71   Male  32.0 Middle atlantic         Conservative\n9  About right  86 Female  13.2 Middle atlantic Slghtly conservative\n10  Too little  32   Male  20.8 Middle atlantic     Slightly liberal\n11 About right  60 Female  24.2 Middle atlantic              Liberal\n12    Too much  76   Male  67.7     New england             Moderate\n13  Too little  33 Female  61.4     New england             Moderate\n14 About right  56   Male  23.3     New england         Conservative\n15  Too little  62 Female  25.7     New england     Slightly liberal\n16  Too little  31   Male  80.9     New england              Liberal\n17 About right  43   Male  39.2     New england              Liberal\n18  Too little  58 Female  24.2     New england              Liberal\n19 About right  32 Female  33.3 Middle atlantic Slghtly conservative\n20 About right  23 Female  21.6 Middle atlantic     Slightly liberal\n21    Too much  37 Female  66.2 Middle atlantic Extrmly conservative\n22 About right  25 Female  14.8 Middle atlantic              Liberal\n23  Too little  71   Male  82.5 Middle atlantic              Liberal\n24 About right  22   Male  39.9 Middle atlantic             Moderate\n25 About right  74   Male  82.5 Middle atlantic             Moderate\n26  Too little  75 Female  37.6 Middle atlantic         Conservative\n27 About right  32   Male  20.7 Middle atlantic              Liberal\n28 About right  68 Female  46.7 Middle atlantic             Moderate\n29 About right  55   Male  65.3 Middle atlantic Slghtly conservative\n30 About right  46   Male  65.3 Middle atlantic Slghtly conservative\n```\n\n\n:::\n:::\n\n\nFill in the \"\\_\\_\\_\\_\" below to encode the binary variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n   mutate(mass_trans_spend_right = if_else(natmass == 'About right', 1, 0))\nhead(data, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       natmass age    sex sei10          region             polviews\n1   Too little  47   Male  87.9     New england             Moderate\n2   Too little  61   Male  38.3     New england              Liberal\n3     Too much  43 Female  21.8     New england             Moderate\n4   Too little  55 Female  39.7     New england     Slightly liberal\n5  About right  53 Female  44.6     New england     Slightly liberal\n6   Too little  50   Male  80.7     New england     Slightly liberal\n7     Too much  23 Female  20.1 Middle atlantic Slghtly conservative\n8     Too much  71   Male  32.0 Middle atlantic         Conservative\n9  About right  86 Female  13.2 Middle atlantic Slghtly conservative\n10  Too little  32   Male  20.8 Middle atlantic     Slightly liberal\n11 About right  60 Female  24.2 Middle atlantic              Liberal\n12    Too much  76   Male  67.7     New england             Moderate\n13  Too little  33 Female  61.4     New england             Moderate\n14 About right  56   Male  23.3     New england         Conservative\n15  Too little  62 Female  25.7     New england     Slightly liberal\n   mass_trans_spend_right\n1                       0\n2                       0\n3                       0\n4                       0\n5                       1\n6                       0\n7                       0\n8                       0\n9                       1\n10                      0\n11                      1\n12                      0\n13                      0\n14                      1\n15                      0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions\nmass_spend_summary <- data %>%\n  count(mass_trans_spend_right) %>%\n  mutate(proportion = n / sum(n))\nhead(mass_spend_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  mass_trans_spend_right    n proportion\n1                      0 1218  0.4702703\n2                      1 1372  0.5297297\n```\n\n\n:::\n\n```{.r .cell-code}\n#Look at the dataframe structure. And make sure it's in a format that you can use for plotting.\n#Change structure if needed\nmass_spend_long <- mass_spend_summary # I guess it's not needed??\n\n#Factorise for plot\nmass_spend_long$mass_trans_spend_right <- as.factor(mass_spend_long$mass_trans_spend_right)\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\nggplot(mass_spend_long, aes(x = \"\", y = proportion, fill = factor(mass_trans_spend_right))) +\n  geom_bar(stat=\"identity\") +\n  labs(x = \"Mass Transportation Spending\",\n       y = \"Proportion\",\n       fill = \"Response\") +\n  scale_fill_discrete(labels = c(\"0\" = \"Not right\",\n                              \"1\" = \"About right\"))\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n> Recode `polviews` so it is a factor with levels that are in an order that is consistent with question on the survey. Note how the categories are spelled in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(polviews = factor(polviews,\n                           levels = c(\"Extremely liberal\",\n                                      \"Liberal\",\n                                      \"Slightly liberal\",\n                                      \"Moderate\",\n                                      \"Slghtly conservative\",  #\n                                      \"Conservative\",\n                                      \"Extrmly conservative\"), #\n                           ordered = TRUE))\n\n#head(data, 20)\nunique(data$polviews)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Moderate             Liberal              Slightly liberal    \n[4] Slghtly conservative Conservative         Extrmly conservative\n[7] Extremely liberal   \n7 Levels: Extremely liberal < Liberal < Slightly liberal < ... < Extrmly conservative\n```\n\n\n:::\n:::\n\n\n> Make a plot of the distribution of `polviews`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions, format, and produce a plot like you did previously for mass_trans_spend_right\npolviews_summary <- data %>%\n  count(polviews) %>%\n  mutate(proportion = n / sum(n))\nhead(polviews_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              polviews   n proportion\n1    Extremely liberal 133 0.05135135\n2              Liberal 336 0.12972973\n3     Slightly liberal 290 0.11196911\n4             Moderate 974 0.37606178\n5 Slghtly conservative 358 0.13822394\n6         Conservative 395 0.15250965\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(polviews_summary, aes(x = polviews, y = proportion)) +\n  geom_col() +\n  labs(x = \"Political views (1 = extremely liberal, 7 = extremely conservative)\",\n       y = \"Proportion\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(polviews_summary, aes(x = \"\", y = proportion, fill = polviews)) +\n  geom_bar(stat = \"identity\") +\n  labs(x = \"\",\n       y = \"Proportion\",\n       fill = \"Political views\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n> Which political view occurs most frequently in this data set?\n>\n> Moderate\n\n> Make a plot displaying the relationship between satisfaction with mass transportation spending and political views. Use the plot to describe the relationship the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npol_mass_summary <- data %>%\n  group_by(polviews) %>%\n  summarise(prop_about_right = mean(mass_trans_spend_right, na.rm = TRUE))\n\nggplot(data,\n       aes(x = polviews,\n           fill = factor(mass_trans_spend_right))) +\n  geom_bar(position = \"fill\") +\n  labs(x = \"Political Views\",\n       y = \"Proportion\",\n       fill = \"Mass Transportation Spending\") +\n  scale_fill_discrete(labels = c(\"Not right\", \"About right\")) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe more conservative one's political views are the more they think the amount of spending on mass transportation is correct.\n\n-   We’d like to use age as a quantitative variable in your model; however, it is currently a character data type because some observations are coded as \"89 or older\".\n\n> Recode age so that is a numeric variable. Note: Before making the variable numeric, you will need to replace the values \"89 or older\" with a single value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(age = if_else(age == \"89 or older\", \"89\", age), \n         age = as.numeric(age))\nsummary(data$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   18.0    34.0    49.0    48.9    62.0    89.0 \n```\n\n\n:::\n:::\n\n\n> Plot the frequency distribution of age.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = age)) +\n  geom_histogram(binwidth = 5, fill = \"steelblue\") +\n  labs(x = \"Age\",\n       y = \"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## Logistic regression\n\n> Let’s start by fitting a logistic regression model with just the intercept\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercept_only_model <- glm(\n  mass_trans_spend_right ~ 1,\n  data = data,\n  family = binomial\n)\n\nintercept_only_model %>% \n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 0.1190594| 0.0393685|  3.024229| 0.0024927|\n\n\n:::\n:::\n\n\n> Interpret the intercept in the context of the data. You can do this by converting the $\\beta_0$ parameter out of the log-odds metric to the probability metric. Make sure to include the 95% confidence intervals. Then interpret the results in a sentence or two--what is the basic thing this probability tells us about?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb0 <- coef(intercept_only_model)[1] # get coef\n\nb0_transformed <- plogis(b0) # convert log-odds to probability\n\n# Hint: compute CIs on the log-odds scale FIRST, then convert to probability\nci_lower_logodds = b0 - 1.96 * 0.0393685\nci_upper_logodds = b0 + 1.96 * 0.0393685\n\n\n# p_lower = exp(ci_lower) / (1 + exp(ci_lower))\n# p_upper = exp(ci_upper) / (1 + exp(ci_upper))\n\np_lower = plogis(ci_lower_logodds)\np_upper = plogis(ci_upper_logodds)\n\nb0_transformed\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5297297 \n```\n\n\n:::\n\n```{.r .cell-code}\np_lower\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5104727 \n```\n\n\n:::\n\n```{.r .cell-code}\np_upper\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5488986 \n```\n\n\n:::\n:::\n\n\nInterpretation: The model estimates that the probability a randomly selected person reports spending on mass transportation is 'about right' is around 53% (95% CI: 0.51, 0.55).\n\n> Now let's fit a model using the demographic factors - `age`,`sex`, `sei10` - to predict the odds a person is satisfied with spending on mass transportation. Make any necessary adjustments to the variables so the intercept will have a meaningful interpretation. *Neatly display the model coefficients (do not display the summary output)*\n\n*Hint: For the intercept to be meaningful, it should represent the log-odds for a realistic person. What does age = 0 and sei10 = 0 mean? Consider centering continuous predictors.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#make sure that sex is a factor\ndata <- data %>%\n  mutate(sex = factor(sex))\n\n#center continuous predictors so the intercept is meaningful\ndata <- data %>%\n  mutate(\n    age_c = age - mean(age, na.rm = TRUE),\n    sei10_c = sei10 - mean(sei10, na.rm = TRUE)\n  )\n\n#fit with glm()\ndemo_model <- glm(\n  mass_trans_spend_right ~ age_c + sex + sei10_c,\n  data = data,\n  family = binomial\n)\n\n#produce tidy output of model coefficients\ndemo_model %>%\n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) |  0.2371084| 0.0539555|  4.394520| 0.0000111|\n|age_c       | -0.0061659| 0.0022824| -2.701502| 0.0069027|\n|sexMale     | -0.2557439| 0.0798020| -3.204732| 0.0013519|\n|sei10_c     | -0.0062271| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n:::\n\n\n> Consider the relationship between sex and one’s opinion about spending on mass transportation. Interpret the coefficient of sex in terms of the log-odds and OR of being satisfied with spending on mass transportation. What are the predicted probabilities for males and females on support for spending on mass transportation? Please include the 95% CIs around each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- demo_model\n\nm1 %>% \n  tidy() %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    0.237|     0.054|     4.395|   0.000|\n|age_c       |   -0.006|     0.002|    -2.702|   0.007|\n|sexMale     |   -0.256|     0.080|    -3.205|   0.001|\n|sei10_c     |   -0.006|     0.002|    -3.749|   0.000|\n\n\n:::\n\n```{.r .cell-code}\nm1 %>% \n  tidy(exponentiate = TRUE, conf.int = TRUE) %>%\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |    1.268|     0.054|     4.395|   0.000|    1.141|     1.409|\n|age_c       |    0.994|     0.002|    -2.702|   0.007|    0.989|     0.998|\n|sexMale     |    0.774|     0.080|    -3.205|   0.001|    0.662|     0.905|\n|sei10_c     |    0.994|     0.002|    -3.749|   0.000|    0.991|     0.997|\n\n\n:::\n\n```{.r .cell-code}\nbsex <- coef(m1)[\"sexMale\"]\nbsex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sexMale \n-0.2557439 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_lower_lo = bsex - 1.96 * 0.0798020\nci_upper_lo = bsex + 1.96 * 0.0798020\nci_lower_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   sexMale \n-0.4121558 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sexMale \n-0.09933194 \n```\n\n\n:::\n\n```{.r .cell-code}\n# exponentiate the log-odds CIs\nci_lower_or = exp(ci_lower_lo)\nci_upper_or = exp(ci_upper_lo)\nci_lower_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sexMale \n0.6622211 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sexMale \n0.9054421 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Get predicted probabilities with emmeans\nemm_sex <- emmeans(m1, \"sex\", type = \"response\")\nemm_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sex     prob     SE  df asymp.LCL asymp.UCL\n Female 0.559 0.0133 Inf     0.533     0.585\n Male   0.495 0.0147 Inf     0.467     0.524\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n:::\n\n\nIf you did this right, you'll find that being female (as compared to male) is associated with an increase in the log-odds of being satisfied with spending on mass transportation by 0.2557439 units (95% CI \\[0.09, 0.41\\]), holding all other variables constant. This equates to the odds of thinking the spending amount is right in females being 1.29 times the odds of thinking this in men (95% CI \\[1.13, 1.44\\]).\n\nThe predicted probability for females to be satisfied with spending on mass transportation is 55.9% (95% CI \\[53.3%, 58.5%\\]) and that of males is 49.5% (95% CI \\[46.7%, 52.4%\\]).\\\n\\\nVerify this.\n\n> Next, consider the relationship between age and one’s opinion about spending on mass transportation. Interpret the coefficient of age in terms of the log-odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbage <- coef(m1)[\"age_c\"]\nse_age <- summary(m1)$coefficients[\"age_c\", \"Std. Error\"] # get SE from model\nbage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age_c \n-0.00616594 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Log-odds CIs\nci_lower_lo = bage - 1.96 * se_age\nci_upper_lo = bage + 1.96 * se_age\nci_lower_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      age_c \n-0.01063947 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       age_c \n-0.001692412 \n```\n\n\n:::\n\n```{.r .cell-code}\n# OR and OR CIs (remember: exponentiate the log-odds CIs)\nor_age = exp(bage)\nci_lower_or = exp(ci_lower_lo)\nci_upper_or = exp(ci_upper_lo)\nor_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   age_c \n0.993853 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_lower_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    age_c \n0.9894169 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   age_c \n0.998309 \n```\n\n\n:::\n:::\n\n\nA one unit increase in age is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.006 (95% CI \\[-0.011, -0.002\\]), holding all other variables constant. The odds ratio is 0.994 (95% CI \\[0.990, 0.998\\]), which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of age, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.994, or approximately 0.6% per unit increase in age, holding other factors constant.\n\n> Consider the relationship between SES and one’s opinion about spending on mass transportation. Interpret the coefficient of SES in terms of the log-odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbses <- coef(m1)[\"sei10_c\"]\nse_ses <- summary(m1)$coefficients[\"sei10_c\", \"Std. Error\"] # get SE for sei10\nbses\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sei10_c \n-0.006227141 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Log-odds CIs\nci_lower_lo = bses - 1.96 * se_ses\nci_upper_lo = bses + 1.96 * se_ses\nci_lower_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sei10_c \n-0.009482529 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_lo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sei10_c \n-0.002971752 \n```\n\n\n:::\n\n```{.r .cell-code}\n# OR and OR CIs\nor_ses = exp(bses)\nci_lower_or = exp(ci_lower_lo)\nci_upper_or = exp(ci_upper_lo)\nor_ses\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sei10_c \n0.9937922 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_lower_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sei10_c \n0.9905623 \n```\n\n\n:::\n\n```{.r .cell-code}\nci_upper_or\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  sei10_c \n0.9970327 \n```\n\n\n:::\n:::\n\n\nA one unit increase in SES index is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.006 units (95% CI \\[-0.010, -0.003\\]), holding all other variables constant. The odds ratio is 0.994 (95% CI \\[0.991, 0.997\\]), which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of SES index, the odds of being satisfied with mass transportation spending change by a factor of about 0.994, or approximately 0.6% per unit increase in SES index, holding other factors constant.\n\n## Marginal effects\n\n-   Let's examine the results on the probability scale.\n\n> Calculate the marginal effects of sex, age, and SES on mass transportation spending. You can use the `margins` package function `margins` discussed in your textbook or you can use the `marginaleffects` package `avg_slope` `avg_comparisons` discussed in lecture. Interpret each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(m1, comparison = \"difference\") %>% \n  kable(digits=4)\n```\n\n::: {.cell-output-display}\n\n\n|term    |contrast      | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:-------|:-------------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|age_c   |+1            |  -0.0015|    0.0006|   -2.7161|  0.0066|  7.2422|  -0.0026|   -0.0004|\n|sei10_c |+1            |  -0.0015|    0.0004|   -3.7894|  0.0002| 12.6928|  -0.0023|   -0.0007|\n|sex     |Male - Female |  -0.0631|    0.0196|   -3.2103|  0.0013|  9.5585|  -0.1016|   -0.0246|\n\n\n:::\n:::\n\n\n-   The marginal effect of age is -0.0015 (95% CI \\[-0.0026, 0.0004\\]). So, for each additional unit increase of age, the probability of being satisfied with mass transportation spending decreases by approximately 0.15 percentage points, holding other factors constant (p = 0.0066).\n\n-   The marginal effect of SES is -0.0015 (95% CI \\[-0.0023, -0.0007). For each one-unit increase in the socioeconomic index, the probability of being satisfied with mass transportation spending decreases by approximately 0.15 percentage points, holding other variables constant.\n\n-   The marginal effect for being female compared to male is -0.0631 (95% CI \\[-0.1016, -0.0246\\]). This indicates that females are, on average, about 6.3 percentage points more likely than males to be satisfied with mass transportation spending, holding other factors constant.\n\n## Model comparison\n\n-   Now let’s see whether a person’s political views has a significant impact on their odds of being satisfied with spending on mass transportation, after accounting for the demographic factors.\n\n> Conduct a drop-in-deviance/likelihood ratio test to determine if polviews is a significant predictor of attitude towards spending on mass transportation. Name these two models `fit2` and `fit3`, respectively. Compare the two models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- glm(\n  mass_trans_spend_right ~ age_c + sex + sei10_c,\n  data = data,\n  family = binomial\n)\n\nfit3 <- glm(\n  mass_trans_spend_right ~ age_c + sex + sei10_c + polviews,\n  data = data,\n  family = binomial\n)\n\ntest_likelihoodratio(fit2, fit3) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|     |Name |Model | df| df_diff|     Chi2|  p|\n|:----|:----|:-----|--:|-------:|--------:|--:|\n|fit2 |fit2 |glm   |  4|      NA|       NA| NA|\n|fit3 |fit3 |glm   | 10|       6| 63.02844|  0|\n\n\n:::\n:::\n\n\n> Is the model with polviews better than the model without?\n\n-   Yes.\n\n## Visualization\n\n-   Let’s plot the results\n\n-   We next use the model to produce visualizations:\n\n    -   Given the code below, interpret what is being plotted:\n\n        -   pol_plot : The predicted probability of being satisfied with mass transportation spending across political views, holding other factors (age, sex, SES) constant\n\n        -   sex_plot : The predicted probability of being satisfied with mass transportation spending for males and females, holding other factors constant.\n\n        -   ses_plot: The predicted probability of being satisfied with mass transportation spending across SES spectrum, holding other factors constant.\n\n    ::: callout-tip\n    -   adjust the various settings in your plot to make it look professional.\n\n    -   You can use `ggeffects` to get the predicted probabilities for these models.\n    :::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages('ggeffects')\nlibrary(ggeffects)\n\n\ncolors <- c(\"Extremely liberal\" = \"black\",\n            \"Liberal\" = \"#0e2f44\",  # Dark blue\n            \"Slightly liberal\" = \"#1d5a6c\",  # Less dark blue\n            \"Moderate\" = \"#358ca3\",  # Medium blue\n            \"Slghtly conservative\" = \"#71b9d1\",  # Light blue\n            \"Conservative\" = \"#a6dcef\",  # Lighter blue\n            \"Extrmly conservative\" = \"#d0f0fd\")  # Very light blue\n\ncorrect_labels <- c(\"Extremely liberal\" = \"Extremely liberal\",\n                    \"Liberal\" = \"Liberal\",\n                    \"Slightly liberal\" = \"Slightly liberal\",\n                    \"Moderate\" = \"Moderate\",\n                    \"Slghtly conservative\" = \"Slightly conservative\",\n                    \"Conservative\" = \"Conservative\",\n                    \"Extrmly conservative\" = \"Extremely conservative\")\n\npp_pol <- ggemmeans(fit3, terms = c(\"polviews\"))\n\n# Adjusted plot with gradient colors\npol_plot <- ggplot(pp_pol, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 3) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  scale_color_manual(values = colors, labels = correct_labels) +\n  scale_x_discrete(labels = correct_labels) +\n  labs(title = \"Effect of Political Views on Satisfaction with Mass Transportation\",\n       x = \"Political Views\", y = \"Predicted Probability\",\n       color = \"Political Views\") +\n  theme_minimal()\n\npol_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-19-1.png){width=1152}\n:::\n\n```{.r .cell-code}\n  labs(title = \"Effect of Political Views on Satisfaction with Mass Transportation\",\n       x = \"Political Views\", y = \"Predicted Probability\",\n       color = \"Political Views\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNULL\n```\n\n\n:::\n\n```{.r .cell-code}\npol_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-19-2.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_sex <- ggemmeans(fit3, terms = c(\"sex\"))\n\nsex_plot <- ggplot(pp_sex, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  labs(title = \"Effect of Sex on Satisfaction with Mass Transportation\",\n       x = \"Sex\", y = \"Predicted Probability\",\n       color = \"Sex\") +\n  theme_minimal()\n\nsex_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-19-3.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_ses <- ggemmeans(fit3, terms = \"sei10_c\")\n\n\nses_plot <-  ggplot(pp_ses, aes(x = x, y = predicted)) +\n  geom_line(color = \"#2c7fb8\", size = 1) + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = \"#2c7fb8\", alpha = 0.2) +  # Add a confidence interval band\n  labs(title = \"Effect of SES on Satisfaction with Mass Transportation\",\n       x = \"Socioeconomic Status\", y = \"Predicted Probability\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")  \nses_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-19-4.png){width=1152}\n:::\n:::\n\n\n## Model Assumptions\n\n-   Is the logistic model a good choice for this data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 86% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n:::\n\n\n::: callout-note\nAnswer: The model isn't perfectly capturing the relationship. So I guess.. no?\n:::\n\n## Model fit\n\n-   Calculate the $R^2$ for this model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.010\n  adj. R2: 0.009\n```\n\n\n:::\n:::\n\n\n> R2 interpretation: The model's R2 value (0.010) is quite small.\n>\n> Next, Take a look at the binned residual plots for each continuous predictor variable and look at linearity. Is there a predictor that sticks out? What can we do to improve model fit in this case?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10_c\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 88% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age_c\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOk: About 98% of the residuals are inside the error bounds.\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10_c\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age_c\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-22-2.png){width=672}\n:::\n:::\n\n\n::: callout-note\nThe relationship between SES and the log-odds of mass transportation satisfaction may not be linear. We might want to try different curves for this factor.\n:::\n\n## Improving Model Fit\n\n> Based on your binned residual plots above, one predictor may show signs of nonlinearity. Try adding a squared term for that predictor, refit the model, and compare using a likelihood ratio test. Do the binned residuals improve?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Refit with squared term\nfit2_improved <- glm(\n  mass_trans_spend_right ~ age_c +\n                           sei10_c + I(sei10_c^2) +\n                           sex,\n  data = data,\n  family = binomial\n)\n\n# Compare models\ntest_likelihoodratio(fit2, fit2_improved) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|              |Name          |Model | df| df_diff|     Chi2|         p|\n|:-------------|:-------------|:-----|--:|-------:|--------:|---------:|\n|fit2          |fit2          |glm   |  4|      NA|       NA|        NA|\n|fit2_improved |fit2_improved |glm   |  5|       1| 4.653371| 0.0309926|\n\n\n:::\n\n```{.r .cell-code}\n# Check binned residuals again\nbinned_residuals(fit2_improved, term = \"sei10_c\") %>% plot(show_dots = TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nDid adding the squared term improve the model? Yes!\n:::\n\n## Testing Polviews\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                   estimate        SE  df z.ratio\n Extremely liberal - Moderate             -0.9266262 0.1950664 Inf  -4.750\n Extremely liberal - Slghtly conservative -0.8487137 0.2127293 Inf  -3.990\n Extremely liberal - Conservative         -0.9935486 0.2108369 Inf  -4.712\n Extremely liberal - Extrmly conservative -1.3402621 0.2792876 Inf  -4.799\n Liberal - Moderate                       -0.7090022 0.1308520 Inf  -5.418\n Liberal - Slghtly conservative           -0.6310897 0.1555805 Inf  -4.056\n Liberal - Conservative                   -0.7759246 0.1532081 Inf  -5.065\n Liberal - Extrmly conservative           -1.1226380 0.2392048 Inf  -4.693\n Slightly liberal - Extrmly conservative  -0.7334002 0.2412625 Inf  -3.040\n p.value\n  <.0001\n  0.0013\n  0.0001\n  <.0001\n  <.0001\n  0.0010\n  <.0001\n  0.0001\n  0.0382\n\nResults are averaged over the levels of: sex \nResults are given on the log odds ratio (not the response) scale. \nP value adjustment: tukey method for comparing a family of 7 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\", type=\"response\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                 odds.ratio         SE  df null\n Extremely liberal / Moderate              0.3958871 0.07722426 Inf    1\n Extremely liberal / Slghtly conservative  0.4279651 0.09104070 Inf    1\n Extremely liberal / Conservative          0.3702605 0.07806458 Inf    1\n Extremely liberal / Extrmly conservative  0.2617771 0.07311109 Inf    1\n Liberal / Moderate                        0.4921350 0.06439684 Inf    1\n Liberal / Slghtly conservative            0.5320118 0.08277063 Inf    1\n Liberal / Conservative                    0.4602780 0.07051835 Inf    1\n Liberal / Extrmly conservative            0.3254202 0.07784206 Inf    1\n Slightly liberal / Extrmly conservative   0.4802732 0.11587191 Inf    1\n z.ratio p.value\n  -4.750  <.0001\n  -3.990  0.0013\n  -4.712  0.0001\n  -4.799  <.0001\n  -5.418  <.0001\n  -4.056  0.0010\n  -5.065  <.0001\n  -4.693  0.0001\n  -3.040  0.0382\n\nResults are averaged over the levels of: sex \nP value adjustment: tukey method for comparing a family of 7 estimates \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n> Using the pairwise comparisons above, fill in the blanks. Be specific: are these odds ratios or probability differences? The `type=\"response\"` output gives odds ratios for logistic models.\n\n-   Conservatives have 2.70, 2.17 times the odds of supporting mass transit spending compared to extremely liberal and liberal respondents\n\n-   Extreme liberals have 0.37, 0.40, 0.43 times the odds of supporting spending compared to conservatives, moderates, and slightly conservative respondents\n\n-   Extremely conservative respondents have 3.08, 2.08 times the odds of supporting mass spending compared to liberals and slightly liberal respondents\n\n-   Liberals have 0.49, 0.53 times the odds of supporting spending compared to moderates and slightly conservative respondents\n\n## Conclusion\n\n\\_\\_\\_ based on the model summary below, and the three figures.\n\n\n|         | Df|  Deviance| Resid. Df| Resid. Dev|  Pr(>Chi)|\n|:--------|--:|---------:|---------:|----------:|---------:|\n|NULL     | NA|        NA|      2589|   3581.340|        NA|\n|age_c    |  1|  9.268443|      2588|   3572.072| 0.0023314|\n|sex      |  1| 12.156624|      2587|   3559.915| 0.0004891|\n|sei10_c  |  1| 14.119078|      2586|   3545.796| 0.0001716|\n|polviews |  6| 63.028441|      2580|   3482.768| 0.0000000|\n\n\n\nTable 1\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1: Effect of Sex on Satisfaction with Mass Transportation](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/plot-sexviews-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 2: Effect of SES  on Satisfaction with Mass Transportation](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/plot-sesviews-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 3: Effect of Political Views on Satisfaction with Mass Transportation](Lab-Logistic-Questions_2026_DianaKim_files/figure-html/plot-polviews-1.png){width=672}\n:::\n:::\n\n",
    "supporting": [
      "Lab-Logistic-Questions_2026_DianaKim_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}