{
  "hash": "e9304418c4351d2ad5ca89fc6c7a2685",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 3: Ordinal Regression\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Yeaju Diana Kim\"\ndate: today\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\nexecute: \n  message: false\n  warning: false\nengine: knitr\n---\n\n## Instructions\n\n-   If you are fitting a model, display the model output in a neatly formatted table. (The `tidy()` and `kable()` functions can help!)\n-   If you are creating a plot, use clear labels for all axes, titles, etc.\n-   Commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages.\n-   When you're done, we should be able to knit the final version of the QMD in your GitHub as an HTML.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(ordinal)\nlibrary(marginaleffects)\nlibrary(emmeans)\nlibrary(car)\nlibrary(ggeffects)\nlibrary(knitr)\n#install.packages('modelsummary')\nlibrary(modelsummary)\nlibrary(patchwork)\n#install.packages('gofcat')\nlibrary(gofcat)\nlibrary(sure)\nlibrary(MASS)\n\noptions(scipen = 999)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 1: Understanding Thresholds Through Simulation\n\n## The Setup\n\nA university has 10 instructors who are **cross-listed** — they each teach one course in the Psychology department and one in Computer Science. At the end of the semester, students in both departments rate these instructors on a 4-point scale: **Poor / Fair / Good / Excellent**.\n\nEach instructor has a latent (hidden) \"teaching effectiveness\" score that we never observe. We only see the ordinal rating. Now, **both departments evaluate the same instructors**, but their evaluation forms use **different descriptions** for the rating categories.\n\n**Psychology's form:**\n\n-   Poor = \"Did not meet basic expectations\"\n-   Fair = \"Meets minimum expectations\"\n-   Good = \"Consistently above average\"\n-   Excellent = \"Outstanding in all respects\"\n\n**Computer Science's form:**\n\n-   Poor = \"Did not meet basic expectations\"\n-   Fair = \"Meets minimum expectations\"\n-   Good = \"Solid and competent\"\n-   Excellent = \"Solid and competent, with minor distinction\"\n\nNotice that in CS, students have to split hairs between \"Good\" and \"Excellent\" as the descriptions barely differ. This compresses the top two categories together. Consequently almost everyone who would be \"Good\" in Psychology ends up rated \"Excellent\" in CS, not because the teaching improved, but because the **scale changed**.\n\nHere's the simulation code. **Read it carefully before running it.**\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nset.seed(504)\n\n# 10 cross-listed instructors with latent teaching effectiveness\ninstructors <- tibble(\n  id = 1:10,\n  effectiveness = rnorm(10, mean = 0, sd = 1.2)\n)\n\n# Each instructor rated by 20 students per department\nratings_latent <- instructors %>%\n  rowwise() %>%\n  mutate(latent = list(rnorm(20, mean = effectiveness, sd = 1))) %>%\n  unnest(latent) %>%\n  ungroup()\n\n# --- THREE THRESHOLDS PRODUCE FOUR CATEGORIES ---\n\n# Psychology: balanced scale\ntau_psych <- c(-1.0, 0.0, 1.0)\n\n# Computer Science: compressed top end\ntau_cs <- c(-1.0, 0.0, 0.3)\n\nratings <- ratings_latent %>%\n  mutate(\n    eval_psych = case_when(\n      latent <= tau_psych[1] ~ \"Poor\",\n      latent <= tau_psych[2] ~ \"Fair\",\n      latent <= tau_psych[3] ~ \"Good\",\n      TRUE                   ~ \"Excellent\"\n    ),\n    eval_psych = ordered(eval_psych, levels = c(\"Poor\", \"Fair\", \"Good\", \"Excellent\")),\n    \n    eval_cs = case_when(\n      latent <= tau_cs[1] ~ \"Poor\",\n      latent <= tau_cs[2] ~ \"Fair\",\n      latent <= tau_cs[3] ~ \"Good\",\n      TRUE                ~ \"Excellent\"\n    ),\n    eval_cs = ordered(eval_cs, levels = c(\"Poor\", \"Fair\", \"Good\", \"Excellent\"))\n  )\n```\n:::\n\n\n### Question 1.1: Visualize the latent distribution {.unnumbered}\n\nCreate a density plot of the latent scores with vertical dashed lines for Psychology's thresholds ($\\tau_1 = -1$, $\\tau_2 = 0$, $\\tau_3 = 1$). Label the four regions (Poor, Fair, Good, Excellent) on the plot.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Key geoms\"}\n`geom_density()` for the curve, `geom_vline(xintercept = ...)` for the thresholds (use `linetype = \"dashed\"`), and `annotate(\"text\", x = ..., y = ..., label = ...)` to place category labels in each region. You'll need one `annotate()` call per label.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ratings_latent, aes(x = latent)) +\n  geom_density() +\n  geom_vline(xintercept = c(-1, 0, 1),\n             linetype = \"dashed\",\n             color = \"red\") +\n  annotate(\"text\", x = -2, y = 0.2, label = \"Poor\") +\n  annotate(\"text\", x = -0.5, y = 0.2, label = \"Fair\") +\n  annotate(\"text\", x = 0.5, y = 0.2, label = \"Good\") +\n  annotate(\"text\", x = 2, y = 0.2, label = \"Excellent\") +\n  labs(title = \"Latent Teaching Effectiveness Distribution\",\n       x = \"Teaching Effectiveness\",\n       y = \"Density\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Question 1.2: Identical instructors, different scales {.unnumbered}\n\nCreate side-by-side stacked bar charts showing the observed rating distributions for Psychology and CS.\n\nThe instructors didn't change, so what did? What does this tell you about what thresholds control?\n\nHow the instructors are rated by the students changed. Different thresholds can cause different categorization based on how you rate the samples, even when latent variables are the same.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Data wrangling\"}\nFirst, create a frequency table for each department using `count()`, rename the rating column to a shared name like `category`, and add a `dept` label column. Then `bind_rows()` them together. Compute proportions with `mutate(prop = n / sum(n))` grouped by department. Plot with `geom_col(position = \"stack\")` mapping `x = dept`, `y = prop`, and `fill = category`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\npsych_table <- ratings %>%\n  count(eval_psych) %>%\n  rename(category = eval_psych) %>%\n  mutate(dept = \"Psychology\")\n\ncs_table <- ratings %>%\n  count(eval_cs) %>%\n  rename(category = eval_cs) %>%\n  mutate(dept = \"Computer Science\")\n\nboth_table <- bind_rows(psych_table, cs_table) %>%\n  group_by(dept) %>%\n  mutate(prop = n / sum(n)) %>%\n  ungroup()\n\nggplot(both_table, aes(x = dept, y = prop, fill = category)) +\n  geom_col(position = \"stack\") +\n  labs(title = \"Rating Distributions In Departments\",\n    x = \"Department\",\n    y = \"Proportion\",\n    fill = \"Rating\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n### Exercise 1.3: What does tau live on? {.unnumbered}\n\nThe thresholds $\\tau_1 = -1$, $\\tau_2 = 0$, $\\tau_3 = 1$ are on the latent \"teaching effectiveness\" scale — the continuous axis you generated but would never observe in real data. The model re-expresses these same cut points as **log-cumulative-odds** — a transformation of the latent scale that makes the math linear. Convert between them:\n\na)  Convert the Psychology Dept thresholds to cumulative probabilities using `plogis()`. What does each value mean?\n\nThresholds for cumulative probabilities of rating categories (e.g., good, excellent).\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: What does plogis() do?\"}\n`plogis()` is the inverse logit. It converts log-cumulative-odds back to a probability: $\\text{plogis}(\\tau) = \\frac{e^\\tau}{1 + e^\\tau} = P(Y \\leq k)$\n:::\n\nb)  Suppose you want a rating distribution where 10% are Poor, 30% Fair, 40% Good, and 20% Excellent. What thresholds would produce this? Use `qlogis()`.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: What does qlogis() do?\"}\n`qlogis()` is the logit function, which goes the other direction. Give it a cumulative probability and it returns the threshold: $\\text{qlogis}(p) = \\log\\frac{p}{1-p} = \\tau$\n:::\n\n::: panel-tabset\n## Your turn\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# (a) Thresholds to cumulative probabilities\nthresholds <- c(-1.0, 0.0, 1.0)\ncumul_probs <- plogis(thresholds)\ncumul_probs\n\n# Then get category-specific probabilities\ncat_probs <- diff(c(0, cumul_probs, 1))\ncat_probs\n\n# (b) Desired split to thresholds\ndesired_split <- c(0.10, 0.30, 0.40, 0.20)\ncumul_desired <- cumsum(desired_split[1:3])  # which elements?\ncumul_desired\nneeded_thresholds <- qlogis(cumul_desired)\nneeded_thresholds\n```\n:::\n\n\n## Expected output\n\n(a) Cumulative probs: 0.269, 0.500, 0.731 Category probs: 0.269, 0.231, 0.231, 0.269\n\n(b) Cumulative at cuts: 0.10, 0.40, 0.80 Required thresholds: -2.197, -0.405, 1.386\n:::\n\n------------------------------------------------------------------------\n\n# Part 2: Manual Calculation — From Counts to Log-Cumulative-Odds\n\nThe goal of this section is to **demystify model output**. When you later see `Poor|Fair = -1.23` in a `clm()` summary, you'll think: \"that's the log-cumulative-odds I already computed by hand.\"\n\n### Exercise 2.1: Build the table {.unnumbered}\n\nUsing Psychology Dept's ratings, compute the following for each category: the count, proportion, cumulative proportion, cumulative odds, and log-cumulative-odds.\n\nDisplay the result as a table using `kable()`.\n\n::: panel-tabset\n## Your turn\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhand_calc <- ratings %>%\n  count(eval_psych) %>% ##?\n  rename(category = eval_psych) %>%\n  mutate(\n    proportion     = n / sum(n),\n    cumul_proportion = cumsum(proportion),\n    cumul_odds       = cumul_proportion / (1 - cumul_proportion),\n    log_cumul_odds   = log(cumul_odds)\n  )\n\nhand_calc %>% kable(digits = 3)\n```\n:::\n\n\n## Hint: What's cumulative odds?\n\nCumulative odds = $\\frac{P(Y \\leq k)}{P(Y > k)} = \\frac{\\text{cum\\_proportion}}{1 - \\text{cum\\_proportion}}$\n\nThen take `log()` (natural log, not log10).\n\nThe last category (Excellent) will be `Inf`. This is because $P(Y \\leq \\text{Excellent}) = 1$, so the odds are $1/0 = \\infty$.\n:::\n\n### Question 2.2: Compare to model output {.unnumbered}\n\nFit an intercept-only ordinal model on the Psychology Dept data: `clm(eval_psych ~ 1, data = ratings)`.\n\nCompare the model's threshold estimates to your hand-calculated log-cumulative-odds. How do they compare, and what does this tell you about what the model is doing?\n\nThey're identical! The model is estimating cumulative probabilities and reporting log-cumulative odds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercept_only <- clm(eval_psych ~ 1, data = ratings)\nmodelsummary(intercept_only)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_r4d6ymkp6lrv9wf7zi8q = TinyTable.createTableFunctions(\"tinytable_r4d6ymkp6lrv9wf7zi8q\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '10', j: 2 } ], css_id: 'tinytable_css_ow1ucdoziimlktid7xa3',}, \n          { positions: [ { i: '6', j: 2 } ], css_id: 'tinytable_css_trzfjri3iqcbultujdqx',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 } ], css_id: 'tinytable_css_21hotigp4xrmnu48by4f',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_fukwg637ys3tuzzr03ri',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_saif1ld1ajkww78afxhl',}, \n          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_bzdd17r64hvbxhm36jkm',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 } ], css_id: 'tinytable_css_95rzquxcyj57wrgs6rpf',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_2whxqni2iz61sxrsqedo',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_r4d6ymkp6lrv9wf7zi8q.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_ow1ucdoziimlktid7xa3, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_ow1ucdoziimlktid7xa3 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_trzfjri3iqcbultujdqx, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_trzfjri3iqcbultujdqx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_21hotigp4xrmnu48by4f, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_21hotigp4xrmnu48by4f { text-align: center }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_fukwg637ys3tuzzr03ri, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_fukwg637ys3tuzzr03ri {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_saif1ld1ajkww78afxhl, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_saif1ld1ajkww78afxhl {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_bzdd17r64hvbxhm36jkm, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_bzdd17r64hvbxhm36jkm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_95rzquxcyj57wrgs6rpf, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_95rzquxcyj57wrgs6rpf { text-align: left }\n    #tinytable_r4d6ymkp6lrv9wf7zi8q td.tinytable_css_2whxqni2iz61sxrsqedo, #tinytable_r4d6ymkp6lrv9wf7zi8q th.tinytable_css_2whxqni2iz61sxrsqedo {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_r4d6ymkp6lrv9wf7zi8q\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Poor|Fair</td>\n                  <td data-row=\"1\" data-col=\"2\">-1.992</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.218)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Fair|Good</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.511</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.146)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Good|Excellent</td>\n                  <td data-row=\"5\" data-col=\"2\">0.824</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.154)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"7\" data-col=\"2\">200</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">537.9</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">547.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"10\" data-col=\"2\">2.71</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n### Question 2.3: Cumulative probability plot {.unnumbered}\n\nRun the code below. It visualizes the numbers you computed in Exercise 2.1, with gray bars showing cumulative probabilities and blue segments showing category-specific probabilities.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nfreq_table <- ratings %>%\n  count(eval_psych) %>%\n  rename(category = eval_psych) %>%\n  mutate(\n    prop = n / sum(n),\n    cumul_prop = cumsum(prop),\n    cumul_prop_lag = lag(cumul_prop, default = 0)\n  )\n\nggplot(freq_table) +\n  geom_col(aes(x = category, y = cumul_prop), \n           fill = \"gray70\", width = 0.5) +\n  geom_segment(aes(x = as.numeric(category) + 0.15, \n                   xend = as.numeric(category) + 0.15,\n                   y = cumul_prop_lag, yend = cumul_prop),\n               color = \"steelblue\", linewidth = 3) +\n  geom_text(aes(x = as.numeric(category) + 0.3,\n                y = (cumul_prop + cumul_prop_lag) / 2,\n                label = round(prop, 2)),\n            color = \"steelblue\", size = 5, fontface = \"bold\") +\n  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.25)) +\n  labs(\n    title = \"Cumulative vs. category-specific probabilities\",\n    subtitle = \"Gray = cumulative P(Y ≤ k)   Blue = category P(Y = k)\",\n    x = \"Rating\", y = \"Probability\"\n  ) +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nAnswer these questions:\n\nWhat do the gray bar and blue segment for \"Fair\" represent? Write them as probability statements.\n\nThe gray bar shows a cumulative probability of 'Fair' and below 'Fair' categories. There is 38% probability that the ratings will fall into 'Fair' or 'Poor' category. The blue bar, on the other hand, shows category-specific probability. There's 26% probability that the ratings fall into 'Fair' category alone.\n\n------------------------------------------------------------------------\n\n# Part 3: Conceptual Questions\n\n### Question 3.1 {.unnumbered}\n\nHow does the **cumulative logit** link function differ from the ordinary logit link used in binary logistic regression?\n\nThe cumulative logit is: $\\log\\frac{P(Y \\leq k)}{P(Y > k)}$\n\nFor an outcome with $K$ categories, how many equations does this produce? Answer in 2--3 sentences.\n\nIn binary logistic regression, the logit link models a single equation because there are only two categories. In a cumulative logit model, it models cumulative probabilities. For an outcome with k categories, it produced k-1 equations.\n\n### Question 3.2: Why not just use linear regression (aka metric models)? {.unnumbered}\n\nLinear regression, ANOVA, and t-tests are all metric models. Metric models assume the numbers you assign to categories have equal spacing and meaningful distances, where you're treating your scale like a ruler with evenly spaced tick marks.\n\nUsing the simulation data, code Psychology Dept ratings as numbers: Poor = 1, Fair = 2, Good = 3, Excellent = 4. Fit `lm(rating_numeric ~ effectiveness)`. Then recode as Poor = 1, Fair = 2, Good = 3, Excellent = 10. Fit the model again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nratings_1 <- ratings %>%\n  mutate(rating_numeric = as.numeric(eval_psych))\n\nmodel1 <- lm(rating_numeric ~ effectiveness, data = ratings_1)\nmodelsummary(model1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_v76dfocpkr5y6ui2r45f = TinyTable.createTableFunctions(\"tinytable_v76dfocpkr5y6ui2r45f\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_uqi084tcmof5ddnkphmi',}, \n          { positions: [ { i: '4', j: 2 } ], css_id: 'tinytable_css_ocbhm11a1rdn3nm0ccki',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_1ox34z60z862otnxjekd',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_fg6xs7pl690yv56ebcha',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_lmwzftjbet7kyyeydu21',}, \n          { positions: [ { i: '4', j: 1 } ], css_id: 'tinytable_css_84fnwulelpks6k3i6omb',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_be7seu4kufjgqqs5oijg',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_zb5mwhhyrkvzrwhwiox7',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_v76dfocpkr5y6ui2r45f.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_uqi084tcmof5ddnkphmi, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_uqi084tcmof5ddnkphmi {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_ocbhm11a1rdn3nm0ccki, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_ocbhm11a1rdn3nm0ccki {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_1ox34z60z862otnxjekd, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_1ox34z60z862otnxjekd { text-align: center }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_fg6xs7pl690yv56ebcha, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_fg6xs7pl690yv56ebcha {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_lmwzftjbet7kyyeydu21, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_lmwzftjbet7kyyeydu21 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_84fnwulelpks6k3i6omb, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_84fnwulelpks6k3i6omb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_be7seu4kufjgqqs5oijg, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_be7seu4kufjgqqs5oijg { text-align: left }\n    #tinytable_v76dfocpkr5y6ui2r45f td.tinytable_css_zb5mwhhyrkvzrwhwiox7, #tinytable_v76dfocpkr5y6ui2r45f th.tinytable_css_zb5mwhhyrkvzrwhwiox7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_v76dfocpkr5y6ui2r45f\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"1\" data-col=\"2\">2.562</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.064)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">effectiveness</td>\n                  <td data-row=\"3\" data-col=\"2\">0.452</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.047)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"5\" data-col=\"2\">200</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\">R2</td>\n                  <td data-row=\"6\" data-col=\"2\">0.321</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">R2 Adj.</td>\n                  <td data-row=\"7\" data-col=\"2\">0.318</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\">AIC</td>\n                  <td data-row=\"8\" data-col=\"2\">496.8</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">BIC</td>\n                  <td data-row=\"9\" data-col=\"2\">506.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">Log.Lik.</td>\n                  <td data-row=\"10\" data-col=\"2\">-245.421</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">F</td>\n                  <td data-row=\"11\" data-col=\"2\">93.728</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"12\" data-col=\"2\">0.83</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\ncoef(model1)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neffectiveness \n    0.4517783 \n```\n\n\n:::\n\n```{.r .cell-code}\nratings_2 <- ratings %>%\n  mutate(rating_numeric = dplyr::recode(eval_psych,\n                                 \"Poor\" = 1,\n                                 \"Fair\" = 2,\n                                 \"Good\" = 3,\n                                 \"Excellent\" = 10))\n\nmodel2 <- lm(rating_numeric ~ effectiveness, data = ratings_2)\ncoef(model2)[2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neffectiveness \n     1.705881 \n```\n\n\n:::\n:::\n\n\nReport both slopes. In one sentence, explain why they differ and what this reveals about metric models.\n\nThe slope of the first model (1,2,3,4) is 0.452 while the second model (1,2,3,10)'s slope is 1.706. Changing the numeric scales can affect the interpretation of ordinal outcomes.\n\n------------------------------------------------------------------------\n\n# Part 4: Modeling the GBBO Data\n\nThe data comes from the Great British Bake Off (GBBO). In each episode, bakers face a \"technical challenge\" where they receive a recipe with minimal instructions and are judged blind. The judges rank every baker from best to worst.\n\nWe will focus on the **top 3 finishers**. Rank is ordinal, as 1st is better than 2nd and 2nd is better than 3rd, but we cannot say the gap between 1st and 2nd equals the gap between 2nd and 3rd. This is the kind of data that ordinal regression is suited for.\n\nDo Gender and Age predict how bakers rank in the technical?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngbbo <- read_csv(\"https://raw.githubusercontent.com/suyoghc/PSY-504_Spring-2025/refs/heads/main/Ordinal%20Regression/data/GBBO.csv\")\n```\n:::\n\n\n### Exercise 4.1: Prepare the data {.unnumbered}\n\nFilter to only top 3 ranks. Convert `Rank` to an ordered factor (1 = best, so think about the ordering). Convert `Gender` to a factor.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Factor ordering\"}\nThe column is called `Technical Rank` (with a space), so rename it first with `rename(Rank = \\`Technical Rank\\`)\\`.\n\nWhat does \"higher\" mean here? Rank 1 is best. You need to decide whether your ordered factor goes 1 \\< 2 \\< 3 (best to worst) or 3 \\< 2 \\< 1 (worst to best). The model interprets higher factor levels as \"more\" of the outcome. Think about what direction makes sense for your interpretation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\ngb <- gbbo %>%\n  rename(Rank = `Technical Rank`) %>%   # fix column name\n  filter(Rank %in% c(1, 2, 3)) %>%\n  drop_na() %>%\n  mutate(\n    Rank = ordered(Rank, levels = c(3, 2, 1)),  # 3 < 2 < 1, so \"higher\" = better rank\n    Gender = factor(Gender)\n  )\n\nhead(gb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  Gender   Age Rank \n  <fct>  <dbl> <ord>\n1 F         30 2    \n2 M         31 3    \n3 M         24 1    \n4 F         45 2    \n5 M         25 1    \n6 F         37 3    \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ntable(gb$Rank)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  3   2   1 \n102 104 103 \n```\n\n\n:::\n:::\n\n\n### Question 4.2: Explore {.unnumbered}\n\nCreate two visualizations:\n\na)  A bar chart showing the proportion of bakers in each rank by Gender.\nb)  A bar chart showing the proportion of bakers in each rank by Age (bin Age into groups using `cut()`).\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Proportional bar charts\"}\n`geom_bar(position = \"fill\")` gives proportions instead of counts. Map `x = Gender` (or your age groups) and `fill = Rank`. For part (b), create age bins with something like `cut(Age, breaks = c(15, 25, 35, 45, 55, 75))` inside a `mutate()` before plotting.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#a\nggplot(gb, aes(x = Gender, fill = Rank)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(\n    title = \"Proportion by Gender\",\n    x = \"Gender\",\n    y = \"Proportion\"\n  ) +\n  theme_minimal(base_size = 14)\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#b\ngb_age <- gb %>%\n  mutate(AgeGroup = cut(Age, breaks = c(15, 25, 35, 45, 55, 75)))\n\nggplot(gb_age, aes(x = AgeGroup, fill = Rank)) +\n  geom_bar(position = \"fill\") +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(\n    title = \"Proportion by Age group\",\n    x = \"Age group\",\n    y = \"Proportion\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n:::\n\n\n### Question 4.3: Build models {.unnumbered}\n\nFit the following models using `clm()` from the `ordinal` package:\n\n-   **Model 0:** Intercept only — `Rank ~ 1`\n-   **Model 1:** `Rank ~ Gender`\n-   **Model 2:** `Rank ~ Gender + Age`\n-   **Model 3:** `Rank ~ Gender * Age`\n\nFor Model 2:\n\na)  Report the threshold estimates. What do they represent?\n\n    3\\|2 is -0.6005 (log-odds of rank being third place) and 2\\|1 is 0.8048 (log-odds of rank being third or second place).\n\nb)  Exponentiate the coefficients. Interpret the odds ratio for `Age` in one sentence.\n\n    When age increases 1 year, the odds of being in a higher rank increase 1.0056%(?).\n\nc)  Using Model 2, what is the predicted probability of Rank 1 for a 30-year-old female? Use `predictions()` from the `marginaleffects` package.\n\n    34.6%. Have we learned how to use this function..?\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Interpreting thresholds\"}\nThe thresholds are the log-cumulative-odds of $P(Y \\leq k)$ when all predictors are zero. They define the baseline distribution — where the cuts fall before any predictor shifts the distribution.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nm0 <- clm(Rank ~ 1, data = gb)\nm1 <- clm(Rank ~ Gender, data = gb)\nm2 <- clm(Rank ~ Gender + Age, data = gb)\nm3 <- clm(Rank ~ Gender * Age, data = gb)\n\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: Rank ~ Gender + Age\ndata:    gb\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  309  -338.86 685.72 3(0)  1.05e-10 2.9e+04\n\nCoefficients:\n         Estimate Std. Error z value Pr(>|z|)\nGenderM -0.190952   0.210607  -0.907    0.365\nAge      0.005618   0.009100   0.617    0.537\n\nThreshold coefficients:\n    Estimate Std. Error z value\n3|2  -0.6005     0.3493  -1.719\n2|1   0.8048     0.3507   2.295\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nexp(coef(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      3|2       2|1   GenderM       Age \n0.5485392 2.2362995 0.8261722 1.0056339 \n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\npredictions(m2, newdata = data.frame(Gender = \"F\", Age = 30))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Group Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 % Gender Age\n     3    0.317     0.0345  9.17   <0.001  64.1 0.249  0.384      F  30\n     2    0.337     0.0270 12.51   <0.001 116.9 0.284  0.390      F  30\n     1    0.346     0.0357  9.70   <0.001  71.5 0.276  0.416      F  30\n\nType:  prob \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 5: Model Comparison\n\n### Question 5.1 {.unnumbered}\n\nUse `anova()` to compare Model 2 (no interaction) with Model 3 (interaction). Is the interaction warranted?\n\nYes. Model 3 is significantly better than Model 2.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: What is anova() doing here?\"}\nEach model's parameters are estimated by maximizing its likelihood function, finding the parameter values that make the observed data as probable as possible. `anova()` performs a likelihood ratio test. It computes:\n\n$$LR = -2 \\log\\left(\\frac{L_{\\text{simple}}}{L_{\\text{complex}}}\\right)$$\n\nThis statistic follows a chi-square distribution. A significant p-value means the complex model fits meaningfully better, so the interaction is worth keeping. A non-significant p-value means the extra parameters aren't earning their keep, so you should prefer the simpler model.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(m2, m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio tests of cumulative link models:\n \n   formula:            link: threshold:\nm2 Rank ~ Gender + Age logit flexible  \nm3 Rank ~ Gender * Age logit flexible  \n\n   no.par    AIC  logLik LR.stat df Pr(>Chisq)  \nm2      4 685.72 -338.86                        \nm3      5 683.28 -336.64   4.437  1    0.03517 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Question 5.2 {.unnumbered}\n\nCreate a publication-quality comparison table of all four models using `modelsummary()`. Exponentiate the coefficients so they display as odds ratios.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\nPut all four models in a named list: `list(\"Intercept only\" = m0, \"Gender\" = m1, \"Gender + Age\" = m2, \"Gender × Age\" = m3)`. Pass it to `modelsummary()` with `exponentiate = TRUE` to display odds ratios and `stars = TRUE` to add significance stars.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodels <- list(\"Intercept only\" = m0, \"Gender\" = m1, \"Gender + Age\" = m2, \"Gender × Age\" = m3)\n\nmodelsummary(models, exponentiate = TRUE, stars = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_fhghm5xc6hurxmkr6ryh = TinyTable.createTableFunctions(\"tinytable_fhghm5xc6hurxmkr6ryh\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 }, { i: '14', j: 4 }, { i: '14', j: 5 } ], css_id: 'tinytable_css_2uyug210it1p9k37obmt',}, \n          { positions: [ { i: '10', j: 2 }, { i: '10', j: 3 }, { i: '10', j: 4 }, { i: '10', j: 5 } ], css_id: 'tinytable_css_1iadn6832mv1papg61j1',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '1', j: 5 }, { i: '2', j: 5 }, { i: '3', j: 5 }, { i: '4', j: 5 }, { i: '5', j: 5 }, { i: '6', j: 5 }, { i: '7', j: 5 }, { i: '8', j: 5 }, { i: '9', j: 5 }, { i: '11', j: 5 }, { i: '12', j: 5 }, { i: '13', j: 5 } ], css_id: 'tinytable_css_pinqyypc1o99we7hv77h',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 }, { i: '0', j: 5 } ], css_id: 'tinytable_css_gc06o302sw65dm5uhnwx',}, \n          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_kzwi65oqv3vudx2iyzj4',}, \n          { positions: [ { i: '10', j: 1 } ], css_id: 'tinytable_css_leloui9grq6toenmbimc',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 } ], css_id: 'tinytable_css_n0yuwarpoke4prjp9mhm',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_wsac5uk7ywhy067uu6s5',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_fhghm5xc6hurxmkr6ryh.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_2uyug210it1p9k37obmt, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_2uyug210it1p9k37obmt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_1iadn6832mv1papg61j1, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_1iadn6832mv1papg61j1 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_pinqyypc1o99we7hv77h, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_pinqyypc1o99we7hv77h { text-align: center }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_gc06o302sw65dm5uhnwx, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_gc06o302sw65dm5uhnwx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_kzwi65oqv3vudx2iyzj4, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_kzwi65oqv3vudx2iyzj4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_leloui9grq6toenmbimc, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_leloui9grq6toenmbimc {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_n0yuwarpoke4prjp9mhm, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_n0yuwarpoke4prjp9mhm { text-align: left }\n    #tinytable_fhghm5xc6hurxmkr6ryh td.tinytable_css_wsac5uk7ywhy067uu6s5, #tinytable_fhghm5xc6hurxmkr6ryh th.tinytable_css_wsac5uk7ywhy067uu6s5 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_fhghm5xc6hurxmkr6ryh\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Intercept only</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Gender</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Gender + Age</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"5\">Gender × Age</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='5'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">3|2</td>\n                  <td data-row=\"1\" data-col=\"2\">0.493***</td>\n                  <td data-row=\"1\" data-col=\"3\">0.452***</td>\n                  <td data-row=\"1\" data-col=\"4\">0.549+</td>\n                  <td data-row=\"1\" data-col=\"5\">0.995</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.060)</td>\n                  <td data-row=\"2\" data-col=\"3\">(0.070)</td>\n                  <td data-row=\"2\" data-col=\"4\">(0.192)</td>\n                  <td data-row=\"2\" data-col=\"5\">(0.450)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">2|1</td>\n                  <td data-row=\"3\" data-col=\"2\">2.000***</td>\n                  <td data-row=\"3\" data-col=\"3\">1.840***</td>\n                  <td data-row=\"3\" data-col=\"4\">2.236*</td>\n                  <td data-row=\"3\" data-col=\"5\">4.123**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.241)</td>\n                  <td data-row=\"4\" data-col=\"3\">(0.279)</td>\n                  <td data-row=\"4\" data-col=\"4\">(0.784)</td>\n                  <td data-row=\"4\" data-col=\"5\">(1.895)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">GenderM</td>\n                  <td data-row=\"5\" data-col=\"2\"></td>\n                  <td data-row=\"5\" data-col=\"3\">0.826</td>\n                  <td data-row=\"5\" data-col=\"4\">0.826</td>\n                  <td data-row=\"5\" data-col=\"5\">3.157+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\"></td>\n                  <td data-row=\"6\" data-col=\"3\">(0.174)</td>\n                  <td data-row=\"6\" data-col=\"4\">(0.174)</td>\n                  <td data-row=\"6\" data-col=\"5\">(2.124)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Age</td>\n                  <td data-row=\"7\" data-col=\"2\"></td>\n                  <td data-row=\"7\" data-col=\"3\"></td>\n                  <td data-row=\"7\" data-col=\"4\">1.006</td>\n                  <td data-row=\"7\" data-col=\"5\">1.023+</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\"></td>\n                  <td data-row=\"8\" data-col=\"3\"></td>\n                  <td data-row=\"8\" data-col=\"4\">(0.009)</td>\n                  <td data-row=\"8\" data-col=\"5\">(0.013)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">GenderM × Age</td>\n                  <td data-row=\"9\" data-col=\"2\"></td>\n                  <td data-row=\"9\" data-col=\"3\"></td>\n                  <td data-row=\"9\" data-col=\"4\"></td>\n                  <td data-row=\"9\" data-col=\"5\">0.962*</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\"></td>\n                  <td data-row=\"10\" data-col=\"3\"></td>\n                  <td data-row=\"10\" data-col=\"4\"></td>\n                  <td data-row=\"10\" data-col=\"5\">(0.018)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"11\" data-col=\"2\">309</td>\n                  <td data-row=\"11\" data-col=\"3\">309</td>\n                  <td data-row=\"11\" data-col=\"4\">309</td>\n                  <td data-row=\"11\" data-col=\"5\">309</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">AIC</td>\n                  <td data-row=\"12\" data-col=\"2\">682.9</td>\n                  <td data-row=\"12\" data-col=\"3\">684.1</td>\n                  <td data-row=\"12\" data-col=\"4\">685.7</td>\n                  <td data-row=\"12\" data-col=\"5\">683.3</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">BIC</td>\n                  <td data-row=\"13\" data-col=\"2\">690.4</td>\n                  <td data-row=\"13\" data-col=\"3\">695.3</td>\n                  <td data-row=\"13\" data-col=\"4\">700.7</td>\n                  <td data-row=\"13\" data-col=\"5\">702.0</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"14\" data-col=\"2\">1.86</td>\n                  <td data-row=\"14\" data-col=\"3\">1.86</td>\n                  <td data-row=\"14\" data-col=\"4\">1.86</td>\n                  <td data-row=\"14\" data-col=\"5\">1.85</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 6: Predicted Probabilities\n\n## Mini-tutorial: `marginaleffects::predictions()`\n\nThe `predictions()` function computes predicted probabilities for specific covariate profiles. Here's a worked example:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Predicted probabilities for a 30-year-old female\npredictions(m2, \n            newdata = datagrid(Gender = \"F\", Age = 30),\n            type = \"prob\") %>%\n  kable(digits = 3, caption = \"Predicted P(Rank) for a 30-year-old female\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Predicted P(Rank) for a 30-year-old female\n\n| rowid|group | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|Gender | Age|Rank |\n|-----:|:-----|--------:|---------:|---------:|-------:|-------:|--------:|---------:|:------|---:|:----|\n|     1|3     |    0.317|     0.035|     9.166|       0|  64.148|    0.249|     0.384|F      |  30|2    |\n|     1|2     |    0.337|     0.027|    12.511|       0| 116.898|    0.284|     0.390|F      |  30|2    |\n|     1|1     |    0.346|     0.036|     9.703|       0|  71.539|    0.276|     0.416|F      |  30|2    |\n\n\n:::\n:::\n\n\n### Question 6.1 {.unnumbered}\n\nCompare the predicted probabilities for a 25-year-old female vs. a 25-year-old male. Which gender has a higher predicted probability of Rank 1?\n\n34% for a 25-year-old female and 29.8% for a 25-year-old male. Higher for a female!\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(m2, newdata = data.frame(Gender = \"F\", Age = 25))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Group Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 % Gender Age\n     3    0.323     0.0386  8.36   <0.001  53.8 0.247  0.399      F  25\n     2    0.337     0.0270 12.52   <0.001 117.0 0.285  0.390      F  25\n     1    0.340     0.0394  8.62   <0.001  57.1 0.263  0.417      F  25\n\nType:  prob \n```\n\n\n:::\n\n```{.r .cell-code}\npredictions(m2, newdata = data.frame(Gender = \"M\", Age = 25))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Group Estimate Std. Error     z Pr(>|z|)     S 2.5 % 97.5 % Gender Age\n     3    0.366     0.0436  8.39   <0.001  54.2 0.280  0.451      M  25\n     2    0.336     0.0270 12.43   <0.001 115.3 0.283  0.389      M  25\n     1    0.298     0.0402  7.43   <0.001  43.0 0.220  0.377      M  25\n\nType:  prob \n```\n\n\n:::\n:::\n\n\n### Exercise 6.2: Verify by hand {.unnumbered}\n\nCompute the predicted probability of Rank 3 for a 25-year-old female using the formula:\n\n$$P(Y \\leq k) = \\text{plogis}(\\alpha_k - \\beta_1 X_1 - \\beta_2 X_2)$$\n\nUse the threshold and coefficient values from `coef(m2)`. Confirm that your manually calculated value matches the model output.\n\nYes! Both 32.3%.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: The subtraction\"}\nRemember the model uses subtraction: $\\eta = \\alpha_k - \\beta X$. So it's `plogis(threshold - (beta_gender * 0 + beta_age * 25))`. Gender = 0 if the reference level is female.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: Rank ~ Gender + Age\ndata:    gb\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  309  -338.86 685.72 3(0)  1.05e-10 2.9e+04\n\nCoefficients:\n         Estimate Std. Error z value Pr(>|z|)\nGenderM -0.190952   0.210607  -0.907    0.365\nAge      0.005618   0.009100   0.617    0.537\n\nThreshold coefficients:\n    Estimate Std. Error z value\n3|2  -0.6005     0.3493  -1.719\n2|1   0.8048     0.3507   2.295\n```\n\n\n:::\n\n```{.r .cell-code}\nthreshold <- coef(m2)[\"3|2\"]\nthreshold\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       3|2 \n-0.6004965 \n```\n\n\n:::\n\n```{.r .cell-code}\nbeta_gender <- coef(m2)[\"GenderM\"]\nbeta_gender\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  GenderM \n-0.190952 \n```\n\n\n:::\n\n```{.r .cell-code}\nbeta_age <- coef(m2)[\"Age\"]\nbeta_age\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Age \n0.005618057 \n```\n\n\n:::\n\n```{.r .cell-code}\nplogis(threshold - (beta_gender * 0 + beta_age * 25))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      3|2 \n0.3227969 \n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 7: Marginal Effects\n\n## Mini-tutorial: `avg_comparisons()`\n\nMarginal effects answer the question: \"How much does the predicted probability of each category change when I shift one predictor, holding everything else constant?\"\n\nIn OLS, the slope *is* the marginal effect, because one unit of X always produces β units of change in Y. That's because the model predicts Y directly, with no transformation.\n\nIn any GLM with a nonlinear link (logistic regression, Poisson, ordinal, ...), the slope and the marginal effect come apart. The model estimates β on a transformed scale (log-odds, log-counts), but the relationship between that scale and probability is a curve, not a line. The same β of 0.5 might shift a probability from 0.10 to 0.15 (a 5-point change) near the tails, but from 0.45 to 0.57 (a 12-point change) near the middle. The coefficient is identical in both cases, but its impact differs because the curve is steepest in the center and flat at the extremes.\n\nFor ordinal regression specifically, there's an added wrinkle: the marginal effect is different for **each category**. Age might increase P(Rank 1) while simultaneously decreasing P(Rank 3), because probability must redistribute.\n\n`avg_comparisons()` handles all of this. It computes the probability-scale effect at every observation, then averages — giving you one summary per category in percentage points.\n\nHere's a worked example interpreting the effect of Gender:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\navg_comparisons(m2, variables = \"Gender\", type = \"prob\") %>%\n  kable(digits = 3, caption = \"Average marginal effect of Gender on each rank\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average marginal effect of Gender on each rank\n\n|term   |group |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:------|:-----|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|Gender |3     |M - F    |    0.042|     0.047|     0.904|   0.366|   1.451|   -0.049|     0.134|\n|Gender |2     |M - F    |    0.000|     0.003|    -0.035|   0.972|   0.040|   -0.006|     0.006|\n|Gender |1     |M - F    |   -0.042|     0.046|    -0.911|   0.362|   1.464|   -0.133|     0.049|\n\n\n:::\n:::\n\n\n**Interpretation example:** *\"Switching from female to male changes the probability of achieving Rank 1 by -4.2 percentage points, on average. This means males are less likely to finish first in the technical challenge than females.\"*\n\n### Question 7.1 {.unnumbered}\n\nCompute the average marginal effect of `Age` on each rank category using `avg_comparisons()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(m2, variables = \"Age\", type = \"prob\") %>%\n  kable(digits = 3, caption = \"Average marginal effect of Age on each rank\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average marginal effect of Age on each rank\n\n|term |group |contrast | estimate| std.error| statistic| p.value| s.value| conf.low| conf.high|\n|:----|:-----|:--------|--------:|---------:|---------:|-------:|-------:|--------:|---------:|\n|Age  |3     |+1       |   -0.001|     0.002|    -0.619|   0.536|   0.899|   -0.005|     0.003|\n|Age  |2     |+1       |    0.000|     0.000|    -0.100|   0.921|   0.119|    0.000|     0.000|\n|Age  |1     |+1       |    0.001|     0.002|     0.618|   0.537|   0.898|   -0.003|     0.005|\n\n\n:::\n:::\n\n\nTranslate the marginal effect for **Rank 1** into a sentence that a non-statistician would understand.\n\nGetting one year older changes the probability of achieving Rank 1 by 0.1 percentage points, on average. You become 0.1 percentage point more likely achieve rank 1 as you get 1 year older.\n\n------------------------------------------------------------------------\n\n# Part 8: Estimated Marginal Means\n\n## Mini-tutorial: `emmeans()`\n\n`emmeans()` computes estimated marginal means, which are the model's best guess for each group, averaged across other predictors. For ordinal models, we need `mode = \"prob\"` to get predicted probabilities.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nemmeans(m2, ~ Gender, mode = \"prob\") %>%\n  kable(digits = 3, caption = \"Estimated probabilities by Gender\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Estimated probabilities by Gender\n\n|Gender |  prob| SE|  df| asymp.LCL| asymp.UCL|\n|:------|-----:|--:|---:|---------:|---------:|\n|F      | 0.333|  0| Inf|     0.333|     0.333|\n|M      | 0.333|  0| Inf|     0.333|     0.333|\n\n\n:::\n:::\n\n\n### Question 8.1 {.unnumbered}\n\nUse `ggemmeans()` from the `ggeffects` package to plot predicted probabilities across Age, colored by Gender. The output should show how the probability of each rank category changes with age for each gender.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\n`ggemmeans(m2, terms = c(\"Age\", \"Gender\"))` returns a data frame of predicted probabilities. You can pipe it directly to `plot()` for a quick visualization, or use the returned data with `ggplot()` for more control over the appearance.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_emmeans <- ggemmeans(m2, terms = c(\"Age[all]\", \"Gender\"))\n\nplot(m2_emmeans)\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 9: Assumption Checking\n\n### Question 9.1: Proportional odds {.unnumbered}\n\nThe proportional odds assumption says the effect of a predictor is the same at every threshold — the slope doesn't change depending on where you split the outcome.\n\nUse the Brant test to check this assumption. State your conclusion.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Which package and model object?\"}\n`brant.test()` from the `gofcat` package requires a `polr()` model, not a `clm()` model. Refit using `MASS::polr()` first.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nm2_polr <- polr(Rank ~ Gender + Age, data = gb)\nbrant.test(m2_polr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBrant Test:\n           chi-sq   df   pr(>chi)\nOmnibus     0.367    2       0.83\nGenderM     0.296    1       0.59\nAge         0.075    1       0.78\n\nH0: Proportional odds assumption holds\n```\n\n\n:::\n:::\n\n\nAll p values are not significant, so the assumption appears to hold.\n\n### Question 9.2: Surrogate residuals {.unnumbered}\n\nUse the `sure` package to create a QQ plot of surrogate residuals. Does the latent normality assumption appear to hold?\n\nIt looks like a straight line, which means that the latent normality assumption holds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?sure\nlibrary(sure)\nresiduals <- resids(m2, method = \"latent\")\nclass(residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"numeric\" \"resid\"  \n```\n\n\n:::\n\n```{.r .cell-code}\n#sure::autoplot(residuals)   ## this doesn't work??\n\n#dev.new()\nqqnorm(residuals)\n```\n\n::: {.cell-output-display}\n![](Lab3_ordinal-regression_DianaKim_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#qqline(residuals, col = \"red\", lwd = 2)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 10: Write-Up\n\n### Question 10.1 {.unnumbered}\n\nWrite a **1-paragraph results section** for your final model. Your paragraph must include:\n\n-   The model type and link function\n-   Sample size\n-   The proportional odds test result\n-   At least one key coefficient reported as an odds ratio with a confidence interval\n-   At least one marginal effect translated into probability terms\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(m2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_74hmv4cdhcgeslxl87rg = TinyTable.createTableFunctions(\"tinytable_74hmv4cdhcgeslxl87rg\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_6pelooxr6iyhlyp5c365',}, \n          { positions: [ { i: '8', j: 2 } ], css_id: 'tinytable_css_27d7kw5vxi4jucvap3wt',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 } ], css_id: 'tinytable_css_cgei65mo8gdnsi4fymvk',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_i1xnk3qlwetc2zkqo54s',}, \n          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_moh55ld4zircqsncm2l6',}, \n          { positions: [ { i: '8', j: 1 } ], css_id: 'tinytable_css_b1jnc6ks1vsxdsc0ccdx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 } ], css_id: 'tinytable_css_8zu6ulg0s3tmkjc5i91r',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_u3id6zbke6ik6of1q6c6',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_74hmv4cdhcgeslxl87rg.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_6pelooxr6iyhlyp5c365, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_6pelooxr6iyhlyp5c365 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_27d7kw5vxi4jucvap3wt, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_27d7kw5vxi4jucvap3wt {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_cgei65mo8gdnsi4fymvk, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_cgei65mo8gdnsi4fymvk { text-align: center }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_i1xnk3qlwetc2zkqo54s, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_i1xnk3qlwetc2zkqo54s {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_moh55ld4zircqsncm2l6, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_moh55ld4zircqsncm2l6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_b1jnc6ks1vsxdsc0ccdx, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_b1jnc6ks1vsxdsc0ccdx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_8zu6ulg0s3tmkjc5i91r, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_8zu6ulg0s3tmkjc5i91r { text-align: left }\n    #tinytable_74hmv4cdhcgeslxl87rg td.tinytable_css_u3id6zbke6ik6of1q6c6, #tinytable_74hmv4cdhcgeslxl87rg th.tinytable_css_u3id6zbke6ik6of1q6c6 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_74hmv4cdhcgeslxl87rg\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">(1)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">3|2</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.600</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.349)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">2|1</td>\n                  <td data-row=\"3\" data-col=\"2\">0.805</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.351)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">GenderM</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.191</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.211)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Age</td>\n                  <td data-row=\"7\" data-col=\"2\">0.006</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.009)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"9\" data-col=\"2\">309</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\">AIC</td>\n                  <td data-row=\"10\" data-col=\"2\">685.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">BIC</td>\n                  <td data-row=\"11\" data-col=\"2\">700.7</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\">RMSE</td>\n                  <td data-row=\"12\" data-col=\"2\">1.86</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: Rank ~ Gender + Age\ndata:    gb\n\n link  threshold nobs logLik  AIC    niter max.grad cond.H \n logit flexible  309  -338.86 685.72 3(0)  1.05e-10 2.9e+04\n\nCoefficients:\n         Estimate Std. Error z value Pr(>|z|)\nGenderM -0.190952   0.210607  -0.907    0.365\nAge      0.005618   0.009100   0.617    0.537\n\nThreshold coefficients:\n    Estimate Std. Error z value\n3|2  -0.6005     0.3493  -1.719\n2|1   0.8048     0.3507   2.295\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         3|2          2|1      GenderM          Age \n-0.600496501  0.804822497 -0.190952025  0.005618057 \n```\n\n\n:::\n\n```{.r .cell-code}\nexp(coef(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      3|2       2|1   GenderM       Age \n0.5485392 2.2362995 0.8261722 1.0056339 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint.default(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n              2.5 %     97.5 %\n3|2     -1.28511933 0.08412633\n2|1      0.11739311 1.49225189\nGenderM -0.60373424 0.22183019\nAge     -0.01221723 0.02345335\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(confint.default(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5 %   97.5 %\n3|2     0.2766176 1.087766\n2|1     1.1245614 4.447099\nGenderM 0.5467661 1.248359\nAge     0.9878571 1.023731\n```\n\n\n:::\n:::\n\n\nWe used a cumulative logit model (proportional odds) to predict technical rank (1st, 2nd, 3rd) from gender and age (N = 309). A Brant test supported the proportional odds assumption (χ² = 0.367, p = 0.83). Gender was not a significant predictor of rank (OR = 0.826, 95% CI \\[0.55, 1.25\\], p = 0.365). Each additional year of age was associated with a decrease in the odds of achieving a better rank (OR = 1.001, 95% CI \\[0.99, 1.02\\]). In terms of predicted probabilities, switching from female to male decreased the probability of achieving rank 1 by approximately 4.2 percentage points.\n\n#Age also not significant??\n\n------------------------------------------------------------------------\n\n# Bonus: Probit vs. Logit\n\n### Question B.1 (optional) {.unnumbered}\n\nRefit Model 2 using a probit link: `clm(Rank ~ Gender + Age, data = gb, link = \"probit\")`.\n\nCompare the coefficients to the logit version. Are the numbers different? Are the substantive conclusions different? In 2-3 sentences, explain why the numbers differ but the story stays the same.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2_probit <- clm(Rank ~ Gender + Age, data = gb, link = \"probit\")\nsummary(m2_probit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformula: Rank ~ Gender + Age\ndata:    gb\n\n link   threshold nobs logLik  AIC    niter max.grad cond.H \n probit flexible  309  -338.87 685.74 5(0)  7.71e-12 2.9e+04\n\nCoefficients:\n         Estimate Std. Error z value Pr(>|z|)\nGenderM -0.115742   0.128633  -0.900    0.368\nAge      0.003280   0.005483   0.598    0.550\n\nThreshold coefficients:\n    Estimate Std. Error z value\n3|2  -0.3785     0.2114  -1.790\n2|1   0.4939     0.2118   2.331\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Lab3_ordinal-regression_DianaKim_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}