{
  "hash": "8126516786de904f84d8a9681e381425",
  "result": {
    "engine": "knitr",
    "markdown": "---\n    title: \"Lab 4 - Multinomial Regression\"\n    author: \"Yeaju Diana Kim\"\n    date: \"2026-03-07\"\n    date-modified: today\n    format:\n      html:\n        self-contained: true\n        anchor-sections: true\n        code-tools: true\n        code-fold: true\n        fig-width: 8\n        fig-height: 4\n        code-block-bg: \"#f1f3f5\"\n        code-block-border-left: \"#31BAE9\"\n        mainfont: Source Sans Pro\n        theme:\n          - journal\n          - custom.scss\n        toc: true\n        toc-depth: 3\n        toc-location: left\n        captions: true\n        cap-location: margin\n        table-captions: true\n        tbl-cap-location: margin\n        reference-location: margin\n      pdf:\n        pdf-engine: lualatex\n        toc: false\n        number-sections: true\n        number-depth: 2\n        top-level-division: section\n        reference-location: document\n        listings: false\n        header-includes:\n          \\usepackage{marginnote, here, relsize, needspace, setspace}\n          \\def\\it{\\emph}\n\n    comments:\n      hypothesis: false\n\n    execute:\n      warning: false\n      message: false\n---\n\n**Lab Goal:** Predict voting frequency using demographic variables\\\n**Data source:** FiveThirtyEight \"Why Many Americans Don't Vote\" survey\\\n**Method:** Multinomial logistic regression\n\n## Instructions\n\n-   If you are fitting a model, display the model output in a neatly formatted table. (The `tidy()` and `kable()` functions can help!)\n-   If you are creating a plot, use clear labels for all axes, titles, etc.\n-   Commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages.\n-   When you're done, we should be able to knit the final version of the QMD in your GitHub as an HTML.\n\n::: callout-tip\n## Workflow tip\n\nWork through the lab by running chunks **one at a time** in RStudio (Cmd/Ctrl + Enter), not by rendering the whole document. Render only at the end, once all your code is working.\n\nThis is how most R users actually work -- you'd write a line, run it, check the output, and iterate. Rendering is for producing the final document. When you render, Quarto starts a fresh R session and runs every chunk top-to-bottom, so if anything is incomplete, everything downstream breaks. When you work interactively using chunks, your environment builds up as you go, so you always have your objects available to inspect and troubleshoot.\n\nThe **\"Run All Chunks Above\"** button (downward arrow with a bar, next to the green play button in each chunk) is another useful tool. It re-runs everything from the top of the document up to your current chunk, so all your objects are up to date before you start working on the next question.\n:::\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(nnet)\nlibrary(car)\nlibrary(tidyverse)\nlibrary(emmeans)\nlibrary(ggeffects)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(broom)\nlibrary(parameters)\nlibrary(easystats)\nlibrary(viridis)\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 1: Data Preparation\n\n## The Data\n\nThe data for this assignment comes from an online Ipsos survey that was conducted for the FiveThirtyEight article [\"Why Many Americans Don't Vote\"](https://projects.fivethirtyeight.com/non-voters-poll-2020-election/). If you'd like, you can read more about the survey design and respondents in the README of the [GitHub repo](https://github.com/fivethirtyeight/data/tree/master/non-voters) for the data, but all the necessary information is explained below.\n\nRespondents were asked a variety of questions about their political beliefs, thoughts on multiple issues, and voting behavior. We will focus on using the demographic variables and someone's party identification to understand whether a person is a probable voter.\n\nThe variables we'll focus on are (definitions from the codebook in data set GitHub repo):\n\n-   `ppage`: Age of respondent\n\n-   `educ`: Highest educational attainment category\n\n-   `race`: Race of respondent, census categories. Note: all categories except Hispanic were non-Hispanic.\n\n-   `gender`: Gender of respondent\n\n-   `income_cat`: Household income category of respondent\n\n-   `Q30`: Response to the question \"Generally speaking, do you think of yourself as a...\"\n\n    -   1: Republican\n    -   2: Democrat\n    -   3: Independent\n    -   4: Another party, please specify\n    -   5: No preference\n    -   -1: No response\n\n-   `voter_category`: past voting behavior:\n\n    -   **always**: respondent voted in all or all-but-one of the elections they were eligible in\n    -   **sporadic**: respondent voted in at least two, but fewer than all-but-one of the elections they were eligible in\n    -   **rarely/never**: respondent voted in 0 or 1 of the elections they were eligible in\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nvoter_data <- read_csv(\"https://raw.githubusercontent.com/fivethirtyeight/data/master/non-voters/nonvoters_data.csv\")\n```\n:::\n\n\nThe variable `Q30` contains the respondent's political party identification. The following code simplifies `Q30` into four categories:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nvoter_data <- voter_data %>%\n  mutate(pol_ident = case_when(\n    Q30 == 1 ~ \"Rep\",\n    Q30 == 2 ~ \"Dem\",\n    Q30 == 3 ~ \"Indep\",\n    TRUE ~ \"Other\"\n  ))\nvoter_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,836 × 120\n   RespId weight    Q1  Q2_1  Q2_2  Q2_3  Q2_4  Q2_5  Q2_6  Q2_7  Q2_8  Q2_9\n    <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n 1 470001  0.752     1     1     1     2     4     1     4     2     2     4\n 2 470002  1.03      1     1     2     2     3     1     1     2     1     1\n 3 470003  1.08      1     1     1     2     2     1     1     2     1     4\n 4 470007  0.682     1     1     1     1     3     1     1     1     1     1\n 5 480008  0.991     1     1     1    -1     1     1     1     1     1     1\n 6 480009  1.06      1     3     2     3     4     1     3     3     1     1\n 7 480010  1.15      1     1     1     2     3     1     1     1     1     1\n 8 470008  1.02      1     1     1     2     2     1     3     1     1     4\n 9 470010  0.818     1     1     1     1     3     1     1     1     1     3\n10 470011  1.17      1     1     1     2     1     1     1     1     2     1\n# ℹ 5,826 more rows\n# ℹ 108 more variables: Q2_10 <dbl>, Q3_1 <dbl>, Q3_2 <dbl>, Q3_3 <dbl>,\n#   Q3_4 <dbl>, Q3_5 <dbl>, Q3_6 <dbl>, Q4_1 <dbl>, Q4_2 <dbl>, Q4_3 <dbl>,\n#   Q4_4 <dbl>, Q4_5 <dbl>, Q4_6 <dbl>, Q5 <dbl>, Q6 <dbl>, Q7 <dbl>,\n#   Q8_1 <dbl>, Q8_2 <dbl>, Q8_3 <dbl>, Q8_4 <dbl>, Q8_5 <dbl>, Q8_6 <dbl>,\n#   Q8_7 <dbl>, Q8_8 <dbl>, Q8_9 <dbl>, Q9_1 <dbl>, Q9_2 <dbl>, Q9_3 <dbl>,\n#   Q9_4 <dbl>, Q10_1 <dbl>, Q10_2 <dbl>, Q10_3 <dbl>, Q10_4 <dbl>, …\n```\n\n\n:::\n:::\n\n\n### Question 1.1 {.unnumbered}\n\nThe variable `voter_category` identifies the respondent's past voter behavior. Relevel the variable to make **rarely/never** the baseline level, followed by sporadic, then always.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\nUse `factor()` with the `levels` argument to set the ordering. The first level becomes the baseline in `multinom()`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nvoter_data$voter_category <- factor(voter_data$voter_category, \n                levels = c(\"rarely/never\", \"sporadic\", \"always\"), \n                ordered = TRUE)\n```\n:::\n\n\n### Question 1.2 {.unnumbered}\n\nMean-center the age variable (`ppage`) so that the intercept reflects the log-odds for an average-aged person rather than a 0-year-old.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nmean_ppage <- mean(voter_data$ppage, na.rm = TRUE)\nvoter_data$ppage_mc <- voter_data$ppage - mean_ppage\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Part 2: Exploratory Data Analysis\n\n### Question 2.1 {.unnumbered}\n\nIn the [FiveThirtyEight article](https://projects.fivethirtyeight.com/non-voters-poll-2020-election/), the authors include visualizations of the relationship between voter category and demographic variables such as race, age, education, etc.\n\nSelect **two** demographic variables. For each variable, create a visualization showing its relationship with `voter_category`. Combine them into a single figure using `patchwork`. Briefly describe (1--2 sentences each) what the plots reveal.\n\nFor inspiration on recreating the FiveThirtyEight style: <https://www.mikelee.co/posts/2020-02-08-recreate-fivethirtyeight-chicklet-stacked-bar-chart-in-ggplot2>\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Quick proportional bar charts\"}\n`geom_bar(position = \"fill\")` gives proportions instead of counts. Map `x` to your demographic variable and `fill` to `voter_category`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 1\nplot1 <- ggplot(voter_data, aes(x= ppage, fill = voter_category)) +\n  geom_bar(position = \"fill\") +\n  labs(title = \"Age and Voter category\",\n       x = \"age\",\n       y = \"proportion\",\n       fill = \"voter category\") +\n  theme_minimal()\n\nplot1\n```\n\n::: {.cell-output-display}\n![](Lab_MultinomialRegression_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot 2\nvoter_data$income_cat <- factor(voter_data$income_cat, \n                levels = c(\"Less than $40k\", \"$40-75k\", \"$75-125k\", \"$125k or more\"), \n                ordered = TRUE)\n\nplot2 <- ggplot(voter_data, aes(x= income_cat, fill = voter_category)) +\n  geom_bar(position = \"fill\") +\n  labs(title = \"Income and Voter category\",\n       x = \"income category\",\n       y = \"proportion\",\n       fill = \"voter category\") +\n  theme_minimal()\n\nplot2\n```\n\n::: {.cell-output-display}\n![](Lab_MultinomialRegression_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine with patchwork\nplot1 + plot2\n```\n\n::: {.cell-output-display}\n![](Lab_MultinomialRegression_files/figure-html/unnamed-chunk-8-1.png){width=768}\n:::\n:::\n\n\n> Enter your interpretation here: (1) People generally tend to vote more often as they get older, but only after age 30. The voting tendency seems to decrease over time for young adults. (2) Regarding income category, the richer people are, the more often they vote. The trend is salient between lower income categories.\n\n------------------------------------------------------------------------\n\n# Part 3: Model Building\n\n### Question 3.1 {.unnumbered}\n\nFit a multinomial logistic regression model using mean-centered age, race, gender, income, and education to predict `voter_category`. Save this as `model_demo`.\n\nYou don't need to display the output here — we'll examine it in Part 4. If you want to peek at it, feel free to run `summary(model_demo)` in your console. There's no real harm in displaying it via the code chunk, except that it'll make your rendered page quite messy. `kable()` is better for clean tables.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\n`multinom(voter_category ~ age_centered + race + gender + income_cat + educ, data = voter_data, trace = FALSE)` — the `trace = FALSE` suppresses the iteration output.\n\nTo keep the rendered document clean, add `#| results: hide` to the chunk header — this runs the code but hides the output. You can always check the output interactively by running the chunk in the console.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nmodel_demo <- multinom(voter_category ~ ppage_mc + race + gender + income_cat + educ, data = voter_data, trace = FALSE)\n```\n:::\n\n\n### Question 3.2 {.unnumbered}\n\nShould party identification (`pol_ident`) be added to the model? Fit a second model that adds `pol_ident` to the predictors. Use `anova()` to compare the two models. Report the test statistic and your conclusion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nmodel_demo_2 <- multinom(voter_category ~ ppage_mc + race + gender + income_cat + educ + pol_ident, data = voter_data, trace = FALSE)\n\nanova(model_demo, model_demo_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio tests of Multinomial Models\n\nResponse: voter_category\n                                                     Model Resid. df Resid. Dev\n1             ppage_mc + race + gender + income_cat + educ     11650   11386.63\n2 ppage_mc + race + gender + income_cat + educ + pol_ident     11644   11232.78\n    Test    Df LR stat. Pr(Chi)\n1                              \n2 1 vs 2     6  153.844       0\n```\n\n\n:::\n\n```{.r .cell-code}\nfinal_model <- model_demo_2\n```\n:::\n\n\n> Enter your answer: The likelihood ratio test shows that adding pol_ident variable as a predictor significantly improves the model ($\\chi^2(6) = 153.84, p < .001$).\n\n**Use the model you select for the remainder of the assignment.** For clarity, call your chosen model `final_model`.\n\n------------------------------------------------------------------------\n\n# Part 4: Interpreting the Model\n\n### Question 4.1: Overall significance {.unnumbered}\n\nUse a likelihood ratio test (`car::Anova()` with `type = \"III\"`) to report the overall significance of each predictor in `final_model`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\ncar::Anova(final_model, type = \"III\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type III tests)\n\nResponse: voter_category\n           LR Chisq Df Pr(>Chisq)    \nppage_mc     638.30  2  < 2.2e-16 ***\nrace          52.65  6  1.379e-09 ***\ngender         6.03  2     0.0491 *  \nincome_cat    67.72  6  1.198e-12 ***\neduc         154.14  4  < 2.2e-16 ***\npol_ident    153.84  6  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n### Question 4.2: Raw coefficients {.unnumbered}\n\nDisplay the model output using `tidy(final_model) %>% kable(digits = 3)`.\n\nPick **one** comparison (e.g., \"sporadic vs. rarely/never\") and do the following:\n\na)  Write out the model equation for that comparison.\nb)  Interpret the coefficient for mean-centered age: what happens to the **odds** of being in that category (vs. the baseline) for each additional year of age? Report the odds ratio `exp(β)`.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint: Reading the tidy() output\"}\nWhen you run `tidy(final_model)`, you'll see a table with columns like `y.level`, `term`, `estimate`, etc. The table has **two blocks of rows** — one block where `y.level` is `sporadic`, and another where `y.level` is `always`. Each block is a separate logistic regression equation:\n\n-   The `sporadic` rows are the equation for: log-odds of sporadic **vs. rarely/never**\n-   The `always` rows are the equation for: log-odds of always **vs. rarely/never**\n\nPick one of those two blocks. The `(Intercept)` row is $\\beta_0$ and the `age_centered` row is $\\beta_1$ for that equation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\ntidy(final_model) %>% kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|y.level  |term                    | estimate| std.error| statistic| p.value|\n|:--------|:-----------------------|--------:|---------:|---------:|-------:|\n|sporadic |(Intercept)             |    1.569|     0.119|    13.153|   0.000|\n|sporadic |ppage_mc                |    0.046|     0.002|    19.654|   0.000|\n|sporadic |raceHispanic            |    0.040|     0.128|     0.314|   0.753|\n|sporadic |raceOther/Mixed         |   -0.332|     0.159|    -2.090|   0.037|\n|sporadic |raceWhite               |   -0.078|     0.108|    -0.719|   0.472|\n|sporadic |genderMale              |   -0.090|     0.072|    -1.248|   0.212|\n|sporadic |income_cat.L            |    0.414|     0.081|     5.101|   0.000|\n|sporadic |income_cat.Q            |   -0.263|     0.072|    -3.650|   0.000|\n|sporadic |income_cat.C            |    0.074|     0.071|     1.033|   0.302|\n|sporadic |educHigh school or less |   -0.853|     0.097|    -8.761|   0.000|\n|sporadic |educSome college        |   -0.293|     0.095|    -3.076|   0.002|\n|sporadic |pol_identIndep          |   -0.392|     0.098|    -4.017|   0.000|\n|sporadic |pol_identOther          |   -0.940|     0.106|    -8.853|   0.000|\n|sporadic |pol_identRep            |   -0.084|     0.103|    -0.815|   0.415|\n|always   |(Intercept)             |    1.366|     0.128|    10.627|   0.000|\n|always   |ppage_mc                |    0.058|     0.003|    22.688|   0.000|\n|always   |raceHispanic            |   -0.341|     0.150|    -2.277|   0.023|\n|always   |raceOther/Mixed         |   -0.600|     0.185|    -3.239|   0.001|\n|always   |raceWhite               |    0.127|     0.119|     1.071|   0.284|\n|always   |genderMale              |   -0.192|     0.080|    -2.413|   0.016|\n|always   |income_cat.L            |    0.483|     0.090|     5.344|   0.000|\n|always   |income_cat.Q            |   -0.414|     0.080|    -5.196|   0.000|\n|always   |income_cat.C            |    0.037|     0.078|     0.481|   0.630|\n|always   |educHigh school or less |   -1.267|     0.109|   -11.644|   0.000|\n|always   |educSome college        |   -0.330|     0.102|    -3.225|   0.001|\n|always   |pol_identIndep          |   -0.562|     0.107|    -5.259|   0.000|\n|always   |pol_identOther          |   -1.401|     0.131|   -10.678|   0.000|\n|always   |pol_identRep            |   -0.162|     0.110|    -1.469|   0.142|\n\n\n:::\n\n```{.r .cell-code}\nexp(0.058)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.059715\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef_age <- tidy(final_model) %>% \n  dplyr::filter(term == \"ppage_mc\", y.level == \"always\")\nbeta <- coef_age$estimate\nse <- coef_age$std.error\nlower <- exp(beta - 1.96 * se)\nupper <- exp(beta + 1.96 * se)\nc(lower, upper)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.054618 1.065278\n```\n\n\n:::\n\n```{.r .cell-code}\nexp(beta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.059935\n```\n\n\n:::\n:::\n\n\n> Enter your equation and interpretation here: (rarely/never vs. always) voter_category = 1.366 + 0.058 \\* ppage_mc + (-0.341)\\*raceHispanic + ... + (-0.162)\\*pol_identRep\n>\n> With each additional year of age, the odds of being in 'always' category (rather than 'rarely/never' category) increases about 6%.\n\n### Question 4.3: Changing the baseline {.unnumbered}\n\nRefit the model with a **different** baseline category for `voter_category` (e.g., \"always\" instead of \"rarely/never\"). Then predict the probabilities for a specific observation using both models.\n\nDo the coefficients change? Do the predicted probabilities change? Explain in 1--2 sentences why this happens.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\nUse `relevel(voter_category, ref = \"always\")` before refitting. Use `predict(model, newdata = ..., type = \"probs\")` to get predicted probabilities. You can use `head(voter_data, 1)` as your newdata for a quick check.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nvoter_data$voter_category <- relevel(factor(voter_data$voter_category, ordered = FALSE), ref = \"always\")\n\nmodel_refit <- multinom(voter_category ~ ppage_mc + race + gender + income_cat + educ + pol_ident, data = voter_data, trace = FALSE)\n\ntidy(model_refit) %>% kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|y.level      |term                    | estimate| std.error| statistic| p.value|\n|:------------|:-----------------------|--------:|---------:|---------:|-------:|\n|rarely/never |(Intercept)             |   -1.366|     0.128|   -10.628|   0.000|\n|rarely/never |ppage_mc                |   -0.058|     0.003|   -22.688|   0.000|\n|rarely/never |raceHispanic            |    0.341|     0.150|     2.277|   0.023|\n|rarely/never |raceOther/Mixed         |    0.600|     0.185|     3.239|   0.001|\n|rarely/never |raceWhite               |   -0.127|     0.119|    -1.071|   0.284|\n|rarely/never |genderMale              |    0.192|     0.080|     2.413|   0.016|\n|rarely/never |income_cat.L            |   -0.483|     0.090|    -5.344|   0.000|\n|rarely/never |income_cat.Q            |    0.414|     0.080|     5.196|   0.000|\n|rarely/never |income_cat.C            |   -0.037|     0.078|    -0.481|   0.630|\n|rarely/never |educHigh school or less |    1.267|     0.109|    11.644|   0.000|\n|rarely/never |educSome college        |    0.330|     0.102|     3.226|   0.001|\n|rarely/never |pol_identIndep          |    0.562|     0.107|     5.259|   0.000|\n|rarely/never |pol_identOther          |    1.401|     0.131|    10.678|   0.000|\n|rarely/never |pol_identRep            |    0.162|     0.110|     1.469|   0.142|\n|sporadic     |(Intercept)             |    0.204|     0.094|     2.165|   0.030|\n|sporadic     |ppage_mc                |   -0.013|     0.002|    -6.375|   0.000|\n|sporadic     |raceHispanic            |    0.381|     0.122|     3.118|   0.002|\n|sporadic     |raceOther/Mixed         |    0.268|     0.156|     1.717|   0.086|\n|sporadic     |raceWhite               |   -0.205|     0.093|    -2.210|   0.027|\n|sporadic     |genderMale              |    0.102|     0.063|     1.615|   0.106|\n|sporadic     |income_cat.L            |   -0.069|     0.073|    -0.944|   0.345|\n|sporadic     |income_cat.Q            |    0.151|     0.063|     2.388|   0.017|\n|sporadic     |income_cat.C            |    0.036|     0.061|     0.595|   0.552|\n|sporadic     |educHigh school or less |    0.414|     0.087|     4.758|   0.000|\n|sporadic     |educSome college        |    0.037|     0.077|     0.484|   0.629|\n|sporadic     |pol_identIndep          |    0.170|     0.084|     2.021|   0.043|\n|sporadic     |pol_identOther          |    0.461|     0.121|     3.801|   0.000|\n|sporadic     |pol_identRep            |    0.078|     0.082|     0.952|   0.341|\n\n\n:::\n\n```{.r .cell-code}\npredict(model_refit, newdata = head(voter_data, 1), type = \"probs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      always rarely/never     sporadic \n  0.57788857   0.02811795   0.39399348 \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(final_model, newdata = head(voter_data, 1), type = \"probs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nrarely/never     sporadic       always \n  0.02811839   0.39399517   0.57788644 \n```\n\n\n:::\n:::\n\n\n> Enter your answer: The coefficients change as baseline changes because they are calculated relative to the reference category. Whereas the predicted probabilities remain the same as the model predictions for each category don't change.\n\n------------------------------------------------------------------------\n\n# Part 5: Marginal Effects & Visualization\n\n### Question 5.1: Predicted probabilities by age {.unnumbered}\n\nPlot the predicted probabilities of voter category as a function of age. The code below will work once you replace `final_model` with the name of your model:\n\n::: callout-note\nThis chunk is set to `eval: false` so the file renders before you've built your model. Once `final_model` exists in your environment, delete the `#| eval: false` line so the chunk runs when you render.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggemmeans(final_model, terms = c(\"ppage_mc [n=25]\")) %>%\n  ggplot(., aes(x = x, y = predicted, fill = response.level)) +\n  geom_area() +\n  geom_rug(sides = \"b\", position = \"jitter\", alpha = .2) +\n  labs(x = \"\\nAge\", y = \"Predicted Probability\\n\",\n       title = \"Predicted Probabilities of Voting Frequency by Age\") +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"always\" = \"#F6B533\", \"sporadic\" = \"#D07EA2\", \"rarely/never\" = \"#9854F7\"),\n    labels = c(\"RARELY OR NEVER VOTE    \", \"SOMETIMES VOTE    \", \"ALMOST ALWAYS VOTE    \"),\n    breaks = c(\"rarely/never\", \"sporadic\", \"always\")\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab_MultinomialRegression_files/figure-html/unnamed-chunk-14-1.png){width=768}\n:::\n\n```{.r .cell-code}\n#ppage_mc [all] didn't work; the error message said the rows of my requested reference grid (i.e., 14208) exceeded the limit of 10000.\n```\n:::\n\n\nDescribe the pattern you see in 1--2 sentences.\n\n> Enter your interpretation here: Voting behavior increases as people get older. The probabilities of 'sometimes voting' is highest in young adults but declines for older population.\n\n### Question 5.2: Predicted probabilities by education {.unnumbered}\n\nCreate a similar plot showing predicted probabilities of voter category as a function of **education level**.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\nReplace `\"ppage [all]\"` with `\"educ\"` in the `ggemmeans()` call. Since education is categorical, you may want to use `geom_col(position = \"dodge\")` or `geom_col(position = \"fill\")` instead of `geom_area()`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\nggemmeans(final_model, terms = c(\"educ\")) %>%\n  ggplot(., aes(x = x, y = predicted, fill = response.level)) +\n  geom_col(position = \"fill\") +\n  geom_rug(sides = \"b\", position = \"jitter\", alpha = .2) +\n  labs(x = \"\\nAge\", y = \"Predicted Probability\\n\",\n       title = \"Predicted Probabilities of Voting Frequency by Education level\") +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"always\" = \"#F6B533\", \"sporadic\" = \"#D07EA2\", \"rarely/never\" = \"#9854F7\"),\n    labels = c(\"RARELY OR NEVER VOTE    \", \"SOMETIMES VOTE    \", \"ALMOST ALWAYS VOTE    \"),\n    breaks = c(\"rarely/never\", \"sporadic\", \"always\")\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Lab_MultinomialRegression_files/figure-html/unnamed-chunk-15-1.png){width=768}\n:::\n:::\n\n\n> Enter your interpretation here: Individuals with higher education level tend to vote more often compared to individuals with lower education level. The probability of 'rarely or never voting' is the highest in 'high school or less' group and the lowest in 'college' group. The probability of 'almost always voting' showed the opposite trend.\n\n------------------------------------------------------------------------\n\n# Part 6: Pairwise Comparisons\n\n### Question 6.1: Political group differences {.unnumbered}\n\nRun the following code (replacing `final_model` with your model name) and interpret the output. The code computes estimated marginal means for each political group within each voter category, then tests pairwise differences on the log-odds scale.\n\n::: callout-note\nSame as Q5.1 — this chunk is set to `eval: false`. Delete that line once `final_model` exists.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Estimated marginal means: political group by voter category\nmulti_an_pol <- emmeans(final_model, ~ pol_ident | voter_category)\n\n# Contrasts on the log scale (log-odds differences between voter categories, within each political group)\ncoefs_pol <- contrast(regrid(multi_an_pol, \"log\"), \"trt.vs.ctrl1\", by = \"pol_ident\")\n\n# Display results, organized by contrast\nupdate(coefs_pol, by = \"contrast\") %>%\n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|contrast                  |pol_ident | estimate|    SE| df| t.ratio| p.value|\n|:-------------------------|:---------|--------:|-----:|--:|-------:|-------:|\n|sporadic - (rarely/never) |Dem       |    0.961| 0.070| 28|  13.722|   0.000|\n|always - (rarely/never)   |Dem       |    0.480| 0.074| 28|   6.498|   0.000|\n|sporadic - (rarely/never) |Indep     |    0.591| 0.077| 28|   7.643|   0.000|\n|always - (rarely/never)   |Indep     |   -0.049| 0.084| 28|  -0.589|   0.900|\n|sporadic - (rarely/never) |Other     |    0.078| 0.087| 28|   0.901|   0.747|\n|always - (rarely/never)   |Other     |   -0.835| 0.110| 28|  -7.577|   0.000|\n|sporadic - (rarely/never) |Rep       |    0.883| 0.084| 28|  10.469|   0.000|\n|always - (rarely/never)   |Rep       |    0.327| 0.089| 28|   3.672|   0.004|\n\n\n:::\n\n```{.r .cell-code}\n# Pairwise differences between political groups, within each contrast\ncontrast(coefs_pol, \"revpairwise\", by = \"contrast\") %>%\n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|contrast1     |contrast                  | estimate|    SE| df| t.ratio| p.value|\n|:-------------|:-------------------------|--------:|-----:|--:|-------:|-------:|\n|Indep - Dem   |sporadic - (rarely/never) |   -0.370| 0.094| 28|  -3.933|   0.003|\n|Other - Dem   |sporadic - (rarely/never) |   -0.883| 0.103| 28|  -8.578|   0.000|\n|Other - Indep |sporadic - (rarely/never) |   -0.513| 0.107| 28|  -4.807|   0.000|\n|Rep - Dem     |sporadic - (rarely/never) |   -0.078| 0.099| 28|  -0.787|   0.860|\n|Rep - Indep   |sporadic - (rarely/never) |    0.292| 0.099| 28|   2.965|   0.029|\n|Rep - Other   |sporadic - (rarely/never) |    0.805| 0.109| 28|   7.404|   0.000|\n|Indep - Dem   |always - (rarely/never)   |   -0.529| 0.101| 28|  -5.254|   0.000|\n|Other - Dem   |always - (rarely/never)   |   -1.315| 0.125| 28| -10.508|   0.000|\n|Other - Indep |always - (rarely/never)   |   -0.786| 0.129| 28|  -6.072|   0.000|\n|Rep - Dem     |always - (rarely/never)   |   -0.153| 0.104| 28|  -1.470|   0.468|\n|Rep - Indep   |always - (rarely/never)   |    0.376| 0.104| 28|   3.605|   0.006|\n|Rep - Other   |always - (rarely/never)   |    1.162| 0.130| 28|   8.969|   0.000|\n\n\n:::\n:::\n\n\n> Enter your interpretation here: Democratic and Republican voters are significantly more likely to be sporadic or always voting rather than rarely/never voting. Independent voters are more likely to be sporadic voters and Others to be always voters, both compared to being 'rarely/never' voters. Democrats are significantly more likely to vote sporaticaly or always (vs. rarely/never) than other political identity groups.\n\n### Question 6.2: Education level differences {.unnumbered}\n\nAdapt the code from 6.1 to examine differences across **education levels** instead of political groups. Run it and interpret.\n\n::: {.callout-tip collapse=\"true\" title=\"Hint\"}\nReplace `pol_ident` with `educ` in the `emmeans()` and `contrast()` calls.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code\n# Estimated marginal means: education level group by voter category\nmulti_an_educ <- emmeans(final_model, ~ educ | voter_category)\n\n# Contrasts on the log scale (log-odds differences between voter categories, within each education level group)\ncoefs_educ <- contrast(regrid(multi_an_educ, \"log\"), \"trt.vs.ctrl1\", by = \"educ\")\n\n# Display results, organized by contrast\nupdate(coefs_educ, by = \"contrast\") %>%\n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|contrast                  |educ                | estimate|    SE| df| t.ratio| p.value|\n|:-------------------------|:-------------------|--------:|-----:|--:|-------:|-------:|\n|sporadic - (rarely/never) |College             |    0.986| 0.076| 28|  12.904|   0.000|\n|always - (rarely/never)   |College             |    0.477| 0.080| 28|   5.960|   0.000|\n|sporadic - (rarely/never) |High school or less |    0.187| 0.069| 28|   2.705|   0.031|\n|always - (rarely/never)   |High school or less |   -0.711| 0.080| 28|  -8.883|   0.000|\n|sporadic - (rarely/never) |Some college        |    0.707| 0.074| 28|   9.512|   0.000|\n|always - (rarely/never)   |Some college        |    0.167| 0.079| 28|   2.115|   0.112|\n\n\n:::\n\n```{.r .cell-code}\n# Pairwise differences between education groups, within each contrast\ncontrast(coefs_educ, \"revpairwise\", by = \"contrast\") %>%\n  kable(format = \"markdown\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|contrast1                          |contrast                  | estimate|    SE| df| t.ratio| p.value|\n|:----------------------------------|:-------------------------|--------:|-----:|--:|-------:|-------:|\n|High school or less - College      |sporadic - (rarely/never) |   -0.799| 0.095| 28|  -8.416|   0.000|\n|Some college - College             |sporadic - (rarely/never) |   -0.278| 0.092| 28|  -3.030|   0.014|\n|Some college - High school or less |sporadic - (rarely/never) |    0.520| 0.088| 28|   5.920|   0.000|\n|High school or less - College      |always - (rarely/never)   |   -1.188| 0.104| 28| -11.394|   0.000|\n|Some college - College             |always - (rarely/never)   |   -0.310| 0.097| 28|  -3.207|   0.009|\n|Some college - High school or less |always - (rarely/never)   |    0.878| 0.098| 28|   8.995|   0.000|\n\n\n:::\n:::\n\n\n> Enter your interpretation here: The results show that voting behavior increases across low to high education levels. For example, while college education group is more likely to vote always or sporadically than rarely/never, high school or less group is more likely to vote rarely/never than always or sporadically.\n\n------------------------------------------------------------------------\n\n# Part 7: Write-Up\n\n### Question 7.1 {.unnumbered}\n\nWrite a **1-paragraph results section** for your final model. Your paragraph should include:\n\n-   The model type and baseline category\n-   Sample size\n-   At least one key coefficient reported as an odds ratio with a confidence interval\n-   The result of the likelihood ratio test for at least one predictor\n-   At least one finding translated into predicted probability terms (from your plots)\n\n> Enter your write-up here: We used a multinomial logistic regression model (baseline category: rarely/never) to predict voting frequency from age, race, gender, income, education, and political identification (N = 5,836). The likelihood ratio test indicated that political identification was a significant predictor of voter category, *χ²*(6) = 153.84, *p* \\< .001. Among individuals in 'rarely/never' and 'always' groups, each additional year of age was associated with an increase in the odds of being always vs. rarely/never voting (OR = 1.060, 95% CI \\[1.055, 1.065\\]). Predicted probability plots showed that the probability of 'almost always' voting increases with age, while the probability of rarely or never voting decreases with age.\n",
    "supporting": [
      "Lab_MultinomialRegression_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}