{
  "hash": "aaef8896a1e67364a3f12b8bb6d188a0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Bayes and Penguins (Part 2)\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Yeaju Diana Kim\"\ndate: \"2026-04-08\"\ndate-modified: today\nformat:\n  html:\n    code-fold: true\n    code-overflow: wrap\n    toc: true\n    toc-depth: 2\n    toc-location: left\nexecute:\n  message: false\n  warning: false\nengine: knitr\n---\n\n::: callout-note\n## Continuing from last week\n\nThis lab picks up where Part 1 left off ([HTML](Bayes_Lab_2_Penguins.html), [QMD](https://github.com/suyoghc/PSY504_Spring_2026/raw/main/posts/Bayes%202/Bayes_Lab_2_Penguins.qmd)). You'll need the same packages and Chinstrap data from last week.\n:::\n\n::: callout-important\n## How to work through this lab\n\nYou will explore distributions, model checking, and priors using `brms`.\n\n1.  Read and run through each code chunk, making sure you understand what it does before moving on.\n2.  Some questions have a **hidden answer you can reveal** after writing your own response. These cover concepts that later questions build on, so check your understanding before moving on.\n3.  Other questions are **open**: no answer is provided. By that point, the walkthrough has given you enough context to reason through them on your own.\n4.  Write your responses in the code chunks marked `# Enter your answer here` (use R comments for text answers). For coding exercises, write your code in chunks marked `# Enter your code here`.\n:::\n\n# Part 3: Distributions all the way down\n\nIn Part 1, you explored the data and fit models with `lm()` and `brm()` (using default priors). You also drew posterior samples. Now we continue with distributions and priors.\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(brms)\nlibrary(tidybayes)\nlibrary(ggdist)\n```\n:::\n\n\n## Packages and data\n\nWe want the same data set up as in the last lab.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the penguins data\ndata(penguins, package = \"palmerpenguins\")\n\n# subset the data\nchinstrap <- penguins %>%\n  filter(species == \"Chinstrap\")\n\nglimpse(chinstrap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 68\nColumns: 8\n$ species           <fct> Chinstrap, Chinstrap, Chinstrap, Chinstrap, Chinstra…\n$ island            <fct> Dream, Dream, Dream, Dream, Dream, Dream, Dream, Dre…\n$ bill_length_mm    <dbl> 46.5, 50.0, 51.3, 45.4, 52.7, 45.2, 46.1, 51.3, 46.0…\n$ bill_depth_mm     <dbl> 17.9, 19.5, 19.2, 18.7, 19.8, 17.8, 18.2, 18.2, 18.9…\n$ flipper_length_mm <int> 192, 196, 193, 188, 197, 198, 178, 197, 195, 198, 19…\n$ body_mass_g       <int> 3500, 3900, 3650, 3525, 3725, 3950, 3250, 3750, 4150…\n$ sex               <fct> female, male, male, female, male, female, female, ma…\n$ year              <int> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n```\n\n\n:::\n:::\n\n\n## Models\n\nOnce again, we'll fit the model\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i + \\epsilon_i \\\\\n\\epsilon_i & \\sim \\operatorname{Normal}(0, \\sigma_\\epsilon) ,\n\\end{align}\n$$\n\nwith both `lm()` and `brm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# OLS\nfit1.ols <- lm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n\n# Bayes\nfit1.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n```\n:::\n\n\n## Bayesians have many kinds of distributions\n\nIn Bayesian statistics, we have at least 6 distributions to keep track of. Those are:\n\n-   the likelihood distributions\n-   the prior parameter distribution (aka priors)\n-   the prior predictive distributions\n-   the posterior parameter distributions (aka posteriors)\n-   the posterior-predictive distribution\n\nIn many respect, it's distributions 'all the way down,' with Bayesians. This can indeed be difficult to keep track of at first. But since this is true for any class of Bayesian models (not just regression), you'll hopefully get used to it.\n\n### Question 3.1 {.unnumbered}\n\nFill in the blanks using $\\theta$, $D$, and $\\mid$ (the conditioning bar):\n\n::: callout-tip\nThe conditioning bar $\\mid$ means \"given.\" Think about which quantity you know and which you're trying to learn about.\n:::\n\n| Distribution         | Notation (fill in the blank) |\n|----------------------|------------------------------|\n| Likelihood           | $P(D|\\theta)$                |\n| Prior                | $P(\\theta)$                  |\n| Prior predictive     | $P(D)$                       |\n| Posterior            | $P(\\theta|D)$                |\n| Posterior predictive | $P(D_{new} | D)$             |\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n| Distribution         | Notation                   |\n|----------------------|----------------------------|\n| Likelihood           | $P(D \\mid \\theta)$         |\n| Prior                | $P(\\theta)$                |\n| Prior predictive     | $P(D)$                     |\n| Posterior            | $P(\\theta \\mid D)$         |\n| Posterior predictive | $P(D_{\\text{new}} \\mid D)$ |\n:::\n\nWe also have some other distributions that follow from these. For example, - the distributions of the model expectations (i.e., the predicted means)\n\n### Likelihood distributions.\n\nWe are approaching Bayesian statistics from a likelihood-based perspective. That is, we situate regression models within the greater context of a likelihood function. (There are ways to do non-parametric Bayesian statistics, which don't focus on likelihoods. We won't get into that right now.)\n\nSo far, we have been using the conventional Gaussian likelihood. If we have some variable $y$, we can express it as normally distributed by\n\n$$\n\\operatorname{Normal}(y \\mid \\mu, \\sigma) = \\frac{1}{\\sqrt{2 \\pi \\sigma}} \\exp \\left( \\frac{1}{2} \\left( \\frac{y - \\mu}{\\sigma}\\right)^2\\right),\n$$\n\nwhere $\\mu$ is the mean and $\\sigma$ is the standard deviation. With this likelihood,\n\n-   $\\mu \\in \\mathbb R$\n    -   the mean can be any real number, ranging from $-\\infty$ to $\\infty$\n-   $\\sigma \\in \\mathbb R_{> 0}$\n    -   the standard deviation can take on any real number greater than zero.\n\nIt's also the assumption\n\n-   $y \\in \\mathbb R$\n    -   the focal variable $y$ can be any real number, ranging from $-\\infty$ to $\\infty$.\n\nOne of the ways we wrote our model formula back in the first file was\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i,\n\\end{align}\n$$\n\nand further in the discussion, we updated that equation with the posterior means for our three parameters to\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, 2.92) \\\\\n\\mu_i & = 32.2 + 0.004 \\text{body\\_mass\\_g}_i.\n\\end{align}\n$$\n\nBefore we get into this, though, let's back up and consider an intercept-only model of the form\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 ,\n\\end{align}\n$$\n\nwhere there is no predictor variable. Here's how to fit the model with `brm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bayes\nfit0.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1\n)\n```\n:::\n\n\nLet's look at the model summary.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit0.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: bill_length_mm ~ 1 \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept    48.84      0.40    48.06    49.62 1.00     4013     3116\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     3.37      0.29     2.87     4.01 1.00     3757     2653\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\nThe intercept parameter $\\beta_0$ is a stand-in for $\\mu$. The $\\sigma$ parameter is just $\\sigma$. Here they are in a plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws <- as_draws_df(fit0.b) \n\ndraws %>% \n  rename(`beta[0]==mu` = b_Intercept) %>% \n  pivot_longer(`beta[0]==mu`:sigma, names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_halfeye(.width = .95, normalize = \"panels\") +\n  scale_y_continuous(NULL, breaks = NULL) +\n  xlab(\"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nHere are the posterior means for those two parameters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu <- mean(draws$b_Intercept)\nsigma <- mean(draws$sigma)\n\nmu; sigma\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 48.83851\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.371195\n```\n\n\n:::\n:::\n\n\nWe can use `dnorm()` to compute the shape of $\\operatorname{Normal}(48.8, 3.4)$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(y = seq(from = 30, to = 70, by = 0.1)) %>% \n  mutate(density = dnorm(x = y, mean = mu, sd = sigma)) %>% \n  \n  ggplot(aes(x = y, y = density)) +\n  geom_line() +\n  xlab(\"bill_length_mm\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nWe can compare this to the sample distribution of the `bill_length_mm` data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchinstrap %>% \n  ggplot(aes(x = bill_length_mm)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 binwidth = 2.5) +\n  geom_line(data = tibble(bill_length_mm = seq(from = 30, to = 70, by = 0.1)),\n            aes(y = dnorm(x = bill_length_mm, mean = mu, sd = sigma)),\n            color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nIt's not a great fit, but not horrible either.\n\n### Question 3.2 {.unnumbered}\n\nThe red curve is the model's best guess at the distribution of `bill_length_mm`. What does this model get right? What does it miss?\n\n::: callout-tip\nThink about what a single Normal curve can and can't capture. Also: this model has no predictor.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# I think the size of variance overall is well captured. The real data is a little bit left skewed.\n```\n:::\n\n\nNow let's see what this means for our univariable model `fit1.b`. First, let's learn about the `posterior_summary()` function, which we'll use to save a few posterior means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_summary(fit1.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate    Est.Error          Q2.5         Q97.5\nb_Intercept    3.217023e+01 3.5038454770  2.514265e+01  3.906066e+01\nb_body_mass_g  4.465923e-03 0.0009344017  2.616279e-03  6.323748e-03\nsigma          2.923537e+00 0.2594267713  2.459553e+00  3.473933e+00\nIntercept      4.884191e+01 0.3602702444  4.814401e+01  4.955748e+01\nlprior        -4.298303e+00 0.0695396837 -4.456549e+00 -4.180625e+00\nlp__          -1.723520e+02 1.2777185738 -1.756278e+02 -1.709042e+02\n```\n\n\n:::\n\n```{.r .cell-code}\nb0    <- posterior_summary(fit1.b)[1, 1]\nb1    <- posterior_summary(fit1.b)[2, 1]\nsigma <- posterior_summary(fit1.b)[3, 1]\n```\n:::\n\n\nNow we plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrossing(body_mass_g    = seq(from = 2500, to = 5000, length.out = 200),\n         bill_length_mm = seq(from = 35, to = 60, length.out = 200))  %>% \n  mutate(density = dnorm(x = bill_length_mm, \n                         mean = b0 + b1 * body_mass_g,\n                         sd = sigma)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = bill_length_mm)) +\n  geom_raster(aes(fill = density),\n              interpolate = TRUE) +\n  geom_point(data = chinstrap,\n             shape = 21, color = \"white\", fill = \"black\", stroke = 1/4) +\n  scale_fill_viridis_c(option = \"A\", begin = .15, limits = c(0, NA)) +\n  coord_cartesian(xlim = range(chinstrap$body_mass_g),\n                  ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nOur univariable model `fit1.b` can be viewed as something like a 3-dimensional Gaussian hill.\n\n### Prior distributions & Prior predictive distributions.\n\nLet's hold off on this for a bit.\n\n### Parameter distributions.\n\nUp above, we plotted the posterior distributions for our intercept-only `fit0.b` model. Here they are again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws %>% \n  rename(`beta[0]==mu` = b_Intercept) %>% \n  pivot_longer(`beta[0]==mu`:sigma, names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_halfeye(.width = .99, normalize = \"panels\",\n               # customize some of the aesthetics\n               fill = \"lightskyblue1\", color = \"royalblue\", \n               point_color = \"darkorchid4\", point_size = 4, shape = 15) +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"fit0.b\",\n       subtitle = \"This time we used 99% intervals, and got silly with the colors.\",\n       x = \"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWe might practice making a similar plot for our univariable model `fit1.b`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas_draws_df(fit1.b) %>% \n  rename(`beta[0]` = b_Intercept,\n         `beta[1]` = b_body_mass_g) %>% \n  pivot_longer(cols = c(`beta[0]`, `beta[1]`, sigma), \n               names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_histinterval(.width = .95, normalize = \"panels\") +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"fit1.b\",\n       subtitle = \"Using good old 95% intervals, but switching to histograms\",\n       x = \"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nSome authors, like John Kruschke, have a strong preference for plotting their posteriors with histograms, rather than density plots.\n\n## Distributions of the model expectations.\n\nTake another look at the `conditional_effects()` plot from earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_effects(fit1.b) %>% \n  plot(points = TRUE)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nThe blue line is the posterior mean, for the $\\mu_i$, the model-based mean for `bill_length_mm`, given the value for the predictor `body_mass_g`. The semitransparent gray ribbon marks the percentile-based interval for the conditional mean.\n\nWe can make a similar plot with the `fitted()` function. First we'll need a predictor grid, we'll call `nd`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnd <- tibble(body_mass_g = seq(\n  from = min(chinstrap$body_mass_g),\n  to = max(chinstrap$body_mass_g),\n  length.out = 100))\n\nglimpse(nd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 100\nColumns: 1\n$ body_mass_g <dbl> 2700.000, 2721.212, 2742.424, 2763.636, 2784.848, 2806.061…\n```\n\n\n:::\n:::\n\n\nNow pump `nd` into the `fitted()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.22822 1.0276102 42.19418 46.22168\n[2,] 44.32295 1.0090714 42.32842 46.27089\n[3,] 44.41768 0.9905823 42.45996 46.32791\n[4,] 44.51241 0.9721456 42.59432 46.38952\n[5,] 44.60714 0.9537645 42.72036 46.44921\n[6,] 44.70188 0.9354422 42.85108 46.50985\n```\n\n\n:::\n:::\n\n\nNow plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/3) +\n  geom_line(aes(y = Estimate)) +\n  # add the data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nLook what happens if we augment the `probs` argument in `fitted()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       probs = c(.025, .975, .25, .75)) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  # 95% range\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # 50% range\n  geom_ribbon(aes(ymin = Q25, ymax = Q75),\n              alpha = 1/4) +\n  geom_line(aes(y = Estimate)) +\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nNow look what happens if we set `summary = FALSE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = FALSE) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:4000, 1:100] 44.5 43.4 44.6 45.3 43.2 ...\n```\n\n\n:::\n:::\n\n\nWe get full 4,000 draw posterior distributions for each of the 100 levels of the predictor `body_mass_g`. Now look at what happens if we wrangle that output a little, and plot with aid from `stat_lineribbon()` from the **ggdist** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value)) +\n  stat_lineribbon() +\n  scale_fill_brewer() +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nLook what happens when we request more intervals in the `.width` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value)) +\n  # make more ribbons\n  stat_lineribbon(.width = c(.1, .2, .3, .4, .5, .6, .7, .8, .9),\n                  # remove the line\n                  linewidth = 0) +\n  scale_fill_brewer() +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThe conditional mean, $\\mu_i$, has its own distribution. We can take this visualization approach even further to make a color gradient.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value, fill = after_stat(.width))) +\n  # make more ribbons\n  stat_lineribbon(.width = ppoints(50)) +\n  scale_fill_distiller(limits = 0:1) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nFor technical details on this visualization approach, go here: <https://mjskay.github.io/ggdist/articles/lineribbon.html#lineribbon-gradients>.\n\nThe **ggdist** package even has an experimental visualization approach that's based on density gradients, rather than interval-width gradients. Since this is experimental, I'm not going to go into the details. But if you're curious and adventurous, you can learn more here: <https://mjskay.github.io/ggdist/articles/lineribbon.html#lineribbon-density-gradients>.\n\n### Posterior-predictive distributions.\n\nThe last section showed the posterior distributions for the model expectations (i.e., the conditional means). In the context of the Gaussian distribution, that's $\\mu$, or $\\mu_i$ in the case of the univariable model `fit1.b`. But the whole Gaussian distribution includes $\\mu$ and $\\sigma$.\n\nThis is where the `predict()` function comes in. First, we compare the `fitted()` output to `predict()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfitted(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.22822 1.0276102 42.19418 46.22168\n[2,] 44.32295 1.0090714 42.32842 46.27089\n[3,] 44.41768 0.9905823 42.45996 46.32791\n[4,] 44.51241 0.9721456 42.59432 46.38952\n[5,] 44.60714 0.9537645 42.72036 46.44921\n[6,] 44.70188 0.9354422 42.85108 46.50985\n```\n\n\n:::\n\n```{.r .cell-code}\npredict(fit1.b, newdata = nd) %>% \n  # subset the first 6 rows\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 44.21445  3.151387 37.88261 50.37860\n[2,] 44.25735  3.101402 38.31346 50.44319\n[3,] 44.43334  3.057953 38.39114 50.48526\n[4,] 44.50751  3.111923 38.45420 50.72353\n[5,] 44.66224  3.034546 38.65895 50.37174\n[6,] 44.74057  3.047951 38.84033 50.81817\n```\n\n\n:::\n:::\n\n\nThe posterior means (`Estimate`) are about the same, but the SD's (`Est.Error`) are much larger in the `predict()` output, and the widths of the 95% intervals are too. Let's make a plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/3) +\n  geom_line(aes(y = Estimate)) +\n  # add the data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm)) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nThe gray band is the 95% interval for the entire posterior predictive distribution, not just the mean. In a good model, about 95% of the data points should be within those bands.\n\nThe jagged edges of the band reflect uncertainty in $\\sigma$, not just the mean.\n\nIf we wanted to, we could integrate the `fitted()`-based conditional posterior mean, with the `predict()`-based posterior-predictive distribution.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# save the fitted() results\nf <- fitted(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) \n\npredict(fit1.b, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  \n  ggplot(aes(x = body_mass_g)) +\n  # 95% posterior-predictive range\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # 95% conditional mean range\n  geom_ribbon(data = f,\n              aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # posterior mean of the conditional mean\n  geom_line(data = f,\n            aes(y = Estimate)) +\n  # original data\n  geom_point(data = chinstrap,\n             aes(y = bill_length_mm)) +\n  coord_cartesian(ylim = range(chinstrap$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n### Question 3.3 {.unnumbered}\n\n`fitted()` gives uncertainty in the mean; `predict()` gives uncertainty in new observations. In your own words, why is the `predict()` band always wider? When would you report each one?\n\n::: callout-tip\nLook at the model equation. `fitted()` uses only $\\beta_0 + \\beta_1 x$. What extra step does `predict()` add?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# predict() adds error distributions. To show prediction for other data points you should plot predict(). To show general (mean) relationship between variables you should plot fitted().\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\n`predict()` adds a random draw from $\\text{Normal}(0, \\sigma)$ on top. Use `fitted()` for \"what's the average bill length at this body mass?\" Use `predict()` for \"where might the next penguin's bill length fall?\"\n:::\n\nIt's the posterior predictive distribution that we use to predict new data points. For example, here's what happens if we use `predict()` without the `newdata` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b) %>% \n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Estimate Est.Error     Q2.5    Q97.5\n[1,] 47.80615  3.001387 41.90656 53.67784\n[2,] 49.56009  2.956621 43.73298 55.46429\n[3,] 48.44219  2.967314 42.47123 54.19332\n[4,] 47.93954  2.957636 42.11558 53.63948\n[5,] 48.79048  3.012299 42.68860 54.75116\n[6,] 49.72023  2.995857 43.95797 55.65735\n```\n\n\n:::\n:::\n\n\nWe get posterior predictive summaries for each of the original data points. Here's what happens if we set `summary = FALSE`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, summary = FALSE) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:4000, 1:68] 46 45.8 53 51 51 ...\n - attr(*, \"dimnames\")=List of 2\n  ..$ : NULL\n  ..$ : NULL\n```\n\n\n:::\n:::\n\n\nThis time, we got 4,000 posterior draws for each. We can reduce that output with the `ndraws` argument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(fit1.b, summary = FALSE, ndraws = 6) %>% \n  str()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n num [1:6, 1:68] 43.9 52.9 51.4 44.4 48 ...\n - attr(*, \"dimnames\")=List of 2\n  ..$ : NULL\n  ..$ : NULL\n```\n\n\n:::\n:::\n\n\nNow wrangle and plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\npredict(fit1.b, summary = FALSE, ndraws = 6) %>% \n  data.frame() %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(row = str_remove(name, \"X\") %>% as.double()) %>% \n  left_join(chinstrap %>% \n              mutate(row = 1:n()),\n            by = join_by(row)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = value)) + \n  geom_point() +\n  ylab(\"bill_length_mm\") +\n  facet_wrap(~ draw, labeller = label_both)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\nWith `predict()`, we can use the entire posterior-predictive distribution to simulate new data based on the values of our predictor variable(s). To give you a better sense of what's happening under the hood, here's an `as_draws_df()` based alternative.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\n# walk this code through\nas_draws_df(fit1.b) %>% \n  rename(beta0 = b_Intercept,\n         beta1 = b_body_mass_g) %>% \n  select(.draw, beta0, beta1, sigma) %>% \n  slice_sample(n = 6) %>% \n  expand_grid(chinstrap %>% select(body_mass_g)) %>% \n  mutate(bill_length_mm = rnorm(n = n(),\n                                mean = beta0 + beta1 * body_mass_g,\n                                sd = sigma)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = bill_length_mm)) + \n  geom_point() +\n  facet_wrap(~ .draw, labeller = label_both)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nNow take a look at what happens when we plot the densities of several simulated draws.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\n\nas_draws_df(fit1.b) %>% \n  rename(beta0 = b_Intercept,\n         beta1 = b_body_mass_g) %>% \n  select(.draw, beta0, beta1, sigma) %>% \n  slice_sample(n = 50) %>%  # increase the number of random draws\n  expand_grid(chinstrap %>% select(body_mass_g)) %>% \n  mutate(bill_length_mm = rnorm(n = n(),\n                                mean = beta0 + beta1 * body_mass_g,\n                                sd = sigma)) %>% \n  \n  ggplot(aes(x = bill_length_mm, group = .draw)) + \n  geom_density(size = 1/4, color = alpha(\"black\", 1/2)) +\n  coord_cartesian(xlim = range(chinstrap$bill_length_mm) + c(-2, 2))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nThe similarities and differences among the individual density lines give you a sense of the (un)certainty of the posterior-predictive distribution.\n\n## Posterior predictive checks with `pp_check()`\n\nYou just did a posterior predictive check by hand — simulating datasets from the posterior and comparing their densities to the observed data. The `pp_check()` function automates this in one line:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit1.b, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nThe dark line is the observed data density. The light lines are 100 simulated datasets from the posterior predictive distribution. If the model is good, the light lines should envelope the dark line.\n\nWe can also target specific summary statistics:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit1.b, type = \"stat\", stat = \"mean\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n\n```{.r .cell-code}\npp_check(fit1.b, type = \"stat\", stat = \"sd\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-33-2.png){width=672}\n:::\n:::\n\n\nThe `stat = \"mean\"` check shows a histogram of posterior predictive means, with the observed mean as a vertical line. The `stat = \"sd\"` check does the same for spread. These targeted checks isolate whether the model captures specific features of the data.\n\n### Question 3.4 {.unnumbered}\n\nCompare the `pp_check()` output to the manual density overlay you made above. What is `pp_check()` doing under the hood?\n\n::: callout-tip\nLook at the dark line and the light lines. You made something very similar a few chunks ago.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# They are doing something very similar. They both show posterior predictive simulations with density lines (density values at each bill length). pp_check() also shows what the actual data look like.\n```\n:::\n\n\n**This may be a good time for you to work on Exercise 3 (see end of the document).**\n\n# Part 4: Beginning to look at priors\n\n## Bayes' rule\n\nBayes' theorem will allow us to determine the plausibility of various values of our parameter(s) of interest, $\\theta$, given the data $d$, which we can express formally as $\\Pr(\\theta \\mid d)$. Bayes' rule takes on the form\n\n$$\n\\Pr(\\theta \\mid d) = \\frac{\\Pr(d \\mid \\theta) \\Pr(\\theta)}{\\Pr(d)}.\n$$\n\nwhere\n\n-   $\\Pr(d \\mid \\theta)$ is the *likelihood*,\n-   $\\Pr(\\theta)$ is the *prior*,\n-   $\\Pr(d)$ is the *average probability of the data*, and\n-   $\\Pr(\\theta \\mid d)$ is the *posterior*.\n\nWe can express this in words as\n\n$$\n\\text{Posterior} = \\frac{\\text{Probability of the data} \\times \\text{Prior}}{\\text{Average probability of the data}}.\n$$\n\nThe denominator $\\Pr(d)$ is a normalizing constant, and dividing by this constant is what converts the posterior $\\Pr(\\theta \\mid d)$ into a probability metric.\n\n## Prior predictive checks\n\nEvery model makes predictions. Most of the time we think about predictions after fitting — but a model with priors is already making predictions before it sees a single data point. If those predictions are absurd, no amount of data will fully rescue the analysis. A quick check now saves you from trusting results that were compromised from the start.\n\nWe can do this by fitting the model with `sample_prior = \"only\"`, which tells brms to ignore the data entirely and just simulate from the priors and likelihood:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_prior_only <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g,\n  prior = prior(normal(0, 0.01), class = b),\n  sample_prior = \"only\"\n)\n```\n:::\n\n\nNote: we had to set an explicit prior on the slope (`class = b`) because the default flat prior can't be sampled — it spans $-\\infty$ to $\\infty$. We used `normal(0, 0.01)`, which is a reasonable weakly informative prior for this scale.\n\nNow run `pp_check()` on the prior-only model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npp_check(fit_prior_only, ndraws = 50)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\nThe dark line is your real data. The light lines are datasets the model would generate using only the priors — no learning from data at all. If these look wildly different from anything you'd expect to see, the priors are encoding unreasonable assumptions.\n\n### Question 4.1 {.unnumbered}\n\nThe prior predictive check shows data the model would generate *before seeing any real data*. Do the predictions look reasonable? What would you change if they predicted bill lengths of 500 mm (that's 50 cm — about the length of your forearm)?\n\n::: callout-tip\nCompare the light lines to the dark line. Do they cover the same range of values? Recall the summary statistics you computed for `bill_length_mm`.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# The predictions don't seem very reasonable. I would change the prior distribution cover the expected range, centered around 50mm.\n```\n:::\n\n\n## Default priors\n\nTo set your priors with **brms**, the `brm()` function has a `prior` argument. If you don't explicitly use the `prior` argument, `brm()` will use default priors. This is what happened with our `fit1.b` model from above. We used default priors. If you'd like to see what those priors are, execute `fit1.b$prior`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# maybe show str(fit1.b)\nfit1.b$prior\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   prior     class        coef group resp dpar nlpar lb ub\n                  (flat)         b                                        \n                  (flat)         b body_mass_g                            \n student_t(3, 49.5, 3.6) Intercept                                        \n    student_t(3, 0, 3.6)     sigma                                    0   \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nThus, a fuller expression of our model is\n\n$$\n\\begin{align}\n\\text{bill\\_length\\_mm}_i & \\sim \\operatorname{Normal}(\\mu_i, \\sigma) \\\\\n\\mu_i & = \\beta_0 + \\beta_1 \\text{body\\_mass\\_g}_i \\\\\n\\beta_0 & \\sim \\operatorname{Student-t}(3, 49.5, 3.6) \\\\\n\\beta_1 & \\sim \\operatorname{Uniform}(-\\infty, \\infty) \\\\\n\\sigma & \\sim \\operatorname{Student-t}^+(3, 0, 3.6).\n\\end{align}\n$$\n\nIf we had wanted to see the `brm()` defaults before fitting the model, we could have used the `get_prior()` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_prior(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   prior     class        coef group resp dpar nlpar lb ub\n                  (flat)         b                                        \n                  (flat)         b body_mass_g                            \n student_t(3, 49.5, 3.6) Intercept                                        \n    student_t(3, 0, 3.6)     sigma                                    0   \n       source\n      default\n (vectorized)\n      default\n      default\n```\n\n\n:::\n:::\n\n\nIf you recall, the normal distribution is a member of the Student-t family, where the $\\nu$ (aka degrees of freedom or normality parameter) is set to $\\infty$. To give you a sense, here are the densities of three members of the Student-t family, with varying $\\nu$ values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrossing(theta = seq(from = -4.5, to = 4.5, length.out = 200),\n         nu = c(3, 10, Inf)) %>% \n  mutate(density = dt(x = theta, df = nu)) %>% \n  \n  ggplot(aes(x = theta, y = density, color = factor(nu))) +\n  geom_line(linewidth = 1) +\n  scale_color_viridis_d(expression(nu), option = \"A\", end = .7) +\n  labs(title = \"3 members of the Student-t family\",\n       x = expression(theta)) +\n  coord_cartesian(xlim = c(-4, 4))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n:::\n\n\nThus, Student-t distributions have thicker tails when they have smaller $\\nu$ parameters. In the case where $\\nu = 3$, the tails are pretty thick, which means they are more tolerant of more extreme values. And thus priors with small-$\\nu$ parameters will be weaker (i.e., more permissive) than their Gaussian counterparts.\n\nWe can visualize functions from **ggdist** to visualize the default `brm()` priors. We'll start with the `student_t(3, 49.5, 3.6)` $\\beta_0$ prior, and also take the opportunity to compare that with a slightly stronger `normal(49.5, 3.6)` alternative.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(prior(student_t(3, 49.5, 3.6)),\n  prior(normal(49.5, 3.6))) %>% \n  parse_dist() %>% \n  \n  ggplot(aes(xdist = .dist_obj, y = prior)) + \n  stat_halfeye() +\n  labs(x = expression(italic(p)(beta[0])),\n       y = NULL) +\n  coord_cartesian(xlim = c(25, 75))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nSee how the $\\nu = 3$ parameter in the default prior produces much thicker tails than its Gaussian counterpart. We can make the same kind of plot for our default $\\sigma$ prior and its half-Gaussian counterpart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(prior(student_t(3, 0, 3.6), lb = 0),  # note our use of the lb = 0 argument\n  prior(normal(0, 3.6), lb = 0)) %>% \n  parse_dist() %>% \n  \n  ggplot(aes(xdist = .dist_obj, y = prior)) + \n  stat_halfeye(point_interval = mean_qi, .width = c(.90, .99)) +\n  labs(x = expression(italic(p)(sigma)),\n       y = NULL) +\n  coord_cartesian(xlim = c(0, 30))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-41-1.png){width=672}\n:::\n:::\n\n\nHere's how we could have explicitly set our priors by hand.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2.b <- brm(\n  data = chinstrap,\n  bill_length_mm ~ 1 + body_mass_g,\n  prior = prior(student_t(3, 49.5, 3.6), class = Intercept) +\n    prior(student_t(3, 0, 3.6), class = sigma, lb = 0)\n)\n```\n:::\n\n\nCompare the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit1.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: bill_length_mm ~ 1 + body_mass_g \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      32.17      3.50    25.14    39.06 1.00     5214     3163\nbody_mass_g     0.00      0.00     0.00     0.01 1.00     5277     3063\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.92      0.26     2.46     3.47 1.00     1991     1744\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit2.b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: bill_length_mm ~ 1 + body_mass_g \n   Data: chinstrap (Number of observations: 68) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      32.23      3.56    25.33    39.14 1.00     5241     2889\nbody_mass_g     0.00      0.00     0.00     0.01 1.00     5224     2804\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.93      0.25     2.47     3.48 1.00     1794     1696\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n### Question 4.2 {.unnumbered}\n\nCompare the priors in `fit1.b` (default) and `fit2.b` (hand-set). Are they the same? If the results are nearly identical, what does that tell you?\n\n::: callout-tip\nCompare `fit1.b$prior` to the priors you set explicitly in `fit2.b`. Count the parameters — did you set a prior on all of them?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# They show very similar results. We set parameters only for intercept and sigma. So the prior here didn't really affect the model prediction?\n```\n:::\n\n\n::: {.callout-tip collapse=\"true\" title=\"Answer\"}\nThe results are nearly identical because the explicit priors on the intercept and $\\sigma$ match what brms chose by default. The slope ($\\beta_1$) still uses the default flat prior in both models — `fit2.b` didn't set one explicitly, so brms filled it in. The lesson: brms always has priors, whether you set them or not.\n:::\n\nIf you want to learn more about the default prior settings for **brms**, read through the `set_prior` section of the **brms** reference manual (https://CRAN.R-project.org/package=brms/brms.pdf).\n\n## Model comparison with LOO-CV\n\nIn your MLM unit, you compared models with AIC and BIC. The Bayesian analog is **Leave-One-Out Cross-Validation** (LOO-CV).\n\nThe idea: hide one data point, fit the model on the remaining 67, and predict the held-out point. Repeat for every point. Models that predict held-out data well are capturing real structure; models that predict poorly are either too simple or fitting noise.\n\nRather than actually refitting the model 67 times, `loo()` approximates the cross-validation using your existing posterior draws. It estimates how much each data point influenced the fit. Points the model already predicts well had little influence; points that surprised the model — the ones that would have been flagged as unusual in a residual plot — had a lot. Averaging across all points gives you an overall score for how well the model predicts new data. So a model that is consistently unsurprised by held-out points gets a high score, and one that is frequently caught off guard gets a low one.\n\nThe key number in the output is **ELPD** (expected log pointwise predictive density). Higher ELPD = better out-of-sample prediction. When comparing two models, `loo_compare()` puts the better model on top and reports the difference with a standard error. A difference many times larger than its SE is reliable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloo0 <- loo(fit0.b)\nloo1 <- loo(fit1.b)\nloo_compare(loo0, loo1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       elpd_diff se_diff\nfit1.b  0.0       0.0   \nfit0.b -9.1       3.8   \n```\n\n\n:::\n:::\n\n\nThe first row is the better model. The `elpd_diff` column tells you how much better, and `se_diff` tells you how certain that difference is.\n\n### Question 4.3 {.unnumbered}\n\nThe `loo_compare()` output shows that `fit1.b` has better predictive accuracy than `fit0.b`. In practical terms, what does this tell you about whether `body_mass_g` is a useful predictor of `bill_length_mm`?\n\n::: callout-tip\nThe first row in `loo_compare()` is the better model. What does it mean for your research question if the predictor model wins?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your answer here\n# It means that the predictor in our model successfully predicted the outcome variable. We better use body mass as a predictor for bill length, rather than just the mean of overall bill lengths.\n```\n:::\n\n\n### Exercise 3 {.unnumbered}\n\nIn the previous lab, you made a subset of the `penguins` data called `gentoo`, which was only the cases for which `species == \"Gentoo\"`. Do that again and refit the Bayesian model to those data.\n\n-   Subset the data to Gentoo penguins.\n-   Refit the Bayesian `brm()` model on the Gentoo data.\n-   Remake some of the figures from Part 3 with the new model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Enter your code here\ngentoo <- penguins %>% \n  filter(species == \"Gentoo\")\ngentoo %>% \n  pivot_longer(cols = c(body_mass_g, bill_length_mm)) %>% \n  group_by(name) %>% \n  summarise(mean = mean(value, na.rm=TRUE),\n            sd = sd(value, na.rm=TRUE),\n            n_missing = sum(is.na(value))) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  name             mean     sd n_missing\n  <chr>           <dbl>  <dbl>     <int>\n1 bill_length_mm   47.5   3.08         1\n2 body_mass_g    5076.  504.           1\n```\n\n\n:::\n\n```{.r .cell-code}\ngentoo <- gentoo %>% \n  drop_na(body_mass_g, bill_length_mm)\n\nfit1.b.g <- brm(\n  data = gentoo,\n  bill_length_mm ~ 1 + body_mass_g\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning \"C:/PROGRA~1/R/R-43~1.3/bin/x64/Rcmd.exe\" SHLIB foo.c\nusing C compiler: 'gcc.exe (GCC) 12.3.0'\ngcc  -I\"C:/PROGRA~1/R/R-43~1.3/include\" -DNDEBUG   -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/Rcpp/include/\"  -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/RcppEigen/include/\"  -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/RcppEigen/include/unsupported\"  -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/BH/include\" -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/StanHeaders/include/src/\"  -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/StanHeaders/include/\"  -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/RcppParallel/include/\" -DRCPP_PARALLEL_USE_TBB=1 -I\"C:/Users/USER/AppData/Local/R/win-library/4.3/rstan/include\" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DUSE_STANC3 -DSTRICT_R_HEADERS  -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -D_HAS_AUTO_PTR_ETC=0  -include \"C:/Users/USER/AppData/Local/R/win-library/4.3/StanHeaders/include/stan/math/prim/fun/Eigen.hpp\"  -std=c++1y    -I\"C:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/include\"     -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c foo.c -o foo.o\ncc1.exe: warning: command-line option '-std=c++14' is valid for C++/ObjC++ but not for C\nIn file included from C:/Users/USER/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/Core:19,\n                 from C:/Users/USER/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/Dense:1,\n                 from C:/Users/USER/AppData/Local/R/win-library/4.3/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:22,\n                 from <command-line>:\nC:/Users/USER/AppData/Local/R/win-library/4.3/RcppEigen/include/Eigen/src/Core/util/Macros.h:679:10: fatal error: cmath: No such file or directory\n  679 | #include <cmath>\n      |          ^~~~~~~\ncompilation terminated.\nmake: *** [C:/PROGRA~1/R/R-43~1.3/etc/x64/Makeconf:265: foo.o] Error 1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nSAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).\nChain 1: \nChain 1: Gradient evaluation took 3.4e-05 seconds\nChain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.34 seconds.\nChain 1: Adjust your expectations accordingly!\nChain 1: \nChain 1: \nChain 1: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 1: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 1: \nChain 1:  Elapsed Time: 0.07 seconds (Warm-up)\nChain 1:                0.096 seconds (Sampling)\nChain 1:                0.166 seconds (Total)\nChain 1: \n\nSAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).\nChain 2: \nChain 2: Gradient evaluation took 1.6e-05 seconds\nChain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.16 seconds.\nChain 2: Adjust your expectations accordingly!\nChain 2: \nChain 2: \nChain 2: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 2: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 2: \nChain 2:  Elapsed Time: 0.069 seconds (Warm-up)\nChain 2:                0.043 seconds (Sampling)\nChain 2:                0.112 seconds (Total)\nChain 2: \n\nSAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).\nChain 3: \nChain 3: Gradient evaluation took 7e-06 seconds\nChain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.07 seconds.\nChain 3: Adjust your expectations accordingly!\nChain 3: \nChain 3: \nChain 3: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 3: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 3: \nChain 3:  Elapsed Time: 0.058 seconds (Warm-up)\nChain 3:                0.035 seconds (Sampling)\nChain 3:                0.093 seconds (Total)\nChain 3: \n\nSAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).\nChain 4: \nChain 4: Gradient evaluation took 5e-06 seconds\nChain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.05 seconds.\nChain 4: Adjust your expectations accordingly!\nChain 4: \nChain 4: \nChain 4: Iteration:    1 / 2000 [  0%]  (Warmup)\nChain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)\nChain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)\nChain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)\nChain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)\nChain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)\nChain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)\nChain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)\nChain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)\nChain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)\nChain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)\nChain 4: Iteration: 2000 / 2000 [100%]  (Sampling)\nChain 4: \nChain 4:  Elapsed Time: 0.056 seconds (Warm-up)\nChain 4:                0.031 seconds (Sampling)\nChain 4:                0.087 seconds (Total)\nChain 4: \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fit1.b.g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: gaussian \n  Links: mu = identity; sigma = identity \nFormula: bill_length_mm ~ 1 + body_mass_g \n   Data: gentoo (Number of observations: 123) \n  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;\n         total post-warmup draws = 4000\n\nRegression Coefficients:\n            Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept      26.77      2.12    22.57    30.99 1.00     4287     2749\nbody_mass_g     0.00      0.00     0.00     0.00 1.00     4418     2808\n\nFurther Distributional Parameters:\n      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nsigma     2.31      0.15     2.04     2.63 1.00     1423     1545\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n\n```{.r .cell-code}\nmu <- mean(gentoo$bill_length_mm)\nsigma <- sd(gentoo$bill_length_mm)\n\ngentoo %>% \n  ggplot(aes(x = bill_length_mm)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 binwidth = 2.5) +\n  geom_line(data = tibble(bill_length_mm = seq(from = 30, to = 70, by = 0.1)),\n            aes(y = dnorm(x = bill_length_mm, mean = mu, sd = sigma)),\n            color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n\n```{.r .cell-code}\nposterior_summary(fit1.b.g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   Estimate    Est.Error          Q2.5         Q97.5\nb_Intercept    2.677388e+01 2.1223952676  2.256822e+01  3.099412e+01\nb_body_mass_g  4.083996e-03 0.0004166438  3.261566e-03  4.913586e-03\nsigma          2.312385e+00 0.1514853100  2.039575e+00  2.631719e+00\nIntercept      4.750431e+01 0.2079751294  4.708697e+01  4.790844e+01\nlprior        -3.918505e+00 0.0420971873 -4.010345e+00 -3.845047e+00\nlp__          -2.805561e+02 1.2471418362 -2.837898e+02 -2.791317e+02\n```\n\n\n:::\n\n```{.r .cell-code}\nb0    <- posterior_summary(fit1.b.g)[1, 1]\nb1    <- posterior_summary(fit1.b.g)[2, 1]\nsigma <- posterior_summary(fit1.b.g)[3, 1]\n\ncrossing(body_mass_g    = seq(from = min(gentoo$body_mass_g), to = max(gentoo$body_mass_g), length.out = 200),\n         bill_length_mm = seq(from = min(gentoo$bill_length_mm), to = max(gentoo$bill_length_mm), length.out = 200))  %>% \n  mutate(density = dnorm(x = bill_length_mm, \n                         mean = b0 + b1 * body_mass_g,\n                         sd = sigma)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = bill_length_mm)) +\n  geom_raster(aes(fill = density),\n              interpolate = TRUE) +\n  geom_point(data = gentoo,\n             shape = 21, color = \"white\", fill = \"black\", stroke = 1/4) +\n  scale_fill_viridis_c(option = \"A\", begin = .15, limits = c(0, NA)) +\n  coord_cartesian(xlim = range(gentoo$body_mass_g),\n                  ylim = range(gentoo$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-2.png){width=672}\n:::\n\n```{.r .cell-code}\nas_draws_df(fit1.b.g) %>% \n  rename(`beta[0]` = b_Intercept,\n         `beta[1]` = b_body_mass_g) %>% \n  pivot_longer(cols = c(`beta[0]`, `beta[1]`, sigma), \n               names_to = \"parameter\") %>% \n  \n  ggplot(aes(x = value)) +\n  stat_histinterval(.width = .95, normalize = \"panels\") +\n  scale_y_continuous(NULL, breaks = NULL) +\n  labs(title = \"fit1.b.g\",\n       x = \"parameter space\") +\n  facet_wrap(~ parameter, scales = \"free\", labeller = label_parsed)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-3.png){width=672}\n:::\n\n```{.r .cell-code}\nconditional_effects(fit1.b.g) %>% \n  plot(points = TRUE)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-4.png){width=672}\n:::\n\n```{.r .cell-code}\nnd <- tibble(body_mass_g = seq(\n  from = min(gentoo$body_mass_g),\n  to = max(gentoo$body_mass_g),\n  length.out = 100))\n\nfitted(fit1.b.g, \n       newdata = nd,\n       probs = c(.025, .975, .25, .75)) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  # 95% range\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/4) +\n  # 50% range\n  geom_ribbon(aes(ymin = Q25, ymax = Q75),\n              alpha = 1/4) +\n  geom_line(aes(y = Estimate)) +\n  geom_point(data = gentoo,\n             aes(y = bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-5.png){width=672}\n:::\n\n```{.r .cell-code}\nfitted(fit1.b.g, \n       newdata = nd,\n       summary = F) %>% \n  data.frame() %>% \n  set_names(pull(nd, body_mass_g)) %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(body_mass_g = as.double(name)) %>%\n  \n  ggplot(aes(x = body_mass_g, y = value, fill = after_stat(.width))) +\n  stat_lineribbon(.width = ppoints(50)) +\n  scale_fill_distiller(limits = 0:1) +\n  coord_cartesian(ylim = range(gentoo$bill_length_mm)) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-6.png){width=672}\n:::\n\n```{.r .cell-code}\npredict(fit1.b.g, newdata = nd) %>% \n  data.frame() %>% \n  bind_cols(nd) %>% \n  ggplot(aes(x = body_mass_g)) +\n  geom_ribbon(aes(ymin = Q2.5, ymax = Q97.5),\n              alpha = 1/3) +\n  geom_line(aes(y = Estimate)) +\n  # add the data\n  geom_point(data = gentoo,\n             aes(y = bill_length_mm)) +\n  coord_cartesian(ylim = range(gentoo$bill_length_mm))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-7.png){width=672}\n:::\n\n```{.r .cell-code}\nset.seed(1)\n\npredict(fit1.b.g, summary = FALSE, ndraws = 6) %>% \n  data.frame() %>% \n  mutate(draw = 1:n()) %>% \n  pivot_longer(-draw) %>% \n  mutate(row = str_remove(name, \"X\") %>% as.double()) %>% \n  left_join(chinstrap %>% \n              mutate(row = 1:n()),\n            by = join_by(row)) %>% \n  \n  ggplot(aes(x = body_mass_g, y = value)) + \n  geom_point() +\n  ylab(\"bill_length_mm\") +\n  facet_wrap(~ draw, labeller = label_both)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-8.png){width=672}\n:::\n\n```{.r .cell-code}\nas_draws_df(fit1.b.g) %>% \n  rename(beta0 = b_Intercept,\n         beta1 = b_body_mass_g) %>% \n  select(.draw, beta0, beta1, sigma) %>% \n  slice_sample(n = 50) %>%  \n  expand_grid(gentoo %>% select(body_mass_g)) %>% \n  mutate(bill_length_mm = rnorm(n = n(),\n                                mean = beta0 + beta1 * body_mass_g,\n                                sd = sigma)) %>% \n  \n  ggplot(aes(x = bill_length_mm, group = .draw)) + \n  geom_density(size = 1/4, color = alpha(\"black\", 1/2)) +\n  coord_cartesian(xlim = range(gentoo$bill_length_mm) + c(-2, 2))\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-9.png){width=672}\n:::\n\n```{.r .cell-code}\npp_check(fit1.b.g, ndraws = 100)\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-10.png){width=672}\n:::\n\n```{.r .cell-code}\npp_check(fit1.b.g, type = \"stat\", stat = \"mean\")\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_3_files/figure-html/unnamed-chunk-46-11.png){width=672}\n:::\n:::\n\n\n## References\n\nGelman, A., Hill, J., & Vehtari, A. (2020). *Regression and other stories*. Cambridge University Press. https://doi.org/10.1017/9781139161879\n\nKruschke, J. K. (2015). *Doing Bayesian data analysis: A tutorial with R, JAGS, and Stan*. Academic Press. https://sites.google.com/site/doingbayesiandataanalysis/\n\nMcElreath, R. (2020). *Statistical rethinking: A Bayesian course with examples in R and Stan* (Second Edition). CRC Press. https://xcelab.net/rm/statistical-rethinking/\n\nMcElreath, R. (2015). *Statistical rethinking: A Bayesian course with examples in R and Stan*. CRC Press. https://xcelab.net/rm/statistical-rethinking/\n\n## Session information\n",
    "supporting": [
      "Bayes_Lab_3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}