{
  "hash": "66e6130256a31a278bfaa28613f313fe",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Bayes 1 — From Tables to MCMC\"\nsubtitle: \"PSY 504: Advanced Statistics\"\nauthor: \"Yeaju Diana Kim\"\ndate: \"2026-02-20\"\ndate-modified: today\nformat:\n  html:\n    code-fold: true\neditor: visual\n---\n\nConsider the following setting: A factory produces coins, each with a different bias $\\theta_i$. You don't know which coin you received. You have prior beliefs about which coins the factory is likely to produce — $p(\\theta_i)$. You flip the coin $N$ times, observe $Y$ heads, and use that data to figure out which coin you probably got — $p(\\theta_i \\mid \\text{data})$.\n\nIn Monday's lecture, you saw a setting like this play out with a table of probabilities:\n\n-   each row was a different coin (a different $\\theta_i$), showing what it could produce — $p(\\text{data} \\mid \\theta_i)$ — with one column for each possible outcome (0 heads, 1 head, … $N$ heads)\n\n-   you then observed $Y$ heads out of $N$ tosses\n\n-   you fixed the data (the $\\text{data} = Y$ column) and scored each coin on how well it explained your observation — that's the likelihood, $p(\\text{data} = Y \\mid \\theta_i)$\n\n-   then you multiplied each cell of this column by your prior on $\\theta_i$, and divided by the column sum:\n\n$$\\frac{p(\\text{data} = Y \\mid \\theta_i) \\times p(\\theta_i)}{\\sum_i p(\\text{data} = Y \\mid \\theta_i) \\times p(\\theta_i)}$$\n\n-   this is the posterior — you just applied Bayes' rule!\n\nIn this lab, you'll do all of this in R — first by hand, then with `brms`. The entire lab uses coins. But you'll be using three different methods to obtain your posterior — a table, grid approximation, and MCMC.\n\n***A note on how to work through this lab:*** Throughout this lab, you'll find that some code is commented out, and some is left for you to write yourself. You can uncomment the commented code to run it (CMD + Shift + C on selected lines). But before doing so, take a moment to think about how you'd write this yourself. What functions would you use? What inputs are needed, etc? Then uncomment the code, and make sure you understand each line / contrast with your approach before moving on. For the blanks marked \\# Your code here: that's your turn — write the code, run it, and check that the output makes sense before continuing. Also, make sure to answer the descriptive follow-up questions such as \"what does these tell you?\"\\\n\\\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n#install.packages('brms')\nlibrary(brms)\nlibrary(tidybayes)\nlibrary(ggdist)\n```\n:::\n\n\n# Part 1: The lecture table — in R\n\nIn lecture, we built a table with 5 coins ($\\theta_i$ = 0.2, 0.4, 0.5, 0.6, 0.8) and $N = 5$ flips, giving 6 possible outcomes (0 through 5 heads). Let's recreate it, and then observe $Y = 3$ heads.\n\n## Section 1: Build the probability table\n\nUse `dbinom()` to compute the probability of each outcome for each coin. (This is reading **across a row** — $p(\\text{data} \\mid \\theta_i)$ with $\\theta_i$ fixed.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Define our coins\ntheta_values <- c(0.2, 0.4, 0.5, 0.6, 0.8)\n\n## For each theta_i, compute the probability of 0, 1, 2, 3, 4, 5 heads\nprob_table <- tibble(theta = theta_values) %>%\n  rowwise() %>%\n  mutate(\n    probs = list(dbinom(0:5, size = 5, prob = theta))\n  ) %>%\n  unnest_wider(probs, names_sep = \"_\") %>%\n  rename_with(~ paste0(\"heads_\", 0:5), starts_with(\"probs_\"))\n\nprob_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 7\n  theta heads_0 heads_1 heads_2 heads_3 heads_4 heads_5\n  <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n1   0.2 0.328    0.410   0.205   0.0512 0.00640 0.00032\n2   0.4 0.0778   0.259   0.346   0.230  0.0768  0.0102 \n3   0.5 0.0312   0.156   0.312   0.312  0.156   0.0312 \n4   0.6 0.0102   0.0768  0.230   0.346  0.259   0.0778 \n5   0.8 0.00032  0.0064  0.0512  0.205  0.410   0.328  \n```\n\n\n:::\n:::\n\n\n### Question 1.1\n\nVerify that each row sums to 1. What does this tell you?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your code here: using a similar structure as above, compute row sums, mutate it (and excluding the theta column)\nprob_table_sum <- prob_table %>%\n  rowwise() %>%\n  mutate(row_sum = sum(c_across(starts_with(\"heads_\"))))\n\nprob_table_sum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 8\n# Rowwise: \n  theta heads_0 heads_1 heads_2 heads_3 heads_4 heads_5 row_sum\n  <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>\n1   0.2 0.328    0.410   0.205   0.0512 0.00640 0.00032       1\n2   0.4 0.0778   0.259   0.346   0.230  0.0768  0.0102        1\n3   0.5 0.0312   0.156   0.312   0.312  0.156   0.0312        1\n4   0.6 0.0102   0.0768  0.230   0.346  0.259   0.0778        1\n5   0.8 0.00032  0.0064  0.0512  0.205  0.410   0.328         1\n```\n\n\n:::\n:::\n\n\nIt shows that the columns in each row contain probability values.\n\n## Section 2: Read the table down a column\n\nNow fix the data at 3 heads (Y = 3) and read **down the column**. This gives you the likelihood function for Y = 3 — $p(\\text{data} = 3 \\mid \\theta_i)$ — which scores each coin on how well it explains your observation.\n\nHint: you used `dbinom()` in Section 1 across outcomes — now use it across $\\theta_i$ values, fixing the number of heads at 3.\n\n::: {.callout-tip collapse=\"true\" title=\"Code\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n## Score each coin on how well they explain 3 heads out of 5 (Y = 3, N = 5)\nlikelihood_table <- tibble(\n  theta = theta_values,\n  likelihood = dbinom(3, size = 5, prob = theta_values)\n)\n\nlikelihood_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  theta likelihood\n  <dbl>      <dbl>\n1   0.2     0.0512\n2   0.4     0.230 \n3   0.5     0.312 \n4   0.6     0.346 \n5   0.8     0.205 \n```\n\n\n:::\n:::\n\n:::\n\n### Question 2.1\n\nDoes the likelihood column sum to 1? Compute it. What does this tell you about the likelihood?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your code here\nsum(likelihood_table$likelihood)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.1445\n```\n\n\n:::\n:::\n\n\nThese values together are not probabilities of getting 3 heads.\n\n### Question 2.2\n\nWhich $\\theta_i$ has the highest likelihood score? That's the MLE. Can you call it a probability? Why or why not?\n\ntheta = 0.6 has the highest likelihood score. This is not a probability of getting 3 heads, as the five values don't sum to 1. The likelihood function is not a probability distribution over theta.\n\n## Section 3: Compute the posterior with a flat prior\n\nNow do what Bayes' rule does: multiply each likelihood by a prior, then normalize so it sums to 1.\n\nStart with a flat prior — each $\\theta_i$ is equally plausible before seeing data. You have the `likelihood_table` from Section 2. Add columns for the prior, the product of prior × likelihood, and the normalized posterior.\n\n::: {.callout-tip collapse=\"true\" title=\"Code\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_table <- likelihood_table %>%\n  mutate(\n    prior = 1 / n(),                          # flat prior: each theta_i gets equal weight\n    prior_x_likelihood = prior * likelihood,   # numerator of Bayes' rule\n    posterior = prior_x_likelihood / sum(prior_x_likelihood)  # normalize\n  )\n\nposterior_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  theta likelihood prior prior_x_likelihood posterior\n  <dbl>      <dbl> <dbl>              <dbl>     <dbl>\n1   0.2     0.0512   0.2             0.0102    0.0447\n2   0.4     0.230    0.2             0.0461    0.201 \n3   0.5     0.312    0.2             0.0625    0.273 \n4   0.6     0.346    0.2             0.0691    0.302 \n5   0.8     0.205    0.2             0.0410    0.179 \n```\n\n\n:::\n:::\n\n:::\n\n### Question 3.1\n\nVerify that the posterior column sums to 1. What does this tell you?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your code here\nsum(posterior_table$posterior)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1\n```\n\n\n:::\n:::\n\n\nThe posterior is a probability distribution over theta!\n\n### Question 3.2\n\nIn lecture, we asked: \"There's a \\_\\_\\_% chance that $\\theta$ is 0.6.\" Fill in the blank using your posterior table. Can you also state: \"There's a \\_\\_\\_% chance that $\\theta$ is 0.5 or 0.6\"?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your code here\nposterior_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  theta likelihood prior prior_x_likelihood posterior\n  <dbl>      <dbl> <dbl>              <dbl>     <dbl>\n1   0.2     0.0512   0.2             0.0102    0.0447\n2   0.4     0.230    0.2             0.0461    0.201 \n3   0.5     0.312    0.2             0.0625    0.273 \n4   0.6     0.346    0.2             0.0691    0.302 \n5   0.8     0.205    0.2             0.0410    0.179 \n```\n\n\n:::\n:::\n\n\nThere's a 30.2% chance that $\\theta$ is 0.6. And there's a 57.5% chance that $\\theta$ is 0.5 or 0.6.\n\nYou just did something that the likelihood alone could not do — you made a probability statement about a parameter.\n\n## Section 4: Change the prior\n\nNow use an informative prior — \"most coins are roughly fair.\" Assume that the bias probabilities are c(0.05, 0.20, 0.50, 0.20, 0.05)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nposterior_informative <- likelihood_table %>%\n  mutate(\n    # Prior peaked at 0.5, lower at extremes\n    prior = c(0.05, 0.20, 0.50, 0.20, 0.05),\n    prior_x_likelihood = prior * likelihood,\n    posterior = prior_x_likelihood / sum(prior_x_likelihood)\n  )\n\nposterior_informative\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 5\n  theta likelihood prior prior_x_likelihood posterior\n  <dbl>      <dbl> <dbl>              <dbl>     <dbl>\n1   0.2     0.0512  0.05            0.00256   0.00901\n2   0.4     0.230   0.2             0.0461    0.162  \n3   0.5     0.312   0.5             0.156     0.550  \n4   0.6     0.346   0.2             0.0691    0.243  \n5   0.8     0.205   0.05            0.0102    0.0360 \n```\n\n\n:::\n:::\n\n\n### Question 4.1\n\nCompare this posterior to the flat-prior posterior. Which $\\theta$ is most probable now? Did the prior pull the estimate? In which direction?\n\nThis time, theta = 0.5 is the most probable. The prior pulled toward the middle.\n\n### 4.2\n\nPlot both posteriors side by side.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Combine the two posteriors for plotting\nbind_rows(\n  posterior_table %>% mutate(prior_type = \"Flat prior\"),\n  posterior_informative %>% mutate(prior_type = \"Informative prior\")\n) %>%\n  ggplot(aes(x = factor(theta), y = posterior, fill = prior_type)) +\n  geom_col(position = \"dodge\") +\n  labs(x = expression(theta), y = \"Posterior probability\",\n       fill = \"Prior\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n### Question 4.3\n\nThe data are the same (3 heads out of 5). Only the prior changed. Why did the posterior shift? When would this matter more — with 5 flips or 500 flips?\n\nThe prior can shift the posterior because it weights the data when generating posteriors. This matters more when sample size is small (e.g., 5 flips).\n\n# Part 2: Grid approximation — finer resolution\n\nWith only 5 values of $\\theta_i$, we got a rough picture. What if we tried 1,000 values between 0 and 1? That's grid approximation — the same logic, just with a much finer grid. Now $\\theta$ becomes effectively continuous.\n\n## Section 5: Grid approximation with a flat prior\n\nReplace the 5 $\\theta_i$ values with `seq(0, 1, length.out = 1000)` and repeat the same multiply-and-normalize steps from Section 3. Then plot the posterior.\n\n::: {.callout-tip collapse=\"true\" title=\"Code\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n## Define a fine grid of theta values\ngrid <- tibble(\n  theta = seq(0, 1, length.out = 1000)\n) %>%\n  mutate(\n    prior = 1,                                           # flat prior (unnormalized is fine)\n    likelihood = dbinom(3, size = 5, prob = theta),      # score each theta\n    unstd_posterior = prior * likelihood,                 # prior × likelihood\n    posterior = unstd_posterior / sum(unstd_posterior)     # normalize\n  )\n\n## Plot the posterior\nggplot(grid, aes(x = theta, y = posterior)) +\n  geom_line() +\n  labs(x = expression(theta), y = \"Posterior probability\",\n       title = \"Posterior: 3 heads out of 5 (Y = 3, N = 5), flat prior\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n:::\n\n### Question 5.1\n\nWhere is the peak of the posterior? Does this match the MLE from Section 2?\n\nThe peak is around 0.59, which matches the MLE from section 2.\n\n## Section 6: Grid approximation with an informative prior\n\nNow replace the flat prior with a Beta(10, 10) distribution — peaked near 0.5, skeptical of extreme values.\\\n\\\n***Note below:** The likelihood and posterior are on different scales, so we rescale the likelihood to the same height for visual comparison. It's juat a plotting/visualization trick. The shapes and peaks are what matter here, not the y-axis values.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrid_informative <- tibble(\n  theta = seq(0, 1, length.out = 1000)\n) %>%\n  mutate(\n    prior = dbeta(theta, 10, 10),                        # peaked near 0.5\n    likelihood = dbinom(3, size = 5, prob = theta),\n    unstd_posterior = prior * likelihood,\n    posterior = unstd_posterior / sum(unstd_posterior)\n  )\n\n## Plot prior, likelihood (rescaled), and posterior together\ngrid_informative %>%\n  mutate(\n    likelihood_scaled = likelihood / max(likelihood) * max(posterior)  # rescale for visibility\n  ) %>%\n  ggplot(aes(x = theta)) +\n  geom_line(aes(y = posterior), color = \"blue\", linewidth = 1) +\n  geom_line(aes(y = prior / sum(prior)), color = \"red\", linetype = \"dashed\") +\n  geom_line(aes(y = likelihood_scaled), color = \"gray50\", linetype = \"dotted\") +\n  labs(x = expression(theta), y = \"Density (rescaled)\",\n       title = \"Blue = Posterior, Red = Prior, Gray = Likelihood\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n### Question 6.1\n\nThe posterior (blue) sits between the prior (red) and the likelihood (gray). Why? What would happen to the posterior if you had $Y = 300$ heads out of $N = 500$ instead of $Y = 3$ out of $N = 5$?\n\nThe posterior sits between the other two because we get the posterior by multiplying prior and likelihood. If the sample size greatly increases, the prior will matter less and the posterior distribution will be closer to the likelihood.\n\n## Section 7: Watch the prior wash out\n\nIncrease the sample size while keeping the same proportion of heads (60%).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Same proportion (60% heads), increasing sample sizes\nsample_sizes <- c(5, 20, 50, 200)\nheads_observed <- round(0.6 * sample_sizes)  # Y = 3, 12, 30, 120\n\ngrid_by_n <- map2_dfr(sample_sizes, heads_observed, function(n, k) {\n  tibble(\n    theta = seq(0, 1, length.out = 1000),\n    n = n,\n    prior = dbeta(theta, 10, 10),\n    likelihood = dbinom(k, size = n, prob = theta),\n    unstd_posterior = prior * likelihood,\n    posterior = unstd_posterior / sum(unstd_posterior)\n  )\n})\n\nggplot(grid_by_n, aes(x = theta, y = posterior)) +\n  geom_line(color = \"blue\") +\n  geom_line(aes(y = prior / sum(prior)), color = \"red\", linetype = \"dashed\",\n            data = grid_by_n %>% filter(n == 5)) +\n  facet_wrap(~ paste0(\"n = \", n), scales = \"free_y\") +\n  labs(x = expression(theta), y = \"Posterior probability\",\n       title = \"Same prior, more data → posterior concentrates\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n### Question 7.1\n\nWhat happens to the posterior as n increases? Does the prior still matter at n = 200? This is what the \"Three ingredients\" slide was about: \"With lots of data — likelihood dominates.\"\n\nAs n increases, the posterior centers closer to the likelihood and gets narrower.\n\n# Part 3: Let brms do it\n\nGrid approximation works beautifully for one parameter. But your regression models have $\\beta_0$, $\\beta_1$, and $\\sigma$ — three parameters. A 3D grid with 1000 points per dimension means 1,000,000,000 cells. That's why we need MCMC. Let's fit the same coin problem with `brms` and see that it gives us the same answer.\n\n## Section 8: Set up the coin data\n\n`brms` needs data in a data frame. For a binomial model, we tell it how many successes and how many trials.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Our coin data: Y = 3 heads out of N = 5 flips\ncoin_data <- data.frame(\n  heads = 3,\n  trials = 5\n)\n```\n:::\n\n\n## Section 9: Fit with brms — flat prior\n\nWe'll use `family = binomial` and a very wide prior on the intercept (which is on the logit scale). A wide prior on the logit scale approximates a flat prior on the probability scale.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_flat <- brm(\n  heads | trials(trials) ~ 1,     # intercept-only binomial model\n  family = binomial(link = \"logit\"),\n  data = coin_data,\n  prior = prior(normal(0, 10), class = Intercept),  # wide prior ≈ flat on prob scale\n  seed = 504,\n  iter = 4000, warmup = 1000, chains = 4\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(fit_flat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Family: binomial \n  Links: mu = logit \nFormula: heads | trials(trials) ~ 1 \n   Data: coin_data (Number of observations: 1) \n  Draws: 4 chains, each with iter = 4000; warmup = 1000; thin = 1;\n         total post-warmup draws = 12000\n\nRegression Coefficients:\n          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS\nIntercept     0.47      1.04    -1.51     2.65 1.00     4087     4536\n\nDraws were sampled using sampling(NUTS). For each parameter, Bulk_ESS\nand Tail_ESS are effective sample size measures, and Rhat is the potential\nscale reduction factor on split chains (at convergence, Rhat = 1).\n```\n\n\n:::\n:::\n\n\n### Question 9.1\n\nThe intercept is on the logit scale. To convert to $\\theta$ (probability scale), apply the inverse logit: `plogis()`. What's the posterior mean of $\\theta$? Is it closer to 0.5 or 0.6? Why?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract posterior draws of the intercept\ndraws_flat <- as_draws_df(fit_flat) %>%\n  mutate(theta = plogis(b_Intercept))  # convert logit → probability\n\n# Posterior mean of theta\nmean(draws_flat$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5938141\n```\n\n\n:::\n:::\n\n\nIt's closer to 0.6 because the prior was very wide and almost flat.\n\n### Question 9.2\n\nHow does this compare to your grid approximation result from Section 5?\n\nThe peak seems quite similar to that from section 5!\n\n## Section 10: Plot the posterior from MCMC draws\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(draws_flat, aes(x = theta)) +\n  geom_histogram(aes(y = after_stat(density)), bins = 50,\n                 fill = \"steelblue\", alpha = 0.7) +\n  labs(x = expression(theta), y = \"Density\",\n       title = \"MCMC posterior: 3 heads out of 5 (Y = 3, N = 5), approximately flat prior\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### Question 10.1\n\nThis histogram is made from 12,000 draws (4 chains × 3000 post-warmup). Each draw is a value of $\\theta$ sampled from the posterior. The histogram IS the posterior. Compare the shape to your grid approximation plot from Section 5 — how does the shape compare to your grid approximation plot from Section 5? What's similar? What's different?\n\nThe overall shape is similar.. but here the peak is more leaning towards 1?\n\n## Section 11: Fit with brms — informative prior\n\nNow use a prior that says \"most coins are roughly fair.\" On the logit scale, $\\theta = 0.5$ corresponds to logit = 0. A Normal(0, 0.5) prior on the logit scale concentrates $\\theta$ near 0.5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_informative <- brm(\n  heads | trials(trials) ~ 1,\n  family = binomial(link = \"logit\"),\n  data = coin_data,\n  prior = prior(normal(0, 0.5), class = Intercept),  # informative: most coins near fair\n  seed = 504,\n  iter = 4000, warmup = 1000, chains = 4\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndraws_informative <- as_draws_df(fit_informative) %>%\n  mutate(theta = plogis(b_Intercept))\n\nmean(draws_informative$theta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5196313\n```\n\n\n:::\n:::\n\n\n### Question 11.1\n\nThe posterior mean shifted compared to the flat prior. In which direction? Why? Does this match what happened in Section 4 when you changed the prior by hand?\n\nIt shifted towards 0.5 because the sample size is very small and the prior mattered a lot in this case. I think it matches with what happened in section 4, where the prior pulled the posterior as well.\n\n## Section 12: Overlay both posteriors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbind_rows(\n  draws_flat %>% select(theta) %>% mutate(prior_type = \"Wide (≈ flat)\"),\n  draws_informative %>% select(theta) %>% mutate(prior_type = \"Informative\")\n) %>%\n  ggplot(aes(x = theta, fill = prior_type)) +\n  geom_density(alpha = 0.5) +\n  labs(x = expression(theta), y = \"Density\",\n       fill = \"Prior\",\n       title = \"Same data, different priors → different posteriors\") +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Dropping 'draws_df' class as required metadata was removed.\nWarning: Dropping 'draws_df' class as required metadata was removed.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Bayes_Lab_1_Coins_DianaKim_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n### Question 12.1\n\nWith only 5 flips, the prior matters. What would you expect if you had 500 flips? (You can test this: change the data to `heads = 300, trials = 500` and refit both models.)\n\nThe plots now overlap!! The prior no longer matters here.\n\n## Section 13: Fill in the blank\n\nUsing your posterior draws, make the probability statements that MLE cannot. Hint: what fraction of your draws satisfy a given condition? Think about what `mean()` returns when applied to a logical vector.\n\n::: {.callout-tip collapse=\"true\" title=\"Code\"}\n\n::: {.cell}\n\n```{.r .cell-code}\n# \"What's the probability that theta > 0.5?\"\nmean(draws_flat$theta > 0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6730833\n```\n\n\n:::\n\n```{.r .cell-code}\n# \"What's the probability that theta is between 0.4 and 0.8?\"\nmean(draws_flat$theta > 0.4 & draws_flat$theta < 0.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6331667\n```\n\n\n:::\n:::\n\n:::\n\nThere's a 67.3% chance that theta is larger than 0.5. And there's a 63.3% chance that theta lies between 0.4 and 0.8.\n\n### Question 13.1\n\nIn lecture, the blank was: \"There's a \\_\\_\\_% chance that $\\theta$ is 0.6.\" With continuous posterior draws, we can't ask about a single point. Instead, we ask about intervals. Compute: \"There's a 17.3% chance that $\\theta$ is between 0.55 and 0.65.\" How does this compare to the grid approximation posterior at $\\theta = 0.6$?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(draws_flat$theta > 0.55 & draws_flat$theta < 0.65) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.17375\n```\n\n\n:::\n:::\n\n\nThe grid approximation posterior just shows how high the posterior is at the point where theta = 0.6. The 17.3% chance here is an area under the posterior curve.\n\n## Section 14: Credible intervals\n\nThe 95% credible interval is the central 95% of the posterior draws. This has the interpretation that frequentist confidence intervals don't: \"There's a 95% probability that $\\theta$ lies within this interval.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 95% credible interval\nquantile(draws_flat$theta, probs = c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n0.1806043 0.9342980 \n```\n\n\n:::\n:::\n\n\n### Question 14.1\n\nIs $\\theta = 0.5$ inside the 95% credible interval? What about $\\theta = 0.2$? What does this tell you?\n\nBoth theta = 0.5 and theta = 0.2 are inside the interval. This posterior is very wide and include various values.\n\n# Wrapping up\n\nYou just solved the same problem three ways:\n\n1.  **By hand** (5 $\\theta_i$ values, a table, multiply and normalize)\n2.  **Grid approximation** (1,000 $\\theta$ values, same logic, finer resolution)\n3.  **MCMC via brms** (12,000 draws from the posterior, no grid needed)\n\nAll three gave you the same answer. The first two don't scale to real models with many parameters. The third does. That's why we use `brms`.\n\n### Final reflection\n\nIn your own words, explain the connection between the posterior table from Section 3 and the histogram from Section 10. What's the same? What's different?\n\nThe prior was flat in both, and their peaks for theta are at similar points. However, the histogtam shows more continuous change in posteriors over thetas. The table indicates exact probabilities while the histogram shows interval probabilities.\n\n## References\n\nKurz, A. S. (2025). *Statistical rethinking with brms, ggplot2, and the tidyverse: Second edition* (Version 1.2.0). <https://bookdown.org/content/4857/>\n\nMcElreath, R. (2020). *Statistical rethinking: A Bayesian course with examples in R and Stan* (Second Edition). CRC Press.\n\n## Session information\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.3.3 (2024-02-29 ucrt)\nPlatform: x86_64-w64-mingw32/x64 (64-bit)\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n\n\nlocale:\n[1] LC_COLLATE=Korean_Korea.utf8  LC_CTYPE=Korean_Korea.utf8   \n[3] LC_MONETARY=Korean_Korea.utf8 LC_NUMERIC=C                 \n[5] LC_TIME=Korean_Korea.utf8    \n\ntime zone: America/New_York\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] ggdist_3.3.3    tidybayes_3.0.7 brms_2.22.0     Rcpp_1.0.14    \n [5] lubridate_1.9.4 forcats_1.0.0   stringr_1.6.0   dplyr_1.1.4    \n [9] purrr_1.0.2     readr_2.1.5     tidyr_1.3.1     tibble_3.2.1   \n[13] ggplot2_4.0.0   tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1     svUnit_1.0.8         farver_2.1.1        \n [4] loo_2.9.0            S7_0.2.0             fastmap_1.2.0       \n [7] TH.data_1.1-4        tensorA_0.36.2.1     digest_0.6.35       \n[10] estimability_1.5.1   timechange_0.3.0     lifecycle_1.0.5     \n[13] StanHeaders_2.32.10  processx_3.8.6       survival_3.5-8      \n[16] magrittr_2.0.3       posterior_1.6.1      compiler_4.3.3      \n[19] rlang_1.1.3          tools_4.3.3          yaml_2.3.10         \n[22] knitr_1.50           labeling_0.4.3       bridgesampling_1.2-1\n[25] htmlwidgets_1.6.4    pkgbuild_1.4.8       curl_6.2.2          \n[28] plyr_1.8.9           RColorBrewer_1.1-3   multcomp_1.4-28     \n[31] abind_1.4-8          withr_3.0.2          grid_4.3.3          \n[34] stats4_4.3.3         xtable_1.8-4         colorspace_2.1-0    \n[37] inline_0.3.21        emmeans_2.0.0        scales_1.4.0        \n[40] MASS_7.3-60.0.1      cli_3.6.2            mvtnorm_1.3-3       \n[43] rmarkdown_2.30       generics_0.1.4       RcppParallel_5.1.10 \n[46] rstudioapi_0.17.1    reshape2_1.4.4       tzdb_0.4.0          \n[49] rstan_2.32.7         splines_4.3.3        bayesplot_1.15.0    \n[52] parallel_4.3.3       matrixStats_1.5.0    vctrs_0.6.5         \n[55] V8_8.0.1             Matrix_1.6-5         sandwich_3.1-1      \n[58] jsonlite_2.0.0       callr_3.7.6          hms_1.1.3           \n[61] arrayhelpers_1.1-0   glue_1.7.0           ps_1.9.0            \n[64] codetools_0.2-19     distributional_0.6.0 stringi_1.8.7       \n[67] gtable_0.3.6         QuickJSR_1.7.0       pillar_1.11.1       \n[70] htmltools_0.5.8.1    Brobdingnag_1.2-9    R6_2.6.1            \n[73] evaluate_1.0.5       lattice_0.22-5       backports_1.4.1     \n[76] rstantools_2.6.0     coda_0.19-4.1        gridExtra_2.3       \n[79] nlme_3.1-164         checkmate_2.3.2      xfun_0.52           \n[82] zoo_1.8-13           pkgconfig_2.0.3     \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Bayes_Lab_1_Coins_DianaKim_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}